UPDATE [series].[RCG.LOAN_DAILY.2023-07-31 (FINAL)]
SET
	[DIVISI] = REPLACE([SOURCE].[Segmen_BSI], 'Consumer', 'Konsumer')
	,[PRODUK] = [SOURCE].[PRODUK_BSI]
	,[PRODUK_DETAIL] = [SOURCE].[PRODUK_BSI_DETAIL]
	,[KOL_LOAN] = [SOURCE].[KolLoan]
	,[KOL_CIF] = [SOURCE].[KolCIF_NonSuper]
	,[KOL_SUPERCIF] = [SOURCE].[KolCIF]
	,[OS_POKOK_PSAK] = [SOURCE].[OSPOKOKCONVERSION PSAK]
	,[OS_POKOK] = [SOURCE].[OSPOKOKCONVERSION]
	,[CKPN] = [SOURCE].[Nominal_CKPN-PPAP]
	,[KODECABANG] = [SOURCE].[KodeOutlet_BSI]
	,[NAMACABANG] = [SOURCE].[Nama_Outlet_BSI]
FROM [series].[RCG.LOAN_DAILY.2023-07-31 (FINAL)] [TARGET]
LEFT JOIN [series].[CRG.LOAN_DAILY.2023-07-31 (FINAL)] [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
WHERE
	(
		(
			[TARGET].[DIVISI] IN ('Hasanah Card')
			AND LEFT([TARGET].[KOL_SUPERCIF], 1) = LEFT([SOURCE].[KOLCIF], 1)
		)
		OR [TARGET].[DIVISI] NOT IN ('Hasanah Card')
	)
AND [SOURCE].[NOLOAN] IS NOT NULL;

UPDATE [series].[RCG.LOAN_DAILY.2023-07-31 (FINAL)]
SET
	[NAMACABANG] = [SOURCE].[cabangBSI_Desk]
	,[AREA] = COALESCE([SOURCE].[areaBSI_Desk], [TARGET].[AREA])
	,[REGION] = COALESCE([SOURCE].[regionBSI_Desk], [TARGET].[REGION])
FROM [series].[RCG.LOAN_DAILY.2023-07-31 (FINAL)] [TARGET]
LEFT JOIN [mapping].[PORTOFOLIO_JOIN.MAPPING.JOIN.MAPPING_OUTLET_EDA] [SOURCE]
	ON [TARGET].[KODECABANG] = [SOURCE].[cabangBSI]
WHERE [SOURCE].[cabangBSI] IS NOT NULL
AND [DIVISI] NOT IN ('SEKURITISASI ASET');