SELECT
	[TARGET].[TGL_DATA] [TGL_BASE] --LAST MONTH 2023-04-30
	,[TARGET].[TGL_DATA] [TGL_UPDATE] --UPDATE 2023-05-08
	,[TARGET].[NOLOAN]
	,[TARGET].[NOMORCIF]
	,[TARGET].[SUPERCIF]
	,[TARGET].[NAMANASABAH]
	,[TARGET].[KODECABANG]
	,[TARGET].[NAMACABANG]
	,[TARGET].[AREA]
	,[TARGET].[REGION]
	,[TARGET].[TANGGAL_CAIR] --LAST MONTH
	,[SUPERCIF].[TANGGAL_CAIR] [TANGGAL_CAIR_SUPERCIF] --LAST MONTH
	,LEFT([SUPERCIF].[TANGGAL_CAIR], 4) [TAHUN_CAIR_SUPERCIF] --LAST MONTH
	,NULL [TANGGAL_RESTRUKTUR] --LAST MONTH
	,NULL [TANGGAL_RESTRUKTUR_SUPERCIF] --LAST MONTH
	,[TARGET].[DIVISI]
	,[TARGET].[PRODUK]
	,[TARGET].[PRODUK_DETAIL]
	,[TARGET].[KOL_LOAN]
	,[TARGET].[KOL_CIF]
	,[TARGET].[KOL_SUPERCIF] --LAST MONTH
	,[SUPERCIF].[KOL_TERBAIK] [KOL_TERBAIK_SUPERCIF] --LAST MONTH
	,[SUPERCIF].[KOL_TERBURUK] [KOL_TERBURUK_SUPERCIF] --LAST MONTH
	,[TARGET].[OS_POKOK_PSAK] --LAST MONTH
	,[TARGET].[OS_POKOK] --LAST MONTH
	,[TARGET].[CKPN]
	,[TARGET].[CKPN] / COALESCE(NULLIF([TARGET].[OS_POKOK_PSAK], 0.00), NULLIF([TARGET].[CKPN], 0.00), 1.00) [RAT_CKPN_PSAK] --LAST MONTH
	,[TARGET].[CKPN] / COALESCE(NULLIF([TARGET].[OS_POKOK_PSAK], 0.00), NULLIF([TARGET].[CKPN], 0.00), 1.00) [RAT_CKPN] --LAST MONTH
	,[CIF_DETAIL].[NPWP] --LAST MONTH
	,CASE
		WHEN [PRODUK] IN ('KUR') THEN 'KUR'
		WHEN [PRODUK] IN ('GRIYA FLPP') THEN 'FLPP'
		WHEN [PRODUK] IN ('LINKAGE') AND [OS_POKOK] >= 1500000000 THEN 'VALIDASI NOTA'
		WHEN [KOL_SUPERCIF] NOT IN ('3', '4', '5') THEN 'ONE OBLIGOR'
	END [KET_LAIN_LAIN] --LAST MONTH
	,NULL [FLAGGING_ELIGIBLE] --LAST MONTH
	
	,NULL [TANGGAL_CAIR_UPDATE] --UPDATE
	,NULL [TAHUN_CAIR_UPDATE] --UPDATE
	,NULL [TANGGAL_RESTRUKTUR_UPDATE] --UPDATE
	,NULL [KOL_LOAN_UPDATE] --UPDATE
	,NULL [KOL_SUPERCIF_UPDATE] --UPDATE
	,NULL [KOL_TERBAIK_SUPERCIF_UPDATE] --LAST MONTH
	,NULL [KOL_TERBURUK_SUPERCIF_UPDATE] --LAST MONTH
	,NULL [OS_POKOK_PSAK_UPDATE] --UPDATE
	,NULL [OS_POKOK_PSAK_UPDATE] --UPDATE
	,NULL [CKPN_UPDATE]
	,NULL [RAT_CKPN_PSAK_UPDATE] --UPDATE
	,NULL [RAT_CKPN_UPDATE] --UPDATE
	,NULL [NPWP_UPDATE] --UPDATE
	,NULL [KET_LAIN_LAIN_UPDATE] --UPDATE
	,NULL [FLAGGING_ELIGIBLE_UPDATE] --UPDATE
FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)] [TARGET]
OUTER APPLY (
	SELECT
		SUM([OS_POKOK_PSAK]) [OS_POKOK_PSAK]
		,SUM([CKPN]) [CKPN]
		,MAX([TANGGAL_CAIR]) [TANGGAL_CAIR]
		,MAX([KOL_LOAN]) [KOL_TERBURUK]
		,MIN([KOL_LOAN]) [KOL_TERBAIK]
	FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
	WHERE [TARGET].[SUPERCIF] = [SUPERCIF]
) [SUPERCIF]
LEFT JOIN [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [CIF_DETAIL]
	ON [TARGET].[NOMORCIF] = [CIF_DETAIL].[NOMORCIF]
WHERE [TARGET].[SUPERCIF] IN
(
	SELECT
		[SUPERCIF]
	FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
	WHERE [KOL_SUPERCIF] IN ('3', '4', '5')
	AND [DIVISI] IN ('Hasanah Card', 'Mikro', 'SME', 'Pawning', 'Konsumer')
)