DECLARE @TABLE_CUR VARCHAR(MAX), @NOMORCIF VARCHAR(MAX)='', @SUPERCIF VARCHAR(MAX)='', @NOLOAN VARCHAR(MAX)='LD2224545063', @POINTER INT = 1, @TGL_DATA DATE = '2023-06-30', @SQL_QUERY VARCHAR(MAX);

CREATE TABLE #RESULT (
	TGL_DATA DATE
	,NOLOAN VARCHAR(255)
	,NOMORCIF VARCHAR(255)
	,SUPERCIF VARCHAR(255)
	,NAMANASABAH VARCHAR(255)
	,KODECABANG VARCHAR(255)
	,NAMACABANG VARCHAR(255)
	,AREA VARCHAR(255)
	,REGION VARCHAR(255)
	,DIVISI VARCHAR(255)
	,PRODUK VARCHAR(255)
	,PRODUK_DETAIL VARCHAR(255)
	,JENISPIUTANGPEMBIAYAAN VARCHAR(255)
	,CYCLE VARCHAR(255)
	,KOL_LOAN VARCHAR(255)
	,KOL_CIF VARCHAR(255)
	,KOL_SUPERCIF VARCHAR(255)
	,OS_POKOK_PSAK DECIMAL(20, 2)
	,OS_POKOK DECIMAL(20, 2)
	,OS_MARGIN DECIMAL(20, 2)
	,REALISASI_BAGIHASIL DECIMAL(20, 2)
);

WHILE @POINTER <= 9
BEGIN
	
	SET @TABLE_CUR = (
		SELECT TOP 1
			CONCAT('[', SCHEMA_NAME(SCHEMA_ID), '].[', name, ']') AS NAME
		FROM [sys].[objects]
		WHERE type_desc = 'USER_TABLE'
		AND name LIKE 'RCG.LOAN_DAILY.____-__-__%'
		AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) = @TGL_DATA
		ORDER BY
			TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) DESC
			,CASE
				WHEN name LIKE ('%(FINAL)') THEN 1
				WHEN name LIKE ('%(FOG)') THEN 0.5
				WHEN name LIKE ('%(QC)') THEN -1
				ELSE 0
			END DESC
	);
	
	SET @SQL_QUERY = CONCAT(
		'SELECT
			TGL_DATA
			,NOLOAN
			,NOMORCIF
			,SUPERCIF
			,NAMANASABAH
			,KODECABANG
			,NAMACABANG
			,AREA
			,REGION
			,DIVISI
			,PRODUK
			,PRODUK_DETAIL
			,JENISPIUTANGPEMBIAYAAN
			,CYCLE
			,KOL_LOAN
			,KOL_CIF
			,KOL_SUPERCIF
			,OS_POKOK_PSAK
			,OS_POKOK
			,OS_MARGIN
			,REALISASI_BAGIHASIL
		FROM ', @TABLE_CUR, ' [CUR]
		WHERE [CUR].[SUPERCIF] IN (''', @NOMORCIF, ''', ''', @SUPERCIF, ''')
		OR [CUR].[NOMORCIF] IN (''', @NOMORCIF, ''', ''', @SUPERCIF, ''')
		OR [CUR].[NOLOAN] IN (''', @NOLOAN, ''');'
	);
	
	BEGIN TRY
		INSERT INTO #RESULT
		EXEC(@SQL_QUERY);
		PRINT CONCAT('EKSEKUSI DATA PER ', @TGL_DATA, ' BASED ON BEFORE ', @TABLE_CUR);
	END TRY
	BEGIN CATCH
		PRINT CONCAT('ERROR! ', ERROR_MESSAGE());
	END CATCH
	
	SET @POINTER = @POINTER + 1;
	SET @TGL_DATA = DATEADD(DAY, 1, @TGL_DATA);
END

SELECT * FROM #RESULT;
DROP TABLE #RESULT;