UPDATE [series].[FOG.LOAN_DAILY.2023-07-31]
SET
	[OSPOKOKCONVERSION] = REPLACE([OSPOKOKCONVERSION], ',', '.')
	,[TGLPENCAIRAN] = CONCAT(RIGHT([TGLPENCAIRAN], 4)
	, '-', CASE WHEN RIGHT(LEFT([TGLPENCAIRAN], 2), 1) = '/'
			THEN
				CASE WHEN RIGHT(LEFT(RIGHT(LEFT([TGLPENCAIRAN], 4), 2), 2), 1) = '/' THEN CONCAT('0', LEFT(RIGHT(LEFT([TGLPENCAIRAN], 4), 2), 1)) ELSE RIGHT(LEFT([TGLPENCAIRAN], 4), 2) END
		ELSE
				CASE WHEN RIGHT(LEFT(RIGHT(LEFT([TGLPENCAIRAN], 5), 2), 2), 1) = '/' THEN CONCAT('0', LEFT(RIGHT(LEFT([TGLPENCAIRAN], 5), 2), 1)) ELSE RIGHT(LEFT([TGLPENCAIRAN], 5), 2) END
		END
	, '-', CASE WHEN RIGHT(LEFT([TGLPENCAIRAN], 2), 1) = '/' THEN CONCAT('0', LEFT([TGLPENCAIRAN], 1)) ELSE LEFT([TGLPENCAIRAN], 2) END
	)