WITH CTE AS
(
	SELECT
		[TARGET].[NOLOAN]
		--,[SOURCE].[NOMORCIF] [NOMORCIF_BEFORE]
		,[SOURCE].[SUPERCIF] [SUPERCIF_BEFORE]
		--,[TARGET].[NOMORCIF]
		,[TARGET].[SUPERCIF]
	FROM [series].[RCG.LOAN_DAILY.2022-10-31 (FINAL)] [TARGET]
	FULL OUTER JOIN [series].[RCG.LOAN_DAILY.2022-09-30 (FINAL)] [SOURCE]
		ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
	WHERE NOT (
		RIGHT([TARGET].[NOMORCIF], 15) = RIGHT([SOURCE].[NOMORCIF], 15)
		OR RIGHT([TARGET].[SUPERCIF], 15) = RIGHT([SOURCE].[SUPERCIF], 15)
	)
	AND [SOURCE].[NOLOAN] IS NOT NULL
	AND NOT (
		RIGHT([TARGET].[NOMORCIF], 15) = RIGHT([SOURCE].[SUPERCIF], 15)
		OR RIGHT([TARGET].[SUPERCIF], 15) = RIGHT([SOURCE].[NOMORCIF], 15)
	)
)
SELECT
	[TARGET].*
FROM CTE [TARGET]
LEFT JOIN [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [SOURCE]
	ON [TARGET].[SUPERCIF_BEFORE] = [SOURCE].[NOMORCIF]
WHERE [TARGET].[SUPERCIF] != [SOURCE].[SUPERCIF]