BEGIN TRY
	DROP TABLE [report].[INQUIRY_2];
END TRY
BEGIN CATCH
END CATCH

SELECT
	[TARGET].[TGL_DATA]
	,[TARGET].[NOLOAN]
	,[TARGET].[NOMORCIF]
	,[TARGET].[NAMANASABAH]
	,[TARGET].[KODECABANG]
	,[TARGET].[NAMACABANG]
	,[TARGET].[AREA]
	,[TARGET].[REGION]
	,[TARGET].[DIVISI]
	,[TARGET].[PRODUK]
	,[TARGET].[PRODUK_DETAIL]
	,[TARGET].[CYCLE]
	,CONCAT([KOL_M3].[KOL_SUPERCIF], ' - ', [KOL_M2].[KOL_SUPERCIF], ' - ', [KOL_M1].[KOL_SUPERCIF]) [AGING_KOL_SUPERCIF_3M]
	,[KOL_M1].[KOL_SUPERCIF] [KOL_SUPERCIF_LAST]
	,[TARGET].[KOL_LOAN]
	,[TARGET].[KOL_CIF]
	,[TARGET].[KOL_SUPERCIF]
	,[TARGET].[OS_POKOK_PSAK]
	,[TARGET].[OS_POKOK]
	,TRY_CAST(NULL AS VARCHAR(255)) [StatusPayroll]
	,CASE
		WHEN COALESCE([KOL_M1].[KOL_SUPERCIF], '1') < [TARGET].[KOL_SUPERCIF] THEN 'New DG'
		WHEN COALESCE([KOL_M1].[KOL_SUPERCIF], '1') = [TARGET].[KOL_SUPERCIF] THEN 'Stay'
		WHEN COALESCE([KOL_M1].[KOL_SUPERCIF], '1') > [TARGET].[KOL_SUPERCIF] THEN 'UG/ Churn'
	END [Habitual]
	,TRY_CAST(NULL AS VARCHAR(255)) [PEKERJAAN]
	,TRY_CAST(NULL AS VARCHAR(255)) [JENIS_PEKERJAAN]
	,TRY_CAST(NULL AS VARCHAR(255)) [NAMAPERUSAHAANNASABAH]
INTO [report].[INQUIRY_2]
FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [TARGET]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [TARGET].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [TARGET].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [TARGET].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M1]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [TARGET].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [TARGET].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [TARGET].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M2]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-02-28 (FINAL)]
				WHERE [TARGET].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-02-28 (FINAL)]
				WHERE [TARGET].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-02-28 (FINAL)]
				WHERE [TARGET].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M3]

WHERE [TARGET].[DIVISI] IN ('Konsumer')
AND [TARGET].[PRODUK] IN ('Mitraguna & Other', 'Griya')
AND [TARGET].[KOL_SUPERCIF] IN ('2A', '2B', '2C', '3A')



------------------------------------

UPDATE [report].[INQUIRY_2]
SET
	[StatusPayroll] = COALESCE([CRG].[StatusPayroll], CONCAT(COALESCE([CRG_BY_CIF].[StatusPayroll], 'Not Found'), ' by CIF'))
FROM [report].[INQUIRY_2] [TARGET]
LEFT JOIN [series].[CRG.LOAN_DAILY.2023-04-30] [CRG]
	ON [TARGET].[NOLOAN] = [CRG].[NOLOAN]
LEFT JOIN (
	SELECT
		[NOMORCIF]
		,MAX([StatusPayroll]) [StatusPayroll]
	FROM [series].[CRG.LOAN_DAILY.2023-04-30] [CRG]
	GROUP BY [NomorCIF]
) [CRG_BY_CIF]
	ON [TARGET].[NOMORCIF] = [CRG_BY_CIF].[NOMORCIF];

UPDATE [report].[INQUIRY_2]
SET
	[PEKERJAAN] = COALESCE([SOURCE].[PEKERJAAN], CONCAT(COALESCE([SOURCE_BY_CIF].[PEKERJAAN], 'Tidak ter-Mapping'), ' by CIF'))
	,[JENIS_PEKERJAAN] = COALESCE([CRG].[Jenis_Pekerjaan_EFO_WISE_FOS], CONCAT(COALESCE([CRG_BY_CIF].[Jenis_Pekerjaan_EFO_WISE_FOS], 'Tidak ter-Mapping'), ' by CIF'))
	,[NAMAPERUSAHAANNASABAH] = COALESCE([SOURCE].[NAMAPERUSAHAANNASABAH], CONCAT(COALESCE([SOURCE_BY_CIF].[NAMAPERUSAHAANNASABAH], 'Tidak ter-Mapping'), ' by CIF'))
FROM [report].[INQUIRY_2] [TARGET]
LEFT JOIN [series].[IFOIS.LOAN_DAILY.2023-05-30] [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
LEFT JOIN [series].[CRG.LOAN_DAILY.2023-04-30] [CRG]
	ON [TARGET].[NOLOAN] = [CRG].[NOLOAN]
LEFT JOIN (
	SELECT
		[NOMORCIF]
		,MAX([Jenis_Pekerjaan_EFO_WISE_FOS]) [Jenis_Pekerjaan_EFO_WISE_FOS]
	FROM [series].[CRG.LOAN_DAILY.2023-04-30] [CRG]
	GROUP BY [NomorCIF]
) [CRG_BY_CIF]
	ON [TARGET].[NOMORCIF] = [CRG_BY_CIF].[NOMORCIF]
LEFT JOIN (
	SELECT
		[NOMORCIF]
		,MAX([Pekerjaan]) [Pekerjaan]
		,MAX([NamaPerusahaanNasabah]) [NamaPerusahaanNasabah]
	FROM [series].[IFOIS.LOAN_DAILY.2023-05-30]
	GROUP BY [NomorCIF]
) [SOURCE_BY_CIF]
	ON [TARGET].[NOMORCIF] = [SOURCE_BY_CIF].[NOMORCIF]