SELECT
	COALESCE([RCG].[NOLOAN], [CRG].[NOLOAN]) [NOLOAN]
	,[RCG].[SUPERCIF] [RCG_SUPERCIF]
	,[CRG].[NomorCIF_SUPER] [CRG_SUPERCIF]
	,[RCG].[LOANTYPE] [RCG_LOANTYPE]
	,[RCG].[TANGGAL_CAIR] [RCG_TANGGAL_CAIR]
	,[RCG].[DIVISI] [RCG_DIVISI]
	,[RCG].[PRODUK] [RCG_PRODUK]
	,[RCG].[PRODUK_DETAIL] [RCG_PRODUK_DETAIL]
	,[CRG].[SEGMEN_BSI] [CRG_DIVISI]
	,[CRG].[Produk_BSI] [CRG_PRODUK]
	,[CRG].[Produk_BSI_DETAIL] [CRG_PRODUK_DETAIL]
	,[RCG].[KOL_SUPERCIF] [RCG_KOL]
	,[CRG].[KOLCIF] [CRG_KOL]
	,[RCG].[OS_POKOK_PSAK] [RCG_OS]
	,[CRG].[OSPOKOKCONVERSION PSAK] [CRG_OS]
FROM [series].[RCG.LOAN_DAILY.2023-07-25] [RCG]
FULL OUTER JOIN [series].[CRG.LOAN_DAILY.2023-07-25] [CRG]
	ON [RCG].[NOLOAN] = [CRG].[NOLOAN]
WHERE 1 = 1
-- 	AND [RCG].[NOLOAN] IS NULL
-- 	AND [CRG].[SEGMEN_BSI] NOT IN ('Hasanah Card')
-- 	AND COALESCE(LEFT([RCG].[KOL_CIF], 1), 'X') != COALESCE(LEFT([CRG].[KOLCIF_NonSuper], 1), 'O')
	AND COALESCE(LEFT([RCG].[KOL_SUPERCIF], 1), 'X') != COALESCE(LEFT([CRG].[KOLCIF], 1), 'O')
-- 	AND COALESCE([RCG].[KOL_SUPERCIF], 'X') != COALESCE([CRG].[KOLCIF], 'O')
-- 	AND COALESCE([RCG].[OS_POKOK_PSAK], 0.00) != COALESCE([CRG].[OSPOKOKCONVERSION PSAK], 0.00)
-- 	AND (
-- 		COALESCE([RCG].[DIVISI], 'X') != COALESCE(REPLACE([CRG].[SEGMEN_BSI], 'Consumer', 'Konsumer'), 'O')
-- 		AND COALESCE([RCG].[DIVISI], 'X') != COALESCE(REPLACE([CRG].[SEGMEN_BSI], 'Corporate 1', 'KORPORASI'), 'O')
-- 		AND COALESCE([RCG].[DIVISI], 'X') != COALESCE(REPLACE([CRG].[SEGMEN_BSI], 'Corporate 2', 'KORPORASI'), 'O')
-- 		AND COALESCE([RCG].[DIVISI], 'X') != COALESCE(REPLACE([CRG].[SEGMEN_BSI], 'Corporate 3', 'KORPORASI'), 'O')
-- 		AND COALESCE([RCG].[DIVISI], 'X') != COALESCE(REPLACE([CRG].[SEGMEN_BSI], 'Commercial', 'KOMERSIL'), 'O')
-- 	)
-- 	AND [RCG].[TANGGAL_CAIR] >= '2023-06-01'
	AND NOT ([RCG].[NOLOAN] IS NULL OR [CRG].[NOLOAN] IS NULL)
ORDER BY
	[RCG].[LOANTYPE]
	,[RCG].[SUPERCIF]
	,[RCG].[NOLOAN]