BEGIN TRY
	DROP TABLE #TEMP_01;
	DROP TABLE #TEMP_02;
	DROP TABLE #TEMP_03;
	DROP TABLE #RESULT;
END TRY
BEGIN CATCH
END CATCH

CREATE TABLE #TEMP_01 (
	[NOMORCIF] VARCHAR(100)
	,[OS_POKOK] DECIMAL(20, 2)
	,[ACCT] INTEGER
);

CREATE TABLE #TEMP_02 (
	[NOMORCIF] VARCHAR(100)
	,[OS_POKOK] DECIMAL(20, 2)
	,[TGL_CAIR] DATE
	,[ACCT] INTEGER
);

CREATE TABLE #TEMP_03 (
	[NOMORCIF] VARCHAR(100)
	,[OS] DECIMAL(20, 2)
	,[TGL_EFEKTIF] DATE
	,[ACCT_TUTUP] INTEGER
	,[ACCT_BUKA] INTEGER
);

CREATE TABLE #RESULT (
	[LEGACY_LAMA] varchar(255),
  [NOLOAN_LAMA] varchar(255),
  [NOCIF_LAMA] varchar(255),
  [KODECABANG_LAMA] varchar(255),
  [NAMANASABAH_LAMA] varchar(255),
  [LEGACY_BARU] varchar(255),
  [NOLOAN_BARU] varchar(255),
  [NOCIF_BARU] varchar(255),
  [KODECABANG_BARU] varchar(255),
  [NAMANASABAH_BARU] varchar(255),
  [FLAG_DATA] varchar(255),
  [TGL_EFEKTIF] date,
  [KETERANGAN] varchar(255)
)

INSERT INTO #TEMP_01
SELECT
	[(SOURCE) NOMORCIF_CURRENT] AS [NOMORCIF]
	,SUM(TRY_CAST([(RCG) OS_POKOK_LAST_MONTH] AS DECIMAL(20, 2))) AS [OS_POKOK]
	,COUNT([(SOURCE) NOLOAN_CURRENT]) AS [ACCT]	
FROM [PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT]
WHERE [(RCG) KOL_LOAN_PECAH] IN ('Lunas')
AND [(RCG) DIVISI_BSI] NOT IN ('Pawning', 'Komersil', 'Korporasi')
GROUP BY
	[(SOURCE) NOMORCIF_CURRENT];

INSERT INTO #TEMP_02
SELECT
	[(SOURCE) NOMORCIF_CURRENT] AS [NOMORCIF]
	,SUM(TRY_CAST([(SOURCE) PENCAIRAN_POKOK] AS DECIMAL(20,2))) AS [OS_POKOK]
	,MIN(TRY_CAST([(SOURCE) TANGGAL_CAIR] AS DATE)) AS [TGL_CAIR]
	,COUNT([(SOURCE) NOLOAN_CURRENT]) AS [ACCT]	
FROM [PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT]
WHERE [(RCG) KOL_LOAN_LAST_MONTH] IS NULL
AND [(RCG) KOL_LOAN_PECAH] NOT IN ('Lunas', 'Suspect', 'WO')
AND [(RCG) DIVISI_BSI] NOT IN ('Pawning', 'Komersil', 'Korporasi')
GROUP BY
	[(SOURCE) NOMORCIF_CURRENT];

INSERT INTO #TEMP_03
SELECT
	[TARGET].[NOMORCIF]
	,[TARGET].[OS_POKOK] AS [OS]
	,[SOURCE].[TGL_CAIR] AS [TGL_EFEKTIF]
	,[TARGET].[ACCT] AS [ACCT_TUTUP]
	,[SOURCE].[ACCT] AS [ACCT_BUKA]
FROM #TEMP_01 [TARGET]
LEFT JOIN #TEMP_02 [SOURCE]
	ON [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
	AND COALESCE([TARGET].[OS_POKOK], 0.00) = COALESCE([SOURCE].[OS_POKOK], 0.00)
	AND COALESCE([TARGET].[ACCT], 0) != COALESCE([SOURCE].[ACCT], 0)
	AND TRY_CAST(RIGHT([TARGET].[OS_POKOK], 4) AS DECIMAL(20, 2)) > 0.00
WHERE [SOURCE].[NOMORCIF] IS NOT NULL;

INSERT INTO #TEMP_03
SELECT
	[TARGET].[NOMORCIF]
	,[TARGET].[OS_POKOK] AS [OS]
	,[SOURCE].[TGL_CAIR] AS [TGL_EFEKTIF]
	,[TARGET].[ACCT] AS [ACCT_TUTUP]
	,[SOURCE].[ACCT] AS [ACCT_BUKA]
FROM #TEMP_01 [TARGET]
LEFT JOIN #TEMP_02 [SOURCE]
	ON [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
	AND COALESCE([TARGET].[OS_POKOK], 0.00) = COALESCE([SOURCE].[OS_POKOK], 0.00)
	AND COALESCE([TARGET].[ACCT], 0) = COALESCE([SOURCE].[ACCT], 0)
	AND TRY_CAST(RIGHT([TARGET].[OS_POKOK], 4) AS DECIMAL(20, 2)) > 0.00
WHERE [SOURCE].[NOMORCIF] IS NOT NULL;

INSERT INTO #RESULT (
	[LEGACY_LAMA],
  [NOLOAN_LAMA],
  [NOCIF_LAMA],
  [KODECABANG_LAMA],
  [NAMANASABAH_LAMA],
  [LEGACY_BARU],
  [NOLOAN_BARU],
  [NOCIF_BARU],
  [KODECABANG_BARU],
  [NAMANASABAH_BARU],
  [FLAG_DATA],
  [TGL_EFEKTIF],
  [KETERANGAN]
)
SELECT
	[TUTUP].[(RCG) SOURCE_CURRENT]
	,[TUTUP].[(SOURCE) NOLOAN_CURRENT]
	,[TUTUP].[(SOURCE) NOMORCIF_CURRENT]
	,[TUTUP].[(RCG) KODECABANG_BSI]
	,[TUTUP].[(SOURCE) NAMANASABAH]
	,[BUKA].[(RCG) SOURCE_CURRENT]
	,[BUKA].[(SOURCE) NOLOAN_CURRENT]
	,[BUKA].[(SOURCE) NOMORCIF_CURRENT]
	,[BUKA].[(RCG) KODECABANG_BSI]
	,[BUKA].[(SOURCE) NAMANASABAH]
	,'ONBS'
	,[TARGET].[TGL_EFEKTIF]
	,CASE
		WHEN [TARGET].[ACCT_TUTUP] = [TARGET].[ACCT_BUKA] THEN 'BUKA TUTUP (SUSPECT RCG)'
		ELSE CONCAT('BUKA TUTUP ', [TARGET].[ACCT_TUTUP],' LOAN JADI ', [TARGET].[ACCT_BUKA], ' LOAN (SUSPECT RCG)')
	END
FROM #TEMP_03 [TARGET]
LEFT JOIN [PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT] [TUTUP]
	ON [TARGET].[NOMORCIF] = [TUTUP].[(SOURCE) NOMORCIF_CURRENT]
	AND [TUTUP].[(RCG) KOL_LOAN_PECAH] IN ('Lunas')
	AND [TUTUP].[(RCG) DIVISI_BSI] NOT IN ('Pawning', 'Komersil', 'Korporasi')
LEFT JOIN [PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT] [BUKA]
	ON [TARGET].[NOMORCIF] = [BUKA].[(SOURCE) NOMORCIF_CURRENT]
	AND [BUKA].[(RCG) KOL_LOAN_LAST_MONTH] IS NULL
	AND [BUKA].[(RCG) KOL_LOAN_PECAH] NOT IN ('Lunas', 'Suspect', 'WO')
	AND [BUKA].[(RCG) DIVISI_BSI] NOT IN ('Pawning', 'Komersil', 'Korporasi')
WHERE
	(
		[TARGET].[ACCT_TUTUP] = [TARGET].[ACCT_BUKA]
		AND [BUKA].[(SOURCE) PENCAIRAN_POKOK] = [TUTUP].[(RCG) OS_POKOK_LAST_MONTH]
	) OR ([TARGET].[ACCT_TUTUP] != [TARGET].[ACCT_BUKA])
GROUP BY
	[TUTUP].[(RCG) SOURCE_CURRENT]
	,[TUTUP].[(SOURCE) NOLOAN_CURRENT]
	,[TUTUP].[(SOURCE) NOMORCIF_CURRENT]
	,[TUTUP].[(RCG) KODECABANG_BSI]
	,[TUTUP].[(SOURCE) NAMANASABAH]
	,[BUKA].[(RCG) SOURCE_CURRENT]
	,[BUKA].[(SOURCE) NOLOAN_CURRENT]
	,[BUKA].[(SOURCE) NOMORCIF_CURRENT]
	,[BUKA].[(RCG) KODECABANG_BSI]
	,[BUKA].[(SOURCE) NAMANASABAH]
	,[TARGET].[TGL_EFEKTIF]
	,CASE
		WHEN [TARGET].[ACCT_TUTUP] = [TARGET].[ACCT_BUKA] THEN 'BUKA TUTUP (SUSPECT RCG)'
		ELSE CONCAT('BUKA TUTUP ', [TARGET].[ACCT_TUTUP],' LOAN JADI ', [TARGET].[ACCT_BUKA], ' LOAN (SUSPECT RCG)')
	END;
	
DELETE #RESULT
FROM #RESULT
LEFT JOIN [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [MUTASI]
	ON #RESULT.[NOLOAN_LAMA] = [MUTASI].[NOLOAN_LAMA]
	AND #RESULT.[NOCIF_LAMA] = [MUTASI].[NOCIF_LAMA]
	AND #RESULT.[NOLOAN_BARU] = [MUTASI].[NOLOAN_BARU]
	AND #RESULT.[NOCIF_BARU] = [MUTASI].[NOCIF_BARU]
WHERE [MUTASI].[NOLOAN_LAMA] IS NOT NULL;
	
SELECT * FROM #TEMP_03;
SELECT * FROM #RESULT ORDER BY KETERANGAN;