BEGIN TRY
	DROP TABLE #TEMP_TB_MUTASI_NOLOAN_EX;
	DROP TABLE #TEMP_RESULT_01;
END TRY
BEGIN CATCH
END CATCH

SELECT
	[MAIN].*
INTO #TEMP_TB_MUTASI_NOLOAN_EX
FROM [dbo].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.TGL_AKTIF] [MAIN]
LEFT JOIN [PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [SUB_1]
	ON [MAIN].LEGACY = SUB_1.LEGACY_LAMA
	AND [MAIN].NOLOAN = SUB_1.NOLOAN_LAMA
LEFT JOIN [PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [SUB_2]
	ON [MAIN].LEGACY = SUB_2.LEGACY_BARU
	AND [MAIN].NOLOAN = SUB_2.NOLOAN_BARU
WHERE
--	[MAIN].[NOMORCIF] LIKE '%83212110%' AND
	SUB_1.NOLOAN_BARU IS NULL AND
	SUB_2.NOLOAN_LAMA IS NULL
ORDER BY [MAIN].[TGL_AKTIF_AWAL], [MAIN].[TGL_AKTIF_AKHIR]

DECLARE @TGL_DATA DATE = (SELECT MAX(TGL_AKTIF_AKHIR) FROM #TEMP_TB_MUTASI_NOLOAN_EX)
SELECT

	[MAIN].TGL_AKTIF_AWAL
	,[SECOND].TGL_AKTIF_AWAL AS TGL_MUTASI
	,[SECOND].TGL_AKTIF_AKHIR
	,[MAIN].LEGACY
	,[SECOND].LEGACY AS LEGACY_CURRENT
	,[MAIN].NOLOAN
	,[SECOND].NOLOAN AS NOLOAN_BARU
	,[MAIN].NOMORCIF
	,[SECOND].NOMORCIF AS NOMORCIF_BARU
	,[MAIN].NAMANASABAH
	,[SECOND].NAMANASABAH AS NAMANASABAH_BARU
	,[SECOND].KODE_OUTLET
INTO #TEMP_RESULT_01
FROM 
	#TEMP_TB_MUTASI_NOLOAN_EX [MAIN]
LEFT JOIN #TEMP_TB_MUTASI_NOLOAN_EX [SECOND]
	ON [MAIN].KODE_OUTLET = [SECOND].KODE_OUTLET
	AND COALESCE([MAIN].OS_POKOK_AKHIR, 0.00) = COALESCE([SECOND].OS_POKOK_AWAL, 0.00)
	AND [SECOND].TGL_AKTIF_AWAL BETWEEN DATEADD(d, -3, [MAIN].TGL_AKTIF_AKHIR) AND DATEADD(d, 3, [MAIN].TGL_AKTIF_AKHIR)
	AND [SECOND].TGL_AKTIF_AWAL != [MAIN].TGL_AKTIF_AKHIR
	AND [SECOND].TGL_AKTIF_AWAL != [MAIN].TGL_AKTIF_AWAL
	AND [SECOND].TGL_AKTIF_AWAL != [SECOND].TGL_AKTIF_AKHIR
	AND [MAIN].TGL_AKTIF_AKHIR < DATEADD(d, -3, @TGL_DATA)
	AND
	(
		(
			[MAIN].LEGACY = 'BNIS'
			AND
			[SECOND].LEGACY = 'BSM'
		)
		OR
		(
			[MAIN].LEGACY = 'BRIS'
			AND
			[SECOND].LEGACY = 'BSM'
			AND
			[MAIN].NAMANASABAH = [SECOND].NAMANASABAH
		)
		OR
		(
			[MAIN].LEGACY = [SECOND].LEGACY
			AND
			[MAIN].NOMORCIF = [SECOND].NOMORCIF
		)
	)

LEFT JOIN
	(
		SELECT
			LEGACY_LAMA
			,NOLOAN_LAMA
		FROM
		[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
		GROUP BY
			LEGACY_LAMA
			,NOLOAN_LAMA
	) [NOLOAN_LAMA] ON [MAIN].NOLOAN = [NOLOAN_LAMA].NOLOAN_LAMA AND [MAIN].LEGACY = [NOLOAN_LAMA].LEGACY_LAMA

LEFT JOIN
	(
		SELECT
			LEGACY_BARU
			,NOLOAN_BARU
		FROM
		[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
		GROUP BY
			LEGACY_BARU
			,NOLOAN_BARU
	) [NOLOAN_BARU] ON [SECOND].NOLOAN = [NOLOAN_BARU].NOLOAN_BARU AND [SECOND].LEGACY = [NOLOAN_BARU].LEGACY_BARU

WHERE COALESCE([SECOND].NOLOAN, 'X') != 'X'
AND COALESCE([NOLOAN_LAMA].NOLOAN_LAMA, 'X') = 'X'
AND COALESCE([NOLOAN_BARU].NOLOAN_BARU, 'X') = 'X'
AND [MAIN].DIVISI != 'Hasanah Card'

ORDER BY NOLOAN, NOLOAN_BARU;

SELECT * FROM #TEMP_RESULT_01;

SELECT
	[TARGET].[LEGACY]
	,[TARGET].[NOLOAN]
	,[TARGET].[NOMORCIF]
	,[TARGET].[KODE_OUTLET]
	,[TARGET].[NAMANASABAH]
	,[TARGET].[LEGACY_CURRENT]
	,[TARGET].[NOLOAN_BARU]
	,[TARGET].[NOMORCIF_BARU]
	,[TARGET].[KODE_OUTLET]
	,[TARGET].[NAMANASABAH_BARU]
	,'ONBS' [FLAG_DATA]
	,[TGL_MUTASI] [TGL_EFEKTIF]
	,'BUKA TUTUP (SUSPECT RCG)' [KETERANGAN]
FROM #TEMP_RESULT_01 [TARGET]
OUTER APPLY (
	SELECT
		COUNT(1) AS [ACCT]
	FROM #TEMP_RESULT_01
	WHERE [TARGET].[LEGACY] = [LEGACY]
	AND [TARGET].[NOLOAN] = [NOLOAN]
) [TUTUP]
OUTER APPLY (
	SELECT
		COUNT(1) AS [ACCT]
	FROM #TEMP_RESULT_01
	WHERE [TARGET].[LEGACY_CURRENT] = [LEGACY_CURRENT]
	AND [TARGET].[NOLOAN_BARU] = [NOLOAN_BARU]
) [BUKA]
WHERE [BUKA].[ACCT] = 1
AND [TUTUP].[ACCT] = 1;