SELECT
	KTP
FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL]
WHERE KTP NOT IN (SELECT KTP FROM [MAPPING].[FILTER.ANOMALI.INVALID_KTP])
AND
	(
		TRY_CAST(LEFT(RIGHT(LEFT([dbo].[fx_common_remove_symbols](KTP), 12), 6), 2) AS INTEGER) > 71
		OR TRY_CAST(LEFT(RIGHT(LEFT([dbo].[fx_common_remove_symbols](KTP), 12), 4), 2) AS INTEGER) > 12
	)
-- AND NPWP NOT LIKE ('%000')
GROUP BY
	KTP