INSERT INTO [mapping].[PORTOFOLIO.ONBS.REMOVE_LOAN]
SELECT
	[IFOIS].[NOLOAN]
	,[IFOIS].[NOMORCIF]
	,[IFOIS].[FICMISDATE]
	,NULL
	,'TAKE OUT FROM QC'
	,'RCG'
FROM [series].[IFOIS.LOAN_DAILY.2023-06-30] [IFOIS]
LEFT JOIN [series].[FOG.LOAN_DAILY.2023-06-30] [FOG]
	ON [IFOIS].[NOLOAN] = [FOG].[NOLOAN]
LEFT JOIN [mapping].[PORTOFOLIO.ONBS.REMOVE_LOAN] [MAPPING]
	ON [IFOIS].[NOLOAN] = [MAPPING].[NOLOAN]
WHERE [FOG].[NOLOAN] IS NULL
AND [MAPPING].[NOLOAN] IS NULL;