-- SELECT * INTO [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL_BACKUP] FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL];
-- DROP TABLE [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL_BACKUP];

UPDATE [TARGET]
SET
	[SUPERCIF] = [SOURCE].[SUPERCIF]
FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [TARGET]
LEFT JOIN
	(
		SELECT
			[NOMORCIF] [NOMORCIF]
			,[SUPERCIF_NO] [SUPERCIF]
		FROM [series].[DDM.MAPPING_SUPERCIF.2023-07-31]
		WHERE [NOMORCIF] != [SUPERCIF_NO]
		GROUP BY
			[NOMORCIF]
			,[SUPERCIF_NO]
	) [SOURCE]
	ON [TARGET].[SUPERCIF] = [SOURCE].[NOMORCIF]
WHERE [SOURCE].[SUPERCIF] IS NOT NULL;

UPDATE [TARGET]
SET
	[SUPERCIF] = [SOURCE].[SUPERCIF]
FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [TARGET]
LEFT JOIN
	(
		SELECT
			[NOMORCIF] [NOMORCIF]
			,[SUPERCIF_NO] [SUPERCIF]
		FROM [series].[DDM.MAPPING_SUPERCIF.2023-07-31]
		WHERE [NOMORCIF] != [SUPERCIF_NO]
		GROUP BY
			[NOMORCIF]
			,[SUPERCIF_NO]
	) [SOURCE]
	ON [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
WHERE [SOURCE].[SUPERCIF] IS NOT NULL;

WITH CTE AS
(
	SELECT
		[TARGET].[NOMORCIF]
		,[TARGET].[SUPERCIF]
		,[SOURCE].[SUPERCIF] [SUPERCIF_UPDATE]
	FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [TARGET]
	LEFT JOIN
		(
			SELECT
				[NOMORCIF]
				,[SUPERCIF]
			FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL]
			GROUP BY
				[NOMORCIF]
				,[SUPERCIF]
		)[SOURCE]
		ON [TARGET].[SUPERCIF] = [SOURCE].[NOMORCIF]
	WHERE [TARGET].[SUPERCIF] != [SOURCE].[SUPERCIF]
) UPDATE CTE SET [SUPERCIF] = [SUPERCIF_UPDATE];