-- SELECT
-- 	[SOURCE].[INDEX] [UPDATE_INDEX]
-- 	,[TARGET].[INDEX]
-- 	,[TARGET].[LEGACY]
-- 	,[TARGET].[NOMORCIF]
-- 	,[TARGET].[SUPERCIF]
-- 	,[TARGET].[NAMANASABAH]
-- 	,COALESCE(CASE WHEN [TARGET].[NPWP] NOT IN (SELECT [NPWP] FROM [mapping].[FILTER.ANOMALI.INVALID_NPWP]) THEN [TARGET].[NPWP] END, CASE WHEN [SOURCE].[NPWP] NOT IN (SELECT [NPWP] FROM [mapping].[FILTER.ANOMALI.INVALID_NPWP]) THEN [SOURCE].[NPWP] END, [TARGET].[NPWP], [SOURCE].[NPWP]) [NPWP]
-- 	,COALESCE(CASE WHEN [TARGET].[KTP] NOT IN (SELECT [KTP] FROM [mapping].[FILTER.ANOMALI.INVALID_KTP]) THEN [TARGET].[KTP] END, CASE WHEN [SOURCE].[KTP] NOT IN (SELECT [KTP] FROM [mapping].[FILTER.ANOMALI.INVALID_KTP]) THEN [SOURCE].[KTP] END, [TARGET].[KTP], [SOURCE].[KTP]) [KTP]
-- 	,COALESCE([TARGET].[NO_HP], [SOURCE].[NO_HP]) [NO_HP]
-- 	,COALESCE([TARGET].[NO_TELP], [SOURCE].[NO_TELP]) [NO_TELP]
-- 	,COALESCE([TARGET].[NO_KANTOR], [SOURCE].[NO_KANTOR]) [NO_KANTOR]
-- 	,COALESCE([TARGET].[ALT_CONTACT_1], [SOURCE].[ALT_CONTACT_1]) [ALT_CONTACT_1]
-- 	,COALESCE([TARGET].[ALT_CONTACT_2], [SOURCE].[ALT_CONTACT_2]) [ALT_CONTACT_2]
-- 	,COALESCE([TARGET].[ALT_CONTACT_3], [SOURCE].[ALT_CONTACT_3]) [ALT_CONTACT_3]
-- 	,COALESCE([TARGET].[TANGGAL_LAHIR], [SOURCE].[TANGGAL_LAHIR]) [TANGGAL_LAHIR]
-- 	,COALESCE([TARGET].[PEKERJAAN], [SOURCE].[PEKERJAAN]) [PEKERJAAN]
-- 	,COALESCE([TARGET].[STATUSPEKERJAAN], [SOURCE].[STATUSPEKERJAAN]) [STATUSPEKERJAAN]
-- 	,COALESCE([TARGET].[ALAMAT], [SOURCE].[ALAMAT]) [ALAMAT]
-- 	,COALESCE([TARGET].[GENDER], [SOURCE].[GENDER]) [GENDER]
-- 	,COALESCE([TARGET].[TANGGAL_AWAL_MENUNGGAK], [SOURCE].[TANGGAL_AWAL_MENUNGGAK]) [TANGGAL_AWAL_MENUNGGAK]
-- 	,COALESCE([TARGET].[NAMAPERUSAHAANNASABAH], [SOURCE].[NAMAPERUSAHAANNASABAH]) [NAMAPERUSAHAANNASABAH]
-- 	,COALESCE([TARGET].[JENISNASABAH], [SOURCE].[JENISNASABAH]) [JENISNASABAH]
-- 	,COALESCE([TARGET].[ALAMATPERUSAHAANNASABAH], [SOURCE].[ALAMATPERUSAHAANNASABAH]) [ALAMATPERUSAHAANNASABAH]
-- 	,COALESCE([TARGET].[BIDANGUSAHAPERUSAHAAN], [SOURCE].[BIDANGUSAHAPERUSAHAAN]) [BIDANGUSAHAPERUSAHAAN]
-- 	,COALESCE([TARGET].[TEMPATLAHIR], [SOURCE].[TEMPATLAHIR]) [TEMPATLAHIR]
-- 	,COALESCE([TARGET].[NAMAIBUKANDUNG], [SOURCE].[NAMAIBUKANDUNG]) [NAMAIBUKANDUNG]
-- 	,COALESCE([TARGET].[KODEPOS], [SOURCE].[KODEPOS]) [KODEPOS]
UPDATE [TARGET]
SET
	[NPWP] = COALESCE(CASE WHEN [TARGET].[NPWP] NOT IN (SELECT [NPWP] FROM [mapping].[FILTER.ANOMALI.INVALID_NPWP]) THEN [TARGET].[NPWP] END, CASE WHEN [SOURCE].[NPWP] NOT IN (SELECT [NPWP] FROM [mapping].[FILTER.ANOMALI.INVALID_NPWP]) THEN [SOURCE].[NPWP] END, [TARGET].[NPWP], [SOURCE].[NPWP])
	,[KTP] = COALESCE(CASE WHEN [TARGET].[KTP] NOT IN (SELECT [KTP] FROM [mapping].[FILTER.ANOMALI.INVALID_KTP]) THEN [TARGET].[KTP] END, CASE WHEN [SOURCE].[KTP] NOT IN (SELECT [KTP] FROM [mapping].[FILTER.ANOMALI.INVALID_KTP]) THEN [SOURCE].[KTP] END, [TARGET].[KTP], [SOURCE].[KTP])
	,[NO_HP] = COALESCE([TARGET].[NO_HP], [SOURCE].[NO_HP])
	,[NO_TELP] = COALESCE([TARGET].[NO_TELP], [SOURCE].[NO_TELP])
	,[NO_KANTOR] = COALESCE([TARGET].[NO_KANTOR], [SOURCE].[NO_KANTOR])
	,[ALT_CONTACT_1] = COALESCE([TARGET].[ALT_CONTACT_1], [SOURCE].[ALT_CONTACT_1])
	,[ALT_CONTACT_2] = COALESCE([TARGET].[ALT_CONTACT_2], [SOURCE].[ALT_CONTACT_2])
	,[ALT_CONTACT_3] = COALESCE([TARGET].[ALT_CONTACT_3], [SOURCE].[ALT_CONTACT_3])
	,[TANGGAL_LAHIR] = COALESCE([TARGET].[TANGGAL_LAHIR], [SOURCE].[TANGGAL_LAHIR])
	,[PEKERJAAN] = COALESCE([TARGET].[PEKERJAAN], [SOURCE].[PEKERJAAN])
	,[STATUSPEKERJAAN] = COALESCE([TARGET].[STATUSPEKERJAAN], [SOURCE].[STATUSPEKERJAAN])
	,[ALAMAT] = COALESCE([TARGET].[ALAMAT], [SOURCE].[ALAMAT])
	,[GENDER] = COALESCE([TARGET].[GENDER], [SOURCE].[GENDER])
	,[TANGGAL_AWAL_MENUNGGAK] = COALESCE([TARGET].[TANGGAL_AWAL_MENUNGGAK], [SOURCE].[TANGGAL_AWAL_MENUNGGAK])
	,[NAMAPERUSAHAANNASABAH] = COALESCE([TARGET].[NAMAPERUSAHAANNASABAH], [SOURCE].[NAMAPERUSAHAANNASABAH])
	,[JENISNASABAH] = COALESCE([TARGET].[JENISNASABAH], [SOURCE].[JENISNASABAH])
	,[ALAMATPERUSAHAANNASABAH] = COALESCE([TARGET].[ALAMATPERUSAHAANNASABAH], [SOURCE].[ALAMATPERUSAHAANNASABAH])
	,[BIDANGUSAHAPERUSAHAAN] = COALESCE([TARGET].[BIDANGUSAHAPERUSAHAAN], [SOURCE].[BIDANGUSAHAPERUSAHAAN])
	,[TEMPATLAHIR] = COALESCE([TARGET].[TEMPATLAHIR], [SOURCE].[TEMPATLAHIR])
	,[NAMAIBUKANDUNG] = COALESCE([TARGET].[NAMAIBUKANDUNG], [SOURCE].[NAMAIBUKANDUNG])
	,[KODEPOS] = COALESCE([TARGET].[KODEPOS], [SOURCE].[KODEPOS])
FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [TARGET]
LEFT JOIN [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [SOURCE]
	ON [TARGET].[SUPERCIF] = [SOURCE].[SUPERCIF]
	AND [TARGET].[INDEX] != [SOURCE].[INDEX]
WHERE [TARGET].[SUPERCIF] IN (
		SELECT
			[SUPERCIF]
		FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL]
		WHERE LEN([SUPERCIF]) = 8
		GROUP BY
			[SUPERCIF]
		HAVING COUNT(1) > 1
	)
AND [SOURCE].[INDEX] IS NOT NULL
ORDER BY
	[TARGET].[SUPERCIF]
	,[TARGET].[NOMORCIF]
	,[TARGET].[NAMANASABAH]
