DECLARE @POINTER INT = 1
WHILE @POINTER <= 100
BEGIN
	UPDATE [mapping].[PORTOFOLIO_ONBS.MAPPING.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN_CURRENT] SET
		LEGACY_AWAL = COALESCE (
			[AWAL].LEGACY_LAMA,
			[CURRENT].LEGACY_AWAL,
			[CURRENT].LEGACY_CURRENT
		),
		NOLOAN_AWAL = COALESCE (
			[AWAL].NOLOAN_LAMA,
			[CURRENT].NOLOAN_AWAL,
			[CURRENT].NOLOAN_CURRENT
		),
		NOCIF_AWAL= COALESCE (
			[AWAL].NOCIF_LAMA,
			[CURRENT].NOCIF_AWAL,
			[CURRENT].NOCIF_CURRENT
		),
		KODECABANG_AWAL = COALESCE (
			[AWAL].KODECABANG_LAMA,
			[CURRENT].KODECABANG_AWAL,
			[CURRENT].KODECABANG_CURRENT
		),
		NAMANASABAH_AWAL = COALESCE (
			[AWAL].NAMANASABAH_LAMA,
			[CURRENT].NAMANASABAH_AWAL,
			[CURRENT].NAMANASABAH_CURRENT
		),

		LEGACY_BEFORE = COALESCE (
			[BEFORE].LEGACY_LAMA,
			[CURRENT].LEGACY_BEFORE,
			[CURRENT].LEGACY_CURRENT
		),
		NOLOAN_BEFORE = COALESCE (
			[BEFORE].NOLOAN_LAMA,
			[CURRENT].NOLOAN_BEFORE,
			[CURRENT].NOLOAN_CURRENT
		),
		NOCIF_BEFORE= COALESCE (
			[BEFORE].NOCIF_LAMA,
			[CURRENT].NOCIF_BEFORE,
			[CURRENT].NOCIF_CURRENT
		),
		KODECABANG_BEFORE = COALESCE (
			[BEFORE].KODECABANG_LAMA,
			[CURRENT].KODECABANG_BEFORE,
			[CURRENT].KODECABANG_CURRENT
		),
		NAMANASABAH_BEFORE = COALESCE (
			[BEFORE].NAMANASABAH_LAMA,
			[CURRENT].NAMANASABAH_BEFORE,
			[CURRENT].NAMANASABAH_CURRENT
		),

		LEGACY_AKHIR = COALESCE (
			[AKHIR].LEGACY_BARU,
			[CURRENT].LEGACY_AKHIR
		),
		NOLOAN_AKHIR = COALESCE (
			[AKHIR].NOLOAN_BARU,
			[CURRENT].NOLOAN_AKHIR
		),
		NOCIF_AKHIR = COALESCE (
			[AKHIR].NOCIF_BARU,
			[CURRENT].NOCIF_AKHIR
		),
		KODECABANG_AKHIR = COALESCE (
			[AKHIR].KODECABANG_BARU,
			[CURRENT].KODECABANG_AKHIR
		),
		NAMANASABAH_AKHIR = COALESCE (
			[AKHIR].NAMANASABAH_BARU,
			[CURRENT].NAMANASABAH_AKHIR
		),
		FLAG_DATA_AKHIR = COALESCE (
			[AKHIR].FLAG_DATA,
			[CURRENT].FLAG_DATA
		),
		TGL_EFEKTIF_AKHIR = COALESCE (
			[AKHIR].TGL_EFEKTIF,
			[CURRENT].TGL_EFEKTIF
		),
		KETERANGAN_AKHIR = COALESCE (
			[AKHIR].KETERANGAN,
			[CURRENT].KETERANGAN
		)
	FROM
		[mapping].[PORTOFOLIO_ONBS.MAPPING.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN_CURRENT] [CURRENT]
	LEFT JOIN [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [AKHIR] ON [CURRENT].LEGACY_AKHIR = [AKHIR].LEGACY_LAMA
	AND [CURRENT].NOLOAN_AKHIR = [AKHIR].NOLOAN_LAMA
	AND [AKHIR].KETERANGAN != 'INVALID'
	LEFT JOIN [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [AWAL] ON [CURRENT].LEGACY_AWAL = [AWAL].LEGACY_BARU
	AND [CURRENT].NOLOAN_AWAL = [AWAL].NOLOAN_BARU
	AND [AWAL].KETERANGAN != 'INVALID'
	LEFT JOIN [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [BEFORE] ON [CURRENT].LEGACY_CURRENT = [BEFORE].LEGACY_BARU
	AND [CURRENT].NOLOAN_CURRENT = [BEFORE].NOLOAN_BARU
	AND [BEFORE].KETERANGAN != 'INVALID'
	SET @POINTER = @POINTER+1
END