UPDATE [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
SET
	[KETERANGAN] = 'INVALID'
FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [TARGET]
LEFT JOIN [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.LOAN_DETAIL] [MAPPING]
	ON [TARGET].[NOLOAN_LAMA] = [MAPPING].[NOLOAN]
	AND [TARGET].[NOCIF_LAMA] = [MAPPING].[NOMORCIF]
WHERE [MAPPING].[LOANTYPE] IN ('QRU0006')
AND [MAPPING].[NOLOAN] IS NOT NULL;

TRUNCATE TABLE [mapping].[PORTOFOLIO_ONBS.MAPPING.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN_CURRENT];

INSERT INTO [mapping].[PORTOFOLIO_ONBS.MAPPING.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN_CURRENT]
SELECT
	[COMPILE].LEGACY_LAMA
	,[COMPILE].NOLOAN_LAMA
	,[COMPILE].NOCIF_LAMA
	,[COMPILE].KODECABANG_LAMA
	,[COMPILE].NAMANASABAH_LAMA
	,[COMPILE].LEGACY_LAMA
	,[COMPILE].NOLOAN_LAMA
	,[COMPILE].NOCIF_LAMA
	,[COMPILE].KODECABANG_LAMA
	,[COMPILE].NAMANASABAH_LAMA
	,[COMPILE].LEGACY_LAMA
	,[COMPILE].NOLOAN_LAMA
	,[COMPILE].NOCIF_LAMA
	,[COMPILE].KODECABANG_LAMA
	,[COMPILE].NAMANASABAH_LAMA
	,[COMPILE].LEGACY_BARU
	,[COMPILE].NOLOAN_BARU
	,[COMPILE].NOCIF_BARU
	,[COMPILE].KODECABANG_BARU
	,[COMPILE].NAMANASABAH_BARU
	,[COMPILE].LEGACY_BARU
	,[COMPILE].NOLOAN_BARU
	,[COMPILE].NOCIF_BARU
	,[COMPILE].KODECABANG_BARU
	,[COMPILE].NAMANASABAH_BARU
	,[COMPILE].FLAG_DATA
	,[COMPILE].FLAG_DATA
	,[COMPILE].TGL_EFEKTIF
	,[COMPILE].TGL_EFEKTIF
	,[COMPILE].KETERANGAN
	,[COMPILE].KETERANGAN
FROM
[mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN] [COMPILE]

WHERE [COMPILE].KETERANGAN != 'INVALID';