DECLARE @NOMORCIF varchar(max), @NAMANASABAH varchar(max);

DECLARE load_cursor CURSOR FOR
		SELECT SUPERCIF, NAMANASABAH FROM 
	(
		SELECT TOP 50000
			[SUPERCIF],
			[NAMANASABAH]
		FROM [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL]
		WHERE
			NOT ([SUPERCIF] IN (SELECT [NOMORCIF] FROM [AI].[FEED.NAME_LIST])
				AND [NAMANASABAH] IN (SELECT [NAMANASABAH] FROM [AI].[FEED.NAME_LIST])
			)
		GROUP BY
			[SUPERCIF],
			[NAMANASABAH]
	) [TEMP];

OPEN load_cursor
	FETCH NEXT FROM load_cursor INTO @NOMORCIF, @NAMANASABAH;
	
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		INSERT INTO [AI].[FEED.NAME_LIST](NOMORCIF, FULL_NAME, WORDING, FLAG) SELECT @NOMORCIF [NOMORCIF], @NAMANASABAH [FULL_NAME], [A].[WORD] [WORDING], CASE WHEN LEN(COALESCE([A].[WORD], '')) <= 2 THEN 'INVALID' END [FLAG] FROM [dbo].[fx_common_stringSplit](@NAMANASABAH, ' ') [A]
		FETCH NEXT FROM load_cursor INTO @NOMORCIF, @NAMANASABAH;
	END
	
CLOSE load_cursor;
DEALLOCATE load_cursor;