TRUNCATE TABLE [AI].[FEED.LOAN_LIST];

DECLARE @SQL_QUERY VARCHAR(max), @TGL_DATA DATE = '2023-03-01', @POINTER INT = 1;

WHILE @POINTER <= 1
BEGIN
	IF @TGL_DATA != EOMONTH(@TGL_DATA)
	BEGIN
		DELETE FROM [AI].[FEED.LOAN_LIST] WHERE TGL_DATA = @TGL_DATA;

		SET @SQL_QUERY = CONCAT(
			'INSERT INTO [AI].[FEED.LOAN_LIST]
			SELECT
				[MAX].[TGL_DATA]
				,[DAILY].[NOLOAN]
				,[DAILY].[KODECABANG]
				,[DAILY].[DIVISI]
				,[DAILY].[PRODUK]
				,[DAILY].[PRODUK_DETAIL]
				,[DAILY].[LOANTYPE]
				,[DAILY].[JENISPIUTANGPEMBIAYAAN]
				,[DAILY].[CYCLE]
				,CONCAT(
					[M_6].[KOL_SUPERCIF], '' - '',
					[M_5].[KOL_SUPERCIF], '' - '',
					[M_4].[KOL_SUPERCIF], '' - '',
					[M_3].[KOL_SUPERCIF], '' - '',
					[M_2].[KOL_SUPERCIF], '' - '',
					[M_1].[KOL_SUPERCIF]
				) [AGING]
				,[DAILY].[KOL_LOAN] [KOL]
				,COALESCE([FINAL].[KOL_LOAN], ''Run Off'') [KOL_FINAL]
				,COALESCE([DAILY].[OS_POKOK_PSAK], 0.00) [OS_POKOK_PSAK]
				,COALESCE([FINAL].[OS_POKOK_PSAK], 0.00) [OS_POKOK_PSAK_FINAL]
				,NULL [FLAG]
			FROM [series].[RCG.LOAN_DAILY.', @TGL_DATA, '] [DAILY]
			OUTER APPLY (
				SELECT
					MAX(TGL_DATA) [TGL_DATA]
				FROM [series].[RCG.LOAN_DAILY.', @TGL_DATA, ']
			) [MAX]
			LEFT JOIN [series].[RCG.LOAN_DAILY.', EOMONTH(@TGL_DATA), ' (FINAL)] [FINAL]
				ON [DAILY].[NOLOAN] = [FINAL].[NOLOAN]
			OUTER APPLY (
				SELECT
					COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]), MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
				FROM (
					SELECT
						CASE WHEN [NOLOAN] IN (
							SELECT
								[NOLOAN_LAMA]
							FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
							WHERE [NOLOAN_BARU] = [DAILY].[NOLOAN]
							AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
						) OR [NOLOAN] = [DAILY].[NOLOAN] THEN [KOL_SUPERCIF] ELSE NULL END [BY_LOAN]
						,CASE WHEN [NOMORCIF] = [DAILY].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
						,[KOL_SUPERCIF] [BY_SUPERCIF]
					FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -1, @TGL_DATA)), ' (FINAL)]
					WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
						AND [DAILY].[DIVISI] = [DIVISI]
				) [SUB]
			) [M_1]
			OUTER APPLY (
				SELECT
					COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]), MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
				FROM (
					SELECT
						CASE WHEN [NOLOAN] IN (
							SELECT
								[NOLOAN_LAMA]
							FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
							WHERE [NOLOAN_BARU] = [DAILY].[NOLOAN]
							AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
						) OR [NOLOAN] = [DAILY].[NOLOAN] THEN [KOL_SUPERCIF] ELSE NULL END [BY_LOAN]
						,CASE WHEN [NOMORCIF] = [DAILY].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
						,[KOL_SUPERCIF] [BY_SUPERCIF]
					FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -2, @TGL_DATA)), ' (FINAL)]
					WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
						AND [DAILY].[DIVISI] = [DIVISI]
				) [SUB]
			) [M_2]
			OUTER APPLY (
				SELECT
					COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]), MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
				FROM (
					SELECT
						CASE WHEN [NOLOAN] IN (
							SELECT
								[NOLOAN_LAMA]
							FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
							WHERE [NOLOAN_BARU] = [DAILY].[NOLOAN]
							AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
						) OR [NOLOAN] = [DAILY].[NOLOAN] THEN [KOL_SUPERCIF] ELSE NULL END [BY_LOAN]
						,CASE WHEN [NOMORCIF] = [DAILY].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
						,[KOL_SUPERCIF] [BY_SUPERCIF]
					FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -3, @TGL_DATA)), ' (FINAL)]
					WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
						AND [DAILY].[DIVISI] = [DIVISI]
				) [SUB]
			) [M_3]
			OUTER APPLY (
				SELECT
					COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]), MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
				FROM (
					SELECT
						CASE WHEN [NOLOAN] IN (
							SELECT
								[NOLOAN_LAMA]
							FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
							WHERE [NOLOAN_BARU] = [DAILY].[NOLOAN]
							AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
						) OR [NOLOAN] = [DAILY].[NOLOAN] THEN [KOL_SUPERCIF] ELSE NULL END [BY_LOAN]
						,CASE WHEN [NOMORCIF] = [DAILY].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
						,[KOL_SUPERCIF] [BY_SUPERCIF]
					FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -4, @TGL_DATA)), ' (FINAL)]
					WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
						AND [DAILY].[DIVISI] = [DIVISI]
				) [SUB]
			) [M_4]
			OUTER APPLY (
				SELECT
					COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]), MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
				FROM (
					SELECT
						CASE WHEN [NOLOAN] IN (
							SELECT
								[NOLOAN_LAMA]
							FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
							WHERE [NOLOAN_BARU] = [DAILY].[NOLOAN]
							AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
						) OR [NOLOAN] = [DAILY].[NOLOAN] THEN [KOL_SUPERCIF] ELSE NULL END [BY_LOAN]
						,CASE WHEN [NOMORCIF] = [DAILY].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
						,[KOL_SUPERCIF] [BY_SUPERCIF]
					FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -5, @TGL_DATA)), ' (FINAL)]
					WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
						AND [DAILY].[DIVISI] = [DIVISI]
				) [SUB]
			) [M_5]
			OUTER APPLY (
				SELECT
					COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]), MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
				FROM (
					SELECT
						CASE WHEN [NOLOAN] IN (
							SELECT
								[NOLOAN_LAMA]
							FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
							WHERE [NOLOAN_BARU] = [DAILY].[NOLOAN]
							AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
						) OR [NOLOAN] = [DAILY].[NOLOAN] THEN [KOL_SUPERCIF] ELSE NULL END [BY_LOAN]
						,CASE WHEN [NOMORCIF] = [DAILY].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
						,[KOL_SUPERCIF] [BY_SUPERCIF]
					FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -6, @TGL_DATA)), ' (FINAL)]
					WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
						AND [DAILY].[DIVISI] = [DIVISI]
				) [SUB]
			) [M_6]
-- 			OUTER APPLY (
-- 				SELECT
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END [KOL_LOAN]
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END [KOL_CIF]
-- 					,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
-- 				FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -1, @TGL_DATA)), ' (FINAL)]
-- 				WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
-- 					AND [DAILY].[DIVISI] = [DIVISI]
-- 				GROUP BY
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END
-- 			) [M_1]
-- 			OUTER APPLY (
-- 				SELECT
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END [KOL_LOAN]
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END [KOL_CIF]
-- 					,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
-- 				FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -2, @TGL_DATA)), ' (FINAL)]
-- 				WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
-- 					AND [DAILY].[DIVISI] = [DIVISI]
-- 				GROUP BY
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END
-- 			) [M_2]
-- 			OUTER APPLY (
-- 				SELECT
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END [KOL_LOAN]
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END [KOL_CIF]
-- 					,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
-- 				FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -3, @TGL_DATA)), ' (FINAL)]
-- 				WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
-- 					AND [DAILY].[DIVISI] = [DIVISI]
-- 				GROUP BY
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END
-- 			) [M_3]
-- 			OUTER APPLY (
-- 				SELECT
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END [KOL_LOAN]
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END [KOL_CIF]
-- 					,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
-- 				FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -4, @TGL_DATA)), ' (FINAL)]
-- 				WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
-- 					AND [DAILY].[DIVISI] = [DIVISI]
-- 				GROUP BY
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END
-- 			) [M_4]
-- 			OUTER APPLY (
-- 				SELECT
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END [KOL_LOAN]
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END [KOL_CIF]
-- 					,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
-- 				FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -5, @TGL_DATA)), ' (FINAL)]
-- 				WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
-- 					AND [DAILY].[DIVISI] = [DIVISI]
-- 				GROUP BY
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END
-- 			) [M_5]
-- 			OUTER APPLY (
-- 				SELECT
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END [KOL_LOAN]
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END [KOL_CIF]
-- 					,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
-- 				FROM [series].[RCG.LOAN_DAILY.', EOMONTH(DATEADD(MONTH, -6, @TGL_DATA)), ' (FINAL)]
-- 				WHERE [DAILY].[SUPERCIF] = [SUPERCIF]
-- 					AND [DAILY].[DIVISI] = [DIVISI]
-- 				GROUP BY
-- 					CASE WHEN [DAILY].[NOLOAN] = [NOLOAN] THEN [KOL_SUPERCIF] END
-- 					,CASE WHEN [DAILY].[NOMORCIF] = [NOMORCIF] THEN [KOL_SUPERCIF] END
-- 			) [M_6]
-- 			WHERE [DAILY].[DIVISI] NOT IN (''Hasanah Card'');'
		);

		EXEC(@SQL_QUERY);
	END
	PRINT @TGL_DATA;
	SET @POINTER = @POINTER + 1;
	SET @TGL_DATA = DATEADD(DAY, 1, @TGL_DATA);
END