	SELECT
		[TARGET].*
		,[SOURCE].[RANK]
	FROM [AI].[MEMORY.NAME_COUNT] [TARGET]
	LEFT JOIN (
		SELECT
			[ACCT]
			,RANK() OVER (
				ORDER BY
					[ACCT] ASC
			) [RANK]
		FROM (
			SELECT
				[ACCT]
			FROM [AI].[MEMORY.NAME_COUNT]
			WHERE [ACCT] > 1
			GROUP BY
				[ACCT]
		) [SOURCE]
	) [SOURCE]
	 ON [TARGET].[ACCT] = [SOURCE].[ACCT]
	WHERE [TARGET].[ACCT] > 1
	AND [SOURCE].[RANK] <= 5
	ORDER BY
		[TARGET].[ACCT] DESC