TRUNCATE TABLE [AI].[MEMORY.PREDICT_KOL];

INSERT INTO [AI].[MEMORY.PREDICT_KOL] (
	[TGL],
	[KOL],
  [AGING],
  [DIVISI],
  [PRODUK],
  [PRODUK_DETAIL],
  [LOANTYPE],
  [JENISPIUTANGPEMBIAYAAN],
  [CYCLE],
  [KOL_FINAL],
  [OS_POKOK_PSAK],
  [OS_POKOK_PSAK_FINAL],
  [ACCT],
  [FLAG]
) SELECT
	RIGHT([TGL_DATA], 2) [TGL],
	[KOL],
  [AGING],
  [DIVISI],
  [PRODUK],
  [PRODUK_DETAIL],
  [LOANTYPE],
  [JENISPIUTANGPEMBIAYAAN],
  [CYCLE],
  [KOL_FINAL],
  SUM([OS_POKOK_PSAK]),
  SUM([OS_POKOK_PSAK_FINAL]),
  COUNT(1) [ACCT],
  NULL [FLAG]
FROM [AI].[FEED.LOAN_LIST]
WHERE COALESCE([FLAG], 'Valid') NOT IN ('Invalid')
GROUP BY
	RIGHT([TGL_DATA], 2),
	[KOL],
  [AGING],
  [DIVISI],
  [PRODUK],
  [PRODUK_DETAIL],
  [LOANTYPE],
  [JENISPIUTANGPEMBIAYAAN],
  [CYCLE],
  [KOL_FINAL]