TRUNCATE TABLE [AI].[MEMORY.NAME_COUNT];
INSERT INTO [AI].[MEMORY.NAME_COUNT]
SELECT
	[WORDING]
	,COUNT(1)
	,NULL
FROM [AI].[FEED.NAME_LIST]
WHERE COALESCE([FLAG], 'VALID') NOT IN ('INVALID')
GROUP BY
	[WORDING];