CREATE TABLE #TEMP (
		TGL_LM DATE
		,TGL_LD DATE
		,TGL_DATA DATE
		,NOLOAN VARCHAR(255)
		,NOMORCIF VARCHAR(255)
		,SUPERCIF VARCHAR(255)
		,NAMANASABAH VARCHAR(255)
		,KODECABANG VARCHAR(255)
		,NAMACABANG VARCHAR(255)
		,AREA VARCHAR(255)
		,REGION VARCHAR(255)
		,DIVISI VARCHAR(255)
		,PRODUK VARCHAR(255)
		,PRODUK_DETAIL VARCHAR(255)
		,JENISPIUTANGPEMBIAYAAN VARCHAR(255)
		,CYCLE VARCHAR(255)
		,KOL_LOAN_LM VARCHAR(255)
		,KOL_CIF_LM VARCHAR(255)
		,KOL_SUPERCIF_LM VARCHAR(255)
		,KOL_LOAN_LD VARCHAR(255)
		,KOL_CIF_LD VARCHAR(255)
		,KOL_SUPERCIF_LD VARCHAR(255)
		,KOL_LOAN VARCHAR(255)
		,KOL_CIF VARCHAR(255)
		,KOL_SUPERCIF VARCHAR(255)
		,PAY_POKOK DECIMAL(20, 2)
		,PAY_MARGIN DECIMAL(20, 2)
		,PAY_BASIL DECIMAL(20, 2)
		,FLAG VARCHAR(255)
		,KETERANGAN VARCHAR(255)
		,REK_PEMBAYARAN VARCHAR(255)
		,ACTION_PLAN VARCHAR(255)
		,PAY_SUBROGASI DECIMAL(20, 2)
	);
	
INSERT INTO #TEMP
SELECT
	TGL_LM
	,TGL_LD
	,TGL_DATA
	,NOLOAN
	,NOMORCIF
	,SUPERCIF
	,NAMANASABAH
	,KODECABANG
	,NAMACABANG
	,AREA
	,REGION
	,DIVISI
	,PRODUK
	,PRODUK_DETAIL
	,JENISPIUTANGPEMBIAYAAN
	,CYCLE
	,KOL_LOAN_LM
	,KOL_CIF_LM
	,KOL_SUPERCIF_LM
	,KOL_LOAN_LD
	,KOL_CIF_LD
	,KOL_SUPERCIF_LD
	,KOL_LOAN
	,KOL_CIF
	,KOL_SUPERCIF
	,PAY_POKOK
	,PAY_MARGIN
	,PAY_BASIL
	,FLAG
	,KETERANGAN
	,REK_PEMBAYARAN
	,ACTION_PLAN
	,PAY_SUBROGASI
FROM [compile].[DAILY_PAYMENT.VERTICAL]
ORDER BY
	[INDEX];
TRUNCATE TABLE [compile].[DAILY_PAYMENT.VERTICAL];
INSERT INTO [compile].[DAILY_PAYMENT.VERTICAL] SELECT * FROM #TEMP;
DROP TABLE #TEMP;