	DECLARE @SIMILAR_NAME VARCHAR(255) = 'PUSPA';
	
	DECLARE load_cursor CURSOR FOR 
	SELECT TOP 10000 [WORD] FROM [AI].[MEMORY.NAME_COUNT]
	WHERE [ACCT] <= 2000
	AND [ACCT] >= 3
	AND COALESCE([FLAG], 'X') NOT IN ('DONE')
	ORDER BY [ACCT] DESC
		,[WORD];
	
	OPEN load_cursor
	FETCH NEXT FROM load_cursor INTO @SIMILAR_NAME
	
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		
		INSERT INTO [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.SUSPECT_SUPERCIF]
		SELECT
			[TARGET].[LEGACY]
			,[TARGET].[NOMORCIF]
			,[TARGET].[NAMANASABAH]
			,[SOURCE].[SUPERCIF]
			,[SOURCE].[NAMANASABAH] AS [NAMANASABAH_SUPERCIF]
			,dbo.fx_common_similarity([TARGET].[NPWP], [SOURCE].[NPWP], 1, 0.9) * 4.00
				+ dbo.fx_common_similarity([TARGET].[KTP], [SOURCE].[KTP], 1, 0.9) * 4.00
				+ CASE WHEN LEFT([TARGET].[NO_HP], LEN([SOURCE].[NO_HP])) = LEFT([SOURCE].[NO_HP], LEN([TARGET].[NO_HP])) THEN 2.00 ELSE 0.00 END
				+ CASE WHEN LEFT([TARGET].[NO_TELP], LEN([SOURCE].[NO_TELP])) = LEFT([SOURCE].[NO_TELP], LEN([TARGET].[NO_TELP])) THEN 2.00 ELSE 0.00 END
				+ CASE WHEN LEFT([TARGET].[NO_KANTOR], LEN([SOURCE].[NO_KANTOR])) = LEFT([SOURCE].[NO_KANTOR], LEN([TARGET].[NO_KANTOR])) THEN 2.00 ELSE 0.00 END
				+ CASE WHEN [TARGET].[TANGGAL_LAHIR] BETWEEN [SOURCE].[TANGGAL_LAHIR_LOW] AND [SOURCE].[TANGGAL_LAHIR_HIGH] THEN 2.00 ELSE 0.00 END
				+ CASE WHEN [TARGET].[TANGGAL_LAHIR] = [SOURCE].[TANGGAL_LAHIR] THEN 2.00 ELSE 0.00 END
			AS [POIN]
		FROM
			(
				SELECT
					[LEGACY]
					,[NOMORCIF]
					,CASE WHEN NULLIF(REPLACE([NAMANASABAH], ' ', ''), '') IS NULL THEN '~~~~~~~~~~~~~~' ELSE [NAMANASABAH] END [NAMANASABAH]
					,COALESCE(NULLIF([NPWP], ''), 'XXXXXXXXXX') [NPWP]
					,COALESCE(NULLIF([KTP], ''), 'XXXXXXXXXX') [KTP]
					,COALESCE(NULLIF([NO_HP], ''), 'POINTER_1') [NO_HP]
					,COALESCE(NULLIF([NO_TELP], ''), 'POINTER_1') [NO_TELP]
					,COALESCE(NULLIF([NO_KANTOR], ''), 'POINTER_1') [NO_KANTOR]
					,COALESCE(NULLIF([TANGGAL_LAHIR], ''), '1900-01-05') [TANGGAL_LAHIR]
					,COALESCE([SUPERCIF], [NOMORCIF]) [SUPERCIF]
				FROM (
					SELECT
						[LEGACY]
						,[NOMORCIF]
						,CASE WHEN NULLIF(REPLACE([NAMANASABAH], ' ', ''), '') IS NULL THEN NULL ELSE [NAMANASABAH] END AS [NAMANASABAH]
						,CASE WHEN NPWP IN (SELECT NPWP FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_NPWP]) THEN NULL ELSE NPWP END AS NPWP
						,CASE WHEN KTP IN (SELECT KTP FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_KTP]) THEN NULL ELSE KTP END AS KTP
						,CASE WHEN NO_HP IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_HP END AS NO_HP
						,CASE WHEN NO_TELP IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_TELP END AS NO_TELP
						,CASE WHEN NO_KANTOR IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_KANTOR END AS NO_KANTOR
						,TRY_CAST([TANGGAL_LAHIR] AS DATE) AS [TANGGAL_LAHIR]
						,[SUPERCIF]
					FROM [PORTOFOLIO.ONBS.CIF_DETAIL]
					WHERE [NOMORCIF] = [SUPERCIF]
					AND
						(
							[NAMANASABAH] LIKE CONCAT('', @SIMILAR_NAME, ' %')
							OR [NAMANASABAH] LIKE CONCAT('% ', @SIMILAR_NAME, '')
							OR [NAMANASABAH] LIKE CONCAT('% ', @SIMILAR_NAME, ' %')
							OR [NAMANASABAH] LIKE CONCAT('', @SIMILAR_NAME, '')
						)
				) [TARGET]
			) [TARGET]
		LEFT JOIN
			(
				SELECT
					[LEGACY]
					,[NOMORCIF]
					,CASE WHEN NULLIF(REPLACE([NAMANASABAH], ' ', ''), '') IS NULL THEN '||||||||||||||||' ELSE [NAMANASABAH] END [NAMANASABAH]
					,COALESCE(NULLIF([NPWP], ''), 'YYYYYYYYYY') [NPWP]
					,COALESCE(NULLIF([KTP], ''), 'YYYYYYYYYY') [KTP]
					,COALESCE(NULLIF([NO_HP], ''), 'POINTER_2') [NO_HP]
					,COALESCE(NULLIF([NO_TELP], ''), 'POINTER_2') [NO_TELP]
					,COALESCE(NULLIF([NO_KANTOR], ''), 'POINTER_2') [NO_KANTOR]
					,COALESCE(NULLIF([TANGGAL_LAHIR], ''), '2049-12-25') [TANGGAL_LAHIR]
					,DATEADD(DAY, -3, COALESCE(NULLIF([TANGGAL_LAHIR], ''), '2049-12-25')) AS [TANGGAL_LAHIR_LOW]
					,DATEADD(DAY, 3, COALESCE(NULLIF([TANGGAL_LAHIR], ''), '2049-12-25')) AS [TANGGAL_LAHIR_HIGH]
					,COALESCE([SUPERCIF], [NOMORCIF]) [SUPERCIF]
				FROM (
					SELECT
						[LEGACY]
						,[NOMORCIF]
						,CASE WHEN NULLIF(REPLACE([NAMANASABAH], ' ', ''), '') IS NULL THEN NULL ELSE [NAMANASABAH] END AS [NAMANASABAH]
						,CASE WHEN NPWP IN (SELECT NPWP FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_NPWP]) THEN NULL ELSE NPWP END AS NPWP
						,CASE WHEN KTP IN (SELECT KTP FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_KTP]) THEN NULL ELSE KTP END AS KTP
						,CASE WHEN NO_HP IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_HP END AS NO_HP
						,CASE WHEN NO_TELP IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_TELP END AS NO_TELP
						,CASE WHEN NO_KANTOR IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_KANTOR END AS NO_KANTOR
						,TRY_CAST([TANGGAL_LAHIR] AS DATE) AS [TANGGAL_LAHIR]
						,[SUPERCIF]
					FROM [PORTOFOLIO.ONBS.CIF_DETAIL]
					WHERE LEGACY = 'BSM'
					AND
						(
							[NAMANASABAH] LIKE CONCAT('', @SIMILAR_NAME, ' %')
							OR [NAMANASABAH] LIKE CONCAT('% ', @SIMILAR_NAME, '')
							OR [NAMANASABAH] LIKE CONCAT('% ', @SIMILAR_NAME, ' %')
							OR [NAMANASABAH] LIKE CONCAT('', @SIMILAR_NAME, '')
						)
				) [SOURCE]
			) [SOURCE]
			
			ON NOT (
				[TARGET].[SUPERCIF] = [SOURCE].[SUPERCIF]
				OR [TARGET].[NOMORCIF] = [SOURCE].[SUPERCIF]
				OR [TARGET].[SUPERCIF] = [SOURCE].[NOMORCIF]
				OR [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
			)
			
			AND (			
				LEN([SOURCE].[NAMANASABAH]) > 10
				AND LEN([TARGET].[NAMANASABAH]) > 10
				AND NEW_BSI_DEV.dbo.fx_common_similarity([TARGET].[NAMANASABAH], [SOURCE].[NAMANASABAH], 0, 0.8) > 0.00 --SIMILARITY
			)

			AND
				(
					dbo.fx_common_similarity([TARGET].[NPWP], [SOURCE].[NPWP], 1, 0.9) * 4.00
					+ dbo.fx_common_similarity([TARGET].[KTP], [SOURCE].[KTP], 1, 0.9) * 4.00
					+ CASE WHEN LEFT([TARGET].[NO_HP], LEN([SOURCE].[NO_HP])) = LEFT([SOURCE].[NO_HP], LEN([TARGET].[NO_HP])) THEN 2.00 ELSE 0.00 END
					+ CASE WHEN LEFT([TARGET].[NO_TELP], LEN([SOURCE].[NO_TELP])) = LEFT([SOURCE].[NO_TELP], LEN([TARGET].[NO_TELP])) THEN 2.00 ELSE 0.00 END
					+ CASE WHEN LEFT([TARGET].[NO_KANTOR], LEN([SOURCE].[NO_KANTOR])) = LEFT([SOURCE].[NO_KANTOR], LEN([TARGET].[NO_KANTOR])) THEN 2.00 ELSE 0.00 END
					+ CASE WHEN [TARGET].[TANGGAL_LAHIR] BETWEEN [SOURCE].[TANGGAL_LAHIR_LOW] AND [SOURCE].[TANGGAL_LAHIR_HIGH] THEN 2.00 ELSE 0.00 END
					+ CASE WHEN [TARGET].[TANGGAL_LAHIR] = [SOURCE].[TANGGAL_LAHIR] THEN 2.00 ELSE 0.00 END	>= 6.00
				)

		WHERE [SOURCE].[NOMORCIF] IS NOT NULL;
		
		DELETE [TARGET] FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.SUSPECT_SUPERCIF] [TARGET]
		LEFT JOIN [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.INVALID_SUPERCIF_MATCH] [SOURCE]
			ON ([TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF] AND [TARGET].[SUPERCIF] = [SOURCE].[SUPERCIF])
			OR ([TARGET].[NOMORCIF] = [SOURCE].[SUPERCIF] AND [TARGET].[SUPERCIF] = [SOURCE].[NOMORCIF])
		WHERE [SOURCE].[SUPERCIF] IS NOT NULL;
		
		WITH CTE AS
		(
			SELECT
				*
				,ROW_NUMBER() OVER (
					PARTITION BY
						[CONCAT]
					ORDER BY
						[CONCAT]
						,[NOMORCIF]
						,[SUPERCIF]
					) [NUM]
			FROM
			(
			SELECT
				*
				,(
					SELECT
						MAX(VAL)
					FROM(VALUES (CONCAT(NOMORCIF, ' - ', SUPERCIF)), (CONCAT(SUPERCIF, ' - ', NOMORCIF))) TEMP(VAL)
				) AS [CONCAT]
			FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.SUSPECT_SUPERCIF]
			) [TEMP]
		) DELETE FROM CTE WHERE [NUM] > 1;
			
		PRINT @SIMILAR_NAME;
		UPDATE [AI].[MEMORY.NAME_COUNT] SET FLAG = 'DONE' WHERE WORD IN (@SIMILAR_NAME);
		FETCH NEXT FROM load_cursor INTO @SIMILAR_NAME;
	END

	CLOSE load_cursor
	DEALLOCATE load_cursor; 	
			
			
	------------------------------------------------------
/*	
SELECT
	[SOURCE].[LEGACY]
	,RIGHT([SOURCE].[NOMORCIF], 15) AS [NOMORCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[POIN]
	,[NOMORCIF].[ACCT] AS [ACCT_NOMORCIF]
	,[SUPERCIF].[ACCT] AS [ACCT_SUPERCIF]
	,[KOL_NOMORCIF].[KOL] AS [KOL_NOMORCIF]
	,[KOL_SUPERCIF].[KOL] AS [KOL_SUPERCIF]
	,[NAME].[ACCT] AS [NAME_FREQUENCY]
INTO #LIST_SUSPECT
FROM [PORTOFOLIO.ONBS.SUSPECT_SUPERCIF] [SOURCE]
OUTER APPLY
	(
		SELECT
			COUNT(1) AS [ACCT]
		FROM [PORTOFOLIO.ONBS.SUSPECT_SUPERCIF]
		WHERE NOMORCIF = [SOURCE].[NOMORCIF]
		GROUP BY NOMORCIF
	) [NOMORCIF]
OUTER APPLY
	(
		SELECT
			COUNT(1) AS [ACCT]
		FROM [PORTOFOLIO.ONBS.SUSPECT_SUPERCIF]
		WHERE SUPERCIF = [SOURCE].[SUPERCIF]
		GROUP BY SUPERCIF
	) [SUPERCIF]
OUTER APPLY
	(
		SELECT
			MAX(KOL) AS [KOL]
		FROM
			(
				SELECT
					[(RCG) KOL_CIF_PECAH] AS KOL
				FROM [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT] [TARGET]
				--FROM [NEW_BSI_STORAGE].[dbo].[BSI.PORTOFOLIO_DAILY.2022-12-27] [TARGET]
				WHERE [SOURCE].[NOMORCIF] = [TARGET].[(SOURCE) NOMORCIF_CURRENT]
				AND [TARGET].[(RCG) KOL_CIF_PECAH] NOT IN ('Lunas', 'Suspect', 'WO')

				UNION

				SELECT
					'WO' AS KOL
				FROM [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_WO.GENERATED.JOIN.WO_CURRENT] [TARGET]
				WHERE [SOURCE].[NOMORCIF] = [TARGET].[CIF]
			) [KOL]
	) [KOL_NOMORCIF]
OUTER APPLY
	(
		SELECT
			MAX(KOL) AS [KOL]
		FROM
			(
				SELECT
					[(RCG) KOL_CIF_PECAH] AS KOL
				FROM [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT] [TARGET]
				--FROM [NEW_BSI_STORAGE].[dbo].[BSI.PORTOFOLIO_DAILY.2022-12-27] [TARGET]
				WHERE [SOURCE].[SUPERCIF] = [TARGET].[(SOURCE) NOMORCIF_CURRENT]
				AND [TARGET].[(RCG) KOL_CIF_PECAH] NOT IN ('Lunas', 'Suspect', 'WO')

				UNION

				SELECT
					'WO' AS KOL
				FROM [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_WO.GENERATED.JOIN.WO_CURRENT] [TARGET]
				WHERE [SOURCE].[SUPERCIF] = [TARGET].[CIF]
			) [KOL]
	) [KOL_SUPERCIF]
OUTER APPLY
(
	SELECT
		COUNT(1) AS ACCT
	FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL]
	WHERE NAMANASABAH = [SOURCE].[NAMANASABAH]
) [NAME]
WHERE
	(
		[SOURCE].[POIN] >= 8.00
	)
	OR
	(
		LEN([SOURCE].[NOMORCIF]) >= 14
	)
	OR
	(
		[SOURCE].[POIN] = 6.00
	)
ORDER BY
	[SOURCE].[POIN] DESC
	,[NOMORCIF].[ACCT] ASC
	,[SUPERCIF].[ACCT] ASC
	,[SOURCE].[NAMANASABAH] ASC
	,[SOURCE].[NOMORCIF] ASC
	,[SOURCE].[SUPERCIF] ASC
*/

/*
CREATE TABLE #LIST_SUSPECT (
	NOMORCIF VARCHAR(100)
	,SUPERCIF VARCHAR(100)
)

INSERT INTO #LIST_SUSPECT
VALUES
	('64725086', '80887175')
	,('60333357', '80999246')
	,('61864733', '81316329')
	,('51540370', '54214381')
	,('53948382', '53949316')
	,('53923547', '53924293')
	,('61846402', '73205577')
	,('50368708', '83077124')
	,('64062424', '84225685')
	,('51538081', '54183483')
	,('51644896', '54119480')
	,('63561633', '83187930')
	--,('', '')
*/

------------------------------------------------------------------------------------------
/*
DECLARE @NOMORCIF_CHECK VARCHAR(100), @SUPERCIF_CHECK VARCHAR(100), @SUPERCIF_SET VARCHAR(100), @sql_query varchar(max)

SELECT TOP 0 * INTO #REKAP_ADJUSTMENT FROM [PORTOFOLIO.ONBS.REKAP_ADJUSTMENT_SUPERCIF]

CREATE TABLE #NOMORCIF
(
	NOMORCIF VARCHAR(100)
)

CREATE TABLE #RESULT_TABLE
	(
		[LEGACY] VARCHAR(255)
		,[NOLOAN] VARCHAR(255)
		,[NOMORCIF] VARCHAR(255)
		,[SUPERCIF] VARCHAR(255)
		,[NAMANASABAH] VARCHAR(255)
		,[KODEOUTLET] VARCHAR(255)
		,[NAMAOUTLET] VARCHAR(255)
		,[AREA] VARCHAR(255)
		,[REGION] VARCHAR(255)
		,[NO_HP] VARCHAR(255)
		,[NO_TELP] VARCHAR(255)
		,[KTP] VARCHAR(255)
		,[NPWP] VARCHAR(255)
		,[TANGGAL_LAHIR] DATE
		,[TANGGAL_AKTIF_AKHIR] DATE
		,[OS_POKOK_PSAK_CURRENT] DECIMAL(20, 2)
		,[KOL] VARCHAR(255)
		,[TGL_WO] DATE
		,[DIVISI] VARCHAR(255)
		,[PRODUK] VARCHAR(255)
	)
	
	CREATE TABLE #TEMP_MAPPING
	(
		[LEGACY] VARCHAR(255)
		,[NOMORCIF] VARCHAR(255)
		,[NAMANASABAH] VARCHAR(255)
		,[NPWP] VARCHAR(255)
		,[KTP] VARCHAR(255)
		,[NO_TELP] VARCHAR(255)
		,[NO_KANTOR] VARCHAR(255)
		,[NO_HP] VARCHAR(255)
		,[ALT_CONTACT_1] VARCHAR(255)
		,[ALT_CONTACT_2] VARCHAR(255)
		,[ALT_CONTACT_3] VARCHAR(255)
		,[TANGGAL_LAHIR] VARCHAR(255)
		,[PEKERJAAN] VARCHAR(255)
		,[ALAMAT] VARCHAR(255)
	)

DECLARE load_cursor CURSOR FOR 
	SELECT
		NOMORCIF
		,SUPERCIF
	FROM #LIST_SUSPECT

OPEN load_cursor
FETCH NEXT FROM load_cursor INTO @NOMORCIF_CHECK, @SUPERCIF_CHECK

WHILE @@FETCH_STATUS = 0 
BEGIN
	TRUNCATE TABLE #REKAP_ADJUSTMENT
	TRUNCATE TABLE #NOMORCIF
	TRUNCATE TABLE #RESULT_TABLE
	TRUNCATE TABLE #TEMP_MAPPING

	------------------------------------------------------------------------------------------------------

	INSERT INTO #NOMORCIF VALUES (@NOMORCIF_CHECK), (@SUPERCIF_CHECK)

	INSERT INTO #RESULT_TABLE
		(
			[LEGACY]
			,[NOLOAN]
			,[NOMORCIF]
			,[KODEOUTLET]
			,[DIVISI]
			,[PRODUK]
		)
	SELECT
		[LEGACY]
		,[NOLOAN]
		,[NOMORCIF]
		,[KODEOUTLET]
		,[DIVISI]
		,[PRODUK]
	FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.LOAN_DETAIL]
	WHERE [NOMORCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
	AND
	NOT (
		LEGACY = 'BSM'
		AND LEN(NOMORCIF) > 8
	)

	SET @sql_query = 'MERGE #RESULT_TABLE [TARGET]
	USING
		(
			SELECT
			[Source Data Current]  AS [LEGACY]
			,[NOLOAN]
			,[CIF] AS [NOMORCIF]
			,[Kode Outlet BSI] AS [KODEOUTLET]
			,[Divisi] AS [DIVISI]
			,[Produk BSI] AS [PRODUK]
			FROM [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_WO.GENERATED.JOIN.WO_CURRENT]
			WHERE [CIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
		) [SOURCE]
		ON [TARGET].[LEGACY] = [SOURCE].[LEGACY]
		AND [TARGET].[NOLOAN] = [SOURCE].[NOLOAN] 
	WHEN NOT MATCHED BY TARGET THEN
	INSERT
		(
			[LEGACY]
			,[NOLOAN]
			,[NOMORCIF]
			,[KODEOUTLET]
			,[DIVISI]
			,[PRODUK]
		)
	VALUES
		(
			[SOURCE].[LEGACY]
			,[SOURCE].[NOLOAN]
			,[SOURCE].[NOMORCIF]
			,[SOURCE].[KODEOUTLET]
			,[SOURCE].[DIVISI]
			,[SOURCE].[PRODUK]
		);'

	EXEC(@sql_query)


	UPDATE #RESULT_TABLE
	SET
		[SUPERCIF] = [SOURCE].[SUPERCIF]
		,[NAMANASABAH] = [SOURCE].[NAMANASABAH]
		,[NO_HP] = [SOURCE].[NO_HP]
		,[NO_TELP] = [SOURCE].[NO_TELP]
		,[KTP] = [SOURCE].[KTP]
		,[NPWP] = [SOURCE].[NPWP]
		,[TANGGAL_LAHIR] = [SOURCE].[TANGGAL_LAHIR]
	FROM #RESULT_TABLE [TARGET]
	LEFT JOIN
		(
			SELECT
				LEGACY
				,NOMORCIF
				,SUPERCIF
				,NAMANASABAH
				,NO_HP
				,NO_TELP
				,KTP
				,NPWP
				,TANGGAL_LAHIR
			FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL]
			WHERE [NOMORCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
			OR [SUPERCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
		) [SOURCE]
		ON [TARGET].[LEGACY] = [SOURCE].[LEGACY]
		AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]

	UPDATE #RESULT_TABLE
		SET
			[NAMAOUTLET] = COALESCE([SOURCE].[Nama Outlet], [TARGET].[NAMAOUTLET])
			,[AREA] = COALESCE([SOURCE].[Nama Area], [TARGET].[AREA])
			,[REGION] = COALESCE([SOURCE].[Nama RO], [TARGET].[REGION])
		FROM #RESULT_TABLE [TARGET]
		LEFT JOIN [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_JOIN.MAPPING.JOIN.CABANG_BSI_UPDATE] [SOURCE]
			ON [TARGET].[KODEOUTLET] = [SOURCE].[kode outlet]

	UPDATE #RESULT_TABLE
		SET
			[TANGGAL_AKTIF_AKHIR] = [SOURCE].[TGL_AKTIF_AKHIR]
			,[DIVISI] = COALESCE([TARGET].[DIVISI], [NEW_BSI_COLLECTION].[dbo].[fx_adjustment_divisi_bsi]([SOURCE].[DIVISI]))
		FROM #RESULT_TABLE [TARGET]
		LEFT JOIN [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.TGL_AKTIF] [SOURCE]
			ON [TARGET].[LEGACY] = [SOURCE].[LEGACY]
			AND [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]

	UPDATE #RESULT_TABLE
		SET
			[OS_POKOK_PSAK_CURRENT] = [SOURCE].[(RCG) OS_POKOK_PSAK_CURRENT]
			,[KOL] = [SOURCE].[(RCG) KOL_CIF_PECAH]
			,[DIVISI] = COALESCE([TARGET].[DIVISI], [SOURCE].[(RCG) DIVISI_BSI])
			,[PRODUK] = COALESCE([TARGET].[PRODUK], [SOURCE].[(EDA) PRODUK])
		FROM #RESULT_TABLE [TARGET]
		LEFT JOIN [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_ONBS.GENERATED.JOIN.PORTOFOLIO_CURRENT] [SOURCE]
		--LEFT JOIN [NEW_BSI_STORAGE].[dbo].[BSI.PORTOFOLIO_DAILY.2022-12-27] [SOURCE]
			ON [TARGET].[LEGACY] = [SOURCE].[(RCG) SOURCE_CURRENT]
			AND [TARGET].[NOLOAN] = [SOURCE].[(SOURCE) NOLOAN_CURRENT]
			AND [TARGET].[NOMORCIF] = RIGHT([SOURCE].[(SOURCE) NOMORCIF_CURRENT], 15)
			AND [SOURCE].[(RCG) KOL_CIF_PECAH] NOT IN ('Lunas', 'Suspect', 'WO')

	UPDATE #RESULT_TABLE
		SET
			[TANGGAL_AKTIF_AKHIR] = COALESCE([SOURCE].[Tgl Current], [TARGET].[TANGGAL_AKTIF_AKHIR])
			,[OS_POKOK_PSAK_CURRENT] = COALESCE([SOURCE].[OS Pokok Current Conversion], [TARGET].[OS_POKOK_PSAK_CURRENT])
			,[KOL] = 'WO'
			,[TGL_WO] = [SOURCE].[Tgl WO Tgl Hapus Buku]
			,[DIVISI] = COALESCE([TARGET].DIVISI, [SOURCE].[Divisi])
			,[PRODUK] = COALESCE([TARGET].PRODUK, [SOURCE].[Produk BSI])
		FROM #RESULT_TABLE [TARGET]
		LEFT JOIN [NEW_BSI_COLLECTION].[dbo].[PORTOFOLIO_WO.GENERATED.JOIN.WO_CURRENT] [SOURCE]
			ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
			AND [TARGET].[NOMORCIF] = RIGHT([SOURCE].[CIF], 15)
	WHERE [SOURCE].[NOLOAN] IS NOT NULL

	INSERT INTO #RESULT_TABLE
		(
			LEGACY
			,NOMORCIF
			,SUPERCIF
			,NAMANASABAH
			,NO_HP
			,NO_TELP
			,KTP
			,NPWP
			,TANGGAL_LAHIR
		)
	SELECT
		[SOURCE].LEGACY
		,[SOURCE].NOMORCIF
		,[SOURCE].SUPERCIF
		,[SOURCE].NAMANASABAH
		,[SOURCE].NO_HP
		,[SOURCE].NO_TELP
		,[SOURCE].KTP
		,[SOURCE].NPWP
		,[SOURCE].TANGGAL_LAHIR
	FROM
		(
			SELECT
				*
			FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL]
			WHERE
			(
				SUPERCIF IN (SELECT NOMORCIF FROM #NOMORCIF)
				OR NOMORCIF IN (SELECT NOMORCIF FROM #NOMORCIF)
			)
			AND
			NOT (
				LEGACY = 'BSM'
				AND LEN(NOMORCIF) > 8
			)
		) [SOURCE]
	LEFT JOIN #RESULT_TABLE [TARGET]
		ON [SOURCE].[NOMORCIF] = [TARGET].[NOMORCIF]
		AND [SOURCE].[LEGACY] = [TARGET].[LEGACY]
	WHERE [TARGET].[NOMORCIF] IS NULL

	INSERT INTO #REKAP_ADJUSTMENT
	(
		TGL_AKTIF_AKHIR
		,OS_PSAK_CIF
		,KOL
		,[LEGACY]
		,[NOMORCIF]
		,[SUPERCIF]
		,NAMANASABAH
		,AREA_CIF
		,REGION_CIF
		,NO_HP
		,NO_TELP
		,KTP
		,NPWP
		,TGL_LAHIR
		,TGL_WO
		,DIVISI
		,PRODUK
	)
	SELECT
		MAX(TANGGAL_AKTIF_AKHIR) AS TGL_AKTIF_AKHIR
		,SUM(OS_POKOK_PSAK_CURRENT) AS OS_PSAK_CIF
		,MAX(KOL) AS KOL
		,[LEGACY]
		,[NOMORCIF]
		,COALESCE([SUPERCIF], [NOMORCIF]) AS [SUPERCIF]
		,MAX(NAMANASABAH) AS NAMANASABAH
		,MAX([AREA]) AS AREA_CIF
		,MAX([REGION]) AS REGION_CIF
		,MAX(NO_HP) AS NO_HP
		,MAX(NO_TELP) AS NO_TELP
		,MAX(KTP) AS KTP
		,MAX(NPWP) AS NPWP
		,MAX(TANGGAL_LAHIR) AS TGL_LAHIR
		,MAX(TGL_WO) AS TGL_WO
		,MAX([DIVISI].[DIVISI]) AS DIVISI
		,MAX([DIVISI].[PRODUK]) AS PRODUK
	FROM #RESULT_TABLE [SOURCE]
	OUTER APPLY (
		SELECT TOP 1
			[DIVISI]
			,[PRODUK]
		FROM #RESULT_TABLE
		WHERE
			[LEGACY] = [SOURCE].[LEGACY]
			AND [NOMORCIF] = [SOURCE].[NOMORCIF]
		GROUP BY
			[DIVISI]
			,[PRODUK]
		ORDER BY
			SUM(OS_POKOK_PSAK_CURRENT) DESC
			,MAX(TANGGAL_AKTIF_AKHIR) DESC
	) [DIVISI]
	WHERE [LEGACY] IS NOT NULL
	GROUP BY
		[LEGACY]
		,[NOMORCIF]
		,[SUPERCIF]
	ORDER BY
		CASE WHEN NOMORCIF != SUPERCIF THEN 1 ELSE 0 END DESC
		,MAX(TANGGAL_AKTIF_AKHIR) DESC
		,SUM(OS_POKOK_PSAK_CURRENT) DESC
		,MAX(TANGGAL_LAHIR) DESC
		,MAX(NPWP) DESC
		,MAX(KTP) DESC
		,MAX(NO_HP) DESC

	SET @SUPERCIF_SET = (SELECT TOP 1 SUPERCIF FROM #REKAP_ADJUSTMENT WHERE LEGACY = 'BSM')
	UPDATE #REKAP_ADJUSTMENT SET SUPERCIF = @SUPERCIF_SET

	UPDATE #REKAP_ADJUSTMENT
	SET
		KETERANGAN =
			CASE
				WHEN (SELECT COUNT(1) FROM #REKAP_ADJUSTMENT WHERE KOL = 'WO' AND OS_PSAK_CIF > 0.00) > 0 AND (SELECT COUNT(1) FROM #REKAP_ADJUSTMENT WHERE LEFT(KOL, 1) IN ('1', '2', '3', '4', '5')) > 0 AND KOL IS NOT NULL THEN 'PARTIAL WO'
				WHEN (SELECT COUNT(1) FROM #REKAP_ADJUSTMENT WHERE LEGACY = 'BSM') = 1 AND (SELECT MAX(LEN(NOMORCIF)) FROM #REKAP_ADJUSTMENT) >= 14 THEN 'MAPPING NOMOR CIF HASANAH CARD'
				WHEN (SELECT COUNT(1) FROM #REKAP_ADJUSTMENT WHERE LEGACY = 'BSM') = 1 THEN 'MAPPING NOMORCIF LEGACY'
			END
		,[FLAG RCG] =
			CASE
				WHEN (SELECT COUNT(1) FROM #REKAP_ADJUSTMENT WHERE KOL = 'WO' AND OS_PSAK_CIF > 0.00) > 0 AND (SELECT COUNT(1) FROM #REKAP_ADJUSTMENT WHERE LEFT(KOL, 1) IN ('1', '2', '3', '4', '5')) > 0 AND KOL IS NOT NULL THEN 'CHECK OBLIGASI HAPUS BUKU'
			END

	------------------------------------------------------------------------------------------------------

	INSERT INTO [PORTOFOLIO.ONBS.REKAP_ADJUSTMENT_SUPERCIF]
	SELECT
		*
	FROM #REKAP_ADJUSTMENT
	WHERE NOMORCIF NOT IN (SELECT NOMORCIF FROM [PORTOFOLIO.ONBS.REKAP_ADJUSTMENT_SUPERCIF])

	------------------------------------------------------------------------------------------------------
	
	INSERT INTO #TEMP_MAPPING
	SELECT
		[TARGET].[LEGACY]
		,[TARGET].[NOMORCIF]
		,[TARGET].[NAMANASABAH]
		,[SOURCE].[NPWP]
		,[SOURCE].[KTP]
		,[SOURCE].[NO_TELP]
		,[SOURCE].[NO_KANTOR]
		,[SOURCE].[NO_HP]
		,[SOURCE].[ALT_CONTACT_1]
		,[SOURCE].[ALT_CONTACT_2]
		,[SOURCE].[ALT_CONTACT_3]
		,[SOURCE].[TANGGAL_LAHIR]
		,[SOURCE].[PEKERJAAN]
		,[SOURCE].[ALAMAT]
	FROM
		(
			SELECT
				LEGACY
				,NOMORCIF
				,NAMANASABAH
			FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL] [TARGET]
			WHERE [TARGET].[NOMORCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
			OR [TARGET].[SUPERCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
		) [TARGET]
	OUTER APPLY
		(
			SELECT
				MAX(NPWP) AS NPWP
				,MAX(KTP) AS KTP
				,MAX(NO_HP) AS NO_HP
				,MAX(NO_TELP) AS NO_TELP
				,MAX(NO_KANTOR) AS NO_KANTOR
				,MIN(NO_HP) AS ALT_CONTACT_1
				,MIN(NO_TELP) AS ALT_CONTACT_2
				,MIN(NO_KANTOR) AS ALT_CONTACT_3
				,MAX(TANGGAL_LAHIR) AS TANGGAL_LAHIR
				,MAX(PEKERJAAN) AS PEKERJAAN
				,MAX(ALAMAT) AS ALAMAT
			FROM
				(
					SELECT
						CASE WHEN NPWP IN (SELECT NPWP FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_NPWP]) THEN NULL ELSE NPWP END AS NPWP
						,CASE WHEN KTP IN (SELECT KTP FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_KTP]) THEN NULL ELSE KTP END AS KTP
						,CASE WHEN NO_HP IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_HP END AS NO_HP
						,CASE WHEN NO_TELP IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_TELP END AS NO_TELP
						,CASE WHEN NO_KANTOR IN (SELECT CONTACT FROM [NEW_BSI_DEV].[dbo].[FILTER.ANOMALI.INVALID_CONTACT]) THEN NULL ELSE NO_KANTOR END AS NO_KANTOR
						,TANGGAL_LAHIR
						,PEKERJAAN
						,ALAMAT
					FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL]
					WHERE [NOMORCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
					OR [SUPERCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
				) [TEMP_TB]
		) [SOURCE]

	-------------------------------------------------------------------------------

	UPDATE [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL]
	SET
		[SUPERCIF] = COALESCE(NULLIF(@SUPERCIF_SET, ''), [TARGET].[SUPERCIF])
		,[NPWP] = [SOURCE].[NPWP]
		,[KTP] = [SOURCE].[KTP]
		,[NO_HP] = [SOURCE].[NO_HP]
		,[NO_TELP] = [SOURCE].[NO_TELP]
		,[NO_KANTOR] = [SOURCE].[NO_KANTOR]
		,[ALT_CONTACT_1] = [SOURCE].[ALT_CONTACT_1]
		,[ALT_CONTACT_2] = [SOURCE].[ALT_CONTACT_2]
		,[ALT_CONTACT_3] = [SOURCE].[ALT_CONTACT_3]
		,[TANGGAL_LAHIR] = [SOURCE].[TANGGAL_LAHIR]
		,[PEKERJAAN] = [SOURCE].[PEKERJAAN]
		,[ALAMAT] = [SOURCE].[ALAMAT]
	FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.CIF_DETAIL] [TARGET]
	LEFT JOIN #TEMP_MAPPING [SOURCE]
		ON [TARGET].[LEGACY] = [SOURCE].[LEGACY]
		AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
	WHERE [TARGET].[NOMORCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
	OR [TARGET].[SUPERCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)

	-------------------------------------------------------------------------------

	DELETE FROM [NEW_BSI_DEV].[dbo].[PORTOFOLIO.ONBS.SUSPECT_SUPERCIF]
	WHERE
		[NOMORCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)
		AND [SUPERCIF] IN (SELECT NOMORCIF FROM #NOMORCIF)

	--SELECT * FROM #REKAP_ADJUSTMENT
	
	FETCH NEXT FROM load_cursor INTO @NOMORCIF_CHECK, @SUPERCIF_CHECK
END

CLOSE load_cursor
DEALLOCATE load_cursor
*/