BEGIN TRY
	CREATE TABLE [report].[LIST_SOFIE] (
		[TGL_DATA] date  NULL,
		[NOLOAN] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[NOMORCIF] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[SUPERCIF] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[NAMANASABAH] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[KODECABANG] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[NAMACABANG] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[AREA] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[REGION] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[DIVISI] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[PRODUK] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[PRODUK_DETAIL] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[KOL_LOAN] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[KOL_CIF] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[KOL_SUPERCIF] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
		[OS_POKOK_PSAK] decimal(20,2)  NULL,
		[OS_POKOK] decimal(20,2)  NULL,
		[KRITERIA] varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL
	);
END TRY
BEGIN CATCH
END CATCH

TRUNCATE TABLE [report].[LIST_SOFIE];

--------------------------------------------------------------------

MERGE [report].[LIST_SOFIE] [TARGET]
USING (
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,'SOFIE 1' [KRITERIA]
	FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
	LEFT JOIN [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)] [SOURCE]
		ON [CUR].[NOLOAN] = [SOURCE].[NOLOAN]
	OUTER APPLY (
		SELECT
			MAX([BY_CIF]) [BY_CIF]
			,MAX([BY_SUPERCIF]) [BY_SUPERCIF]
		FROM (
			SELECT
				CASE WHEN [NOMORCIF] = [CUR].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
				,[KOL_SUPERCIF] [BY_SUPERCIF]
			FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
			WHERE [CUR].[SUPERCIF] = [SUPERCIF]
				AND [CUR].[DIVISI] = [DIVISI]
		) [SUB]
	) [KOL_SUPERCIF]
	WHERE
		(
			[CUR].[DIVISI] IN ('Konsumer')
			AND [CUR].[KOL_SUPERCIF] IN ('2A', '2C', '3A')
			AND LEFT(COALESCE([SOURCE].[KOL_SUPERCIF], [KOL_SUPERCIF].[BY_CIF], [KOL_SUPERCIF].[BY_SUPERCIF], '1'), 1) > LEFT([CUR].[KOL_SUPERCIF], 1)
		)
		OR
		(
			[CUR].[DIVISI] IN ('SME', 'Mikro')
			AND [CUR].[KOL_SUPERCIF] IN ('3A')
			AND COALESCE([SOURCE].[KOL_SUPERCIF], [KOL_SUPERCIF].[BY_CIF], [KOL_SUPERCIF].[BY_SUPERCIF], '1') > [CUR].[KOL_SUPERCIF]
		)
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
WHEN NOT MATCHED BY TARGET THEN
INSERT VALUES 
(
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[KODECABANG]
	,[SOURCE].[NAMACABANG]
	,[SOURCE].[AREA]
	,[SOURCE].[REGION]
	,[SOURCE].[DIVISI]
	,[SOURCE].[PRODUK]
	,[SOURCE].[PRODUK_DETAIL]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_CIF]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK_PSAK]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[KRITERIA]
);

--------------------------------------------------------------------

MERGE [report].[LIST_SOFIE] [TARGET]
USING (
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,'SOFIE 2' [KRITERIA]
	FROM [series].[RCG.LOAN_DAILY.2023-06-15] [CUR]
	LEFT JOIN [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)] [SOURCE]
		ON [CUR].[NOLOAN] = [SOURCE].[NOLOAN]
	OUTER APPLY (
		SELECT
			MAX([BY_CIF]) [BY_CIF]
			,MAX([BY_SUPERCIF]) [BY_SUPERCIF]
		FROM (
			SELECT
				CASE WHEN [NOMORCIF] = [CUR].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
				,[KOL_SUPERCIF] [BY_SUPERCIF]
			FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
			WHERE [CUR].[SUPERCIF] = [SUPERCIF]
				AND [CUR].[DIVISI] = [DIVISI]
		) [SUB]
	) [KOL_SUPERCIF]
	WHERE
		(
			[CUR].[DIVISI] IN ('Konsumer')
			AND [CUR].[KOL_SUPERCIF] IN ('2A', '2C', '3A')
			AND LEFT(COALESCE([SOURCE].[KOL_SUPERCIF], [KOL_SUPERCIF].[BY_CIF], [KOL_SUPERCIF].[BY_SUPERCIF], '1'), 1) > LEFT([CUR].[KOL_SUPERCIF], 1)
		)
		OR
		(
			[CUR].[DIVISI] IN ('SME', 'Mikro')
			AND [CUR].[KOL_SUPERCIF] IN ('3A')
			AND COALESCE([SOURCE].[KOL_SUPERCIF], [KOL_SUPERCIF].[BY_CIF], [KOL_SUPERCIF].[BY_SUPERCIF], '1') > [CUR].[KOL_SUPERCIF]
		)
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
WHEN NOT MATCHED BY TARGET THEN
INSERT VALUES 
(
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[KODECABANG]
	,[SOURCE].[NAMACABANG]
	,[SOURCE].[AREA]
	,[SOURCE].[REGION]
	,[SOURCE].[DIVISI]
	,[SOURCE].[PRODUK]
	,[SOURCE].[PRODUK_DETAIL]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_CIF]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK_PSAK]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[KRITERIA]
);

--------------------------------------------------------------------

MERGE [report].[LIST_SOFIE] [TARGET]
USING (
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,'SOFIE 3' [KRITERIA]
	FROM [series].[RCG.LOAN_DAILY.2023-06-15] [CUR]
	WHERE
	(
		(
			[CUR].[DIVISI] = 'Konsumer'
			AND [CUR].[KOL_SUPERCIF] IN ('2A', '2C', '3A')
		)
		OR
		(
			[CUR].[DIVISI] IN ('SME', 'Mikro')
			AND [CUR].[KOL_SUPERCIF] IN ('3A')
		)
	)
	AND
	(
		CASE
			WHEN [CUR].[KOL_SUPERCIF] IN ('2A') THEN COALESCE([CUR].[TUNGGAKAN_POKOK], 0.00)+COALESCE([CUR].[TUNGGAKAN_MARGIN], 0.00)
			WHEN COALESCE([CUR].[ANGSURAN], 0.00) = COALESCE([CUR].[TUNGGAKAN_POKOK], 0.00)+COALESCE([CUR].[TUNGGAKAN_MARGIN], 0.00)
				THEN COALESCE([CUR].[TUNGGAKAN_POKOK], 0.00)+COALESCE([CUR].[TUNGGAKAN_MARGIN], 0.00)
			ELSE
				(COALESCE([CUR].[TUNGGAKAN_POKOK], 0.00)+COALESCE([CUR].[TUNGGAKAN_MARGIN], 0.00)) - 
				(
					TRY_CAST(
						(COALESCE([CUR].[TUNGGAKAN_POKOK], 0.00)+COALESCE([CUR].[TUNGGAKAN_MARGIN], 0.00))
						/ COALESCE(NULLIF((COALESCE([CUR].[ANGSURAN], 0.00)), 0.00), 1.00)
						AS INTEGER
					)			
					* (COALESCE([CUR].[ANGSURAN], 0.00))
				)
		END <= 1000000.00
	)
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
WHEN NOT MATCHED BY TARGET THEN
INSERT VALUES 
(
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[KODECABANG]
	,[SOURCE].[NAMACABANG]
	,[SOURCE].[AREA]
	,[SOURCE].[REGION]
	,[SOURCE].[DIVISI]
	,[SOURCE].[PRODUK]
	,[SOURCE].[PRODUK_DETAIL]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_CIF]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK_PSAK]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[KRITERIA]
);

--------------------------------------------------------------------

MERGE [report].[LIST_SOFIE] [TARGET]
USING (
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,'SOFIE 4' [KRITERIA]
	FROM [series].[RCG.LOAN_DAILY.2023-06-15] [CUR]
	LEFT JOIN [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)] [SOURCE]
		ON [CUR].[NOLOAN] = [SOURCE].[NOLOAN]
	OUTER APPLY (
		SELECT
			MAX([BY_CIF]) [BY_CIF]
			,MAX([BY_SUPERCIF]) [BY_SUPERCIF]
		FROM (
			SELECT
				CASE WHEN [NOMORCIF] = [CUR].[NOMORCIF] THEN [KOL_SUPERCIF] ELSE NULL END [BY_CIF]
				,[KOL_SUPERCIF] [BY_SUPERCIF]
			FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
			WHERE [CUR].[SUPERCIF] = [SUPERCIF]
				AND [CUR].[DIVISI] = [DIVISI]
		) [SUB]
	) [KOL_SUPERCIF]
	WHERE
	(
		(
			[CUR].[DIVISI] = 'Konsumer'
			AND [CUR].[KOL_SUPERCIF] IN ('2A', '2C', '3A')
		)
		OR
		(
			[CUR].[DIVISI] IN ('SME', 'Mikro')
			AND [CUR].[KOL_SUPERCIF] IN ('3A')
		)
	)
	AND
	(
		COALESCE([SOURCE].[KOL_SUPERCIF], [KOL_SUPERCIF].[BY_CIF], [KOL_SUPERCIF].[BY_SUPERCIF], '1') IN ('1') AND LEFT([CUR].[KOL_SUPERCIF], 1) IN ('2')
		OR COALESCE([SOURCE].[KOL_SUPERCIF], [KOL_SUPERCIF].[BY_CIF], [KOL_SUPERCIF].[BY_SUPERCIF], '1') IN ('1', '2A', '2B', '2C') AND LEFT([CUR].[KOL_SUPERCIF], 1) IN ('3', '4', '5')
	)
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
WHEN NOT MATCHED BY TARGET THEN
INSERT VALUES 
(
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[KODECABANG]
	,[SOURCE].[NAMACABANG]
	,[SOURCE].[AREA]
	,[SOURCE].[REGION]
	,[SOURCE].[DIVISI]
	,[SOURCE].[PRODUK]
	,[SOURCE].[PRODUK_DETAIL]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_CIF]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK_PSAK]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[KRITERIA]
);

--------------------------------------------------------------------

WITH CTE AS
(
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,ROW_NUMBER() OVER (
			PARTITION BY
				[DIVISI]
				,[KOL_SUPERCIF]
				,[AREA]
			ORDER BY
				[OUT].[OS_POKOK_PSAK]
		) [RANK]
	FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
	OUTER APPLY (
		SELECT
			SUM([OS_POKOK_PSAK]) [OS_POKOK_PSAK]
		FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)]
		WHERE [CUR].[SUPERCIF] = [SUPERCIF]
		AND [CUR].[DIVISI] = [DIVISI]
		AND [CUR].[KOL_SUPERCIF] = [KOL_SUPERCIF]
	) [OUT]
	WHERE
	(
		(
			[CUR].[DIVISI] = 'Konsumer'
			AND [CUR].[KOL_SUPERCIF] IN ('2A', '2C', '3A')
			AND [CUR].[PRODUK] NOT LIKE '%Oto%'
		)
		OR
		(
			[CUR].[DIVISI] IN ('SME', 'Mikro')
			AND [CUR].[KOL_SUPERCIF] IN ('3A')
		)
	)
)
MERGE [report].[LIST_SOFIE] [TARGET]
USING (
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,[CUR].[RANK]
		,'SOFIE 5' [KRITERIA]
	FROM CTE [CUR]
	WHERE [RANK] <= 50
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
WHEN NOT MATCHED BY TARGET THEN
INSERT VALUES 
(
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[KODECABANG]
	,[SOURCE].[NAMACABANG]
	,[SOURCE].[AREA]
	,[SOURCE].[REGION]
	,[SOURCE].[DIVISI]
	,[SOURCE].[PRODUK]
	,[SOURCE].[PRODUK_DETAIL]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_CIF]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK_PSAK]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[KRITERIA]
);