SELECT
	[CUR].[TGL_DATA]
	,[CUR].[NOLOAN]
	,[CUR].[NOMORCIF]
	,[CUR].[SUPERCIF]
	,[CUR].[NAMANASABAH]
	,[CUR].[KODECABANG]
	,[CUR].[NAMACABANG]
	,[CUR].[AREA]
	,[CUR].[REGION]
	,[CUR].[DIVISI]
	,[CUR].[PRODUK]
	,[CUR].[PRODUK_DETAIL]
	,[CUR].[KOL_LOAN]
	,[CUR].[KOL_CIF]
	,[CUR].[KOL_SUPERCIF]
	,[CUR].[OS_POKOK_PSAK]
	,[CUR].[OS_POKOK]
FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) [KOL_LOAN]
		,MAX([KOL_CIF]) [KOL_CIF]
		,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
	FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
	WHERE [CUR].[NOLOAN] = [NOLOAN]
) [BY_LOAN]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) [KOL_LOAN]
		,MAX([KOL_CIF]) [KOL_CIF]
		,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
	FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
	WHERE [CUR].[NOMORCIF] = [NOMORCIF]
) [BY_CIF]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) [KOL_LOAN]
		,MAX([KOL_CIF]) [KOL_CIF]
		,MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
	FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
	WHERE [CUR].[SUPERCIF] = [SUPERCIF]
) [BY_SUPERCIF]
WHERE
(
	(
		[CUR].[DIVISI] = 'Konsumer'
		AND [CUR].[KOL_LOAN] IN ('2A', '2C', '3A')
	)
	OR
	(
		[CUR].[DIVISI] IN ('SME', 'Mikro')
		AND [CUR].[KOL_LOAN] IN ('3A')
	)
)
AND
(
	COALESCE([BY_LOAN].[KOL_SUPERCIF], [BY_CIF].[KOL_SUPERCIF], [BY_SUPERCIF].[KOL_SUPERCIF], '1') IN ('1') AND LEFT([CUR].[KOL_SUPERCIF], 1) IN ('2')
	OR COALESCE([BY_LOAN].[KOL_SUPERCIF], [BY_CIF].[KOL_SUPERCIF], [BY_SUPERCIF].[KOL_SUPERCIF], '1') IN ('1', '2A', '2B', '2C') AND LEFT([CUR].[KOL_SUPERCIF], 1) IN ('3', '4', '5')
)