SELECT
	COALESCE([LAST_MONTH].[KOL_SUPERCIF], '01. Cair Baru') [KOL_SUPERCIF]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('1') THEN 1 ELSE 0 END) [ACCT_KOL_1]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('2A') THEN 1 ELSE 0 END) [ACCT_KOL_2A]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('2B') THEN 1 ELSE 0 END) [ACCT_KOL_2B]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('2C') THEN 1 ELSE 0 END) [ACCT_KOL_2C]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('3A') THEN 1 ELSE 0 END) [ACCT_KOL_3A]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('3B') THEN 1 ELSE 0 END) [ACCT_KOL_3B]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('3C') THEN 1 ELSE 0 END) [ACCT_KOL_3C]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('4A') THEN 1 ELSE 0 END) [ACCT_KOL_4A]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('4B') THEN 1 ELSE 0 END) [ACCT_KOL_4B]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('4C') THEN 1 ELSE 0 END) [ACCT_KOL_4C]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('5') THEN 1 ELSE 0 END) [ACCT_KOL_5]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IS NULL THEN 1 ELSE 0 END) [ACCT_RUN_OFF]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('1') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_1]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('2A') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_2A]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('2B') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_2B]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('2C') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_2C]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('3A') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_3A]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('3B') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_3B]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('3C') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_3C]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('4A') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_4A]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('4B') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_4B]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('4C') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_4C]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IN ('5') THEN [CUR].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_KOL_5]
	,SUM(CASE WHEN [CUR].[KOL_SUPERCIF] IS NULL THEN [LAST_MONTH].[OS_POKOK_PSAK] ELSE 0.00 END) / 1000000000.00 [OS_RUN_OFF]
FROM [series].[RCG.LOAN_DAILY.2023-06-19] [CUR]
FULL OUTER JOIN [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [LAST_MONTH]
	ON [CUR].[NOLOAN] = [LAST_MONTH].[NOLOAN]
WHERE COALESCE([CUR].[DIVISI], [LAST_MONTH].[DIVISI]) IN ('Konsumer', 'Hasanah Card', 'Pawning', 'Mikro', 'SME')
-- AND COALESCE([CUR].[DIVISI], [LAST_MONTH].[DIVISI]) IN ('Mikro')
-- AND COALESCE([CUR].[PRODUK], [LAST_MONTH].[PRODUK]) LIKE '%Pensiun%'
-- AND COALESCE([CUR].[PRODUK_DETAIL], [LAST_MONTH].[PRODUK_DETAIL]) LIKE '%FLPP%'
GROUP BY COALESCE([LAST_MONTH].[KOL_SUPERCIF], '01. Cair Baru')
ORDER BY COALESCE([LAST_MONTH].[KOL_SUPERCIF], '01. Cair Baru')