SELECT
	[CUR].[TGL_DATA]
	,[CUR].[NOLOAN]
	,[CUR].[NOMORCIF]
	,[CUR].[SUPERCIF]
	,[CUR].[NAMANASABAH]
	,[CUR].[KODECABANG]
	,[CUR].[NAMACABANG]
	,[CUR].[AREA]
	,[CUR].[REGION]
	,[CUR].[DIVISI]
	,[CUR].[PRODUK]
	,[CUR].[PRODUK_DETAIL]
	,[CUR].[KOL_LOAN]
	,[CUR].[KOL_CIF]
	,[CUR].[KOL_SUPERCIF]
	,[CUR].[OS_POKOK_PSAK]
	,[CUR].[OS_POKOK]
FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
OUTER APPLY (
	SELECT
		SUM([OS_POKOK_PSAK]) [OS_POKOK_PSAK]
	FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)]
	WHERE [CUR].[SUPERCIF] = [SUPERCIF]
	AND [CUR].[DIVISI] = [DIVISI]
	AND [CUR].[PRODUK] = [PRODUK]
) [SUPERCIF]
WHERE
	[CUR].[DIVISI] IN ('Mikro')
	AND [CUR].[PRODUK] IN ('KUR')
	AND [SUPERCIF].[OS_POKOK_PSAK] >= 100000000.00
ORDER BY
	[SUPERCIF].[OS_POKOK_PSAK] DESC
	,[CUR].[SUPERCIF]