WITH CTE AS
(
	SELECT
		[CUR].[TGL_DATA]
		,[CUR].[NOLOAN]
		,[CUR].[NOMORCIF]
		,[CUR].[SUPERCIF]
		,[CUR].[NAMANASABAH]
		,[CUR].[KODECABANG]
		,[CUR].[NAMACABANG]
		,[CUR].[AREA]
		,[CUR].[REGION]
		,[CUR].[DIVISI]
		,[CUR].[PRODUK]
		,[CUR].[PRODUK_DETAIL]
		,[CUR].[KOL_LOAN]
		,[CUR].[KOL_CIF]
		,[CUR].[KOL_SUPERCIF]
		,[CUR].[OS_POKOK_PSAK]
		,[CUR].[OS_POKOK]
		,ROW_NUMBER() OVER (
			PARTITION BY
				[DIVISI]
				,[KOL_SUPERCIF]
				,[AREA]
			ORDER BY
				[OUT].[OS_POKOK_PSAK]
		) [RANK]
	FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
	OUTER APPLY (
		SELECT
			SUM([OS_POKOK_PSAK]) [OS_POKOK_PSAK]
		FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)]
		WHERE [CUR].[SUPERCIF] = [SUPERCIF]
		AND [CUR].[DIVISI] = [DIVISI]
		AND [CUR].[KOL_SUPERCIF] = [KOL_SUPERCIF]
	) [OUT]
	WHERE
	(
		(
			[CUR].[DIVISI] = 'Konsumer'
			AND [CUR].[KOL_SUPERCIF] IN ('2A', '2C', '3A')
			AND [CUR].[PRODUK] NOT LIKE '%Oto%'
		)
		OR
		(
			[CUR].[DIVISI] IN ('SME', 'Mikro')
			AND [CUR].[KOL_SUPERCIF] IN ('3A')
		)
	)
)
SELECT
	[CUR].[TGL_DATA]
	,[CUR].[NOLOAN]
	,[CUR].[NOMORCIF]
	,[CUR].[SUPERCIF]
	,[CUR].[NAMANASABAH]
	,[CUR].[KODECABANG]
	,[CUR].[NAMACABANG]
	,[CUR].[AREA]
	,[CUR].[REGION]
	,[CUR].[DIVISI]
	,[CUR].[PRODUK]
	,[CUR].[PRODUK_DETAIL]
	,[CUR].[KOL_LOAN]
	,[CUR].[KOL_CIF]
	,[CUR].[KOL_SUPERCIF]
	,[CUR].[OS_POKOK_PSAK]
	,[CUR].[OS_POKOK]
	,[CUR].[RANK]
FROM CTE [CUR]
WHERE [RANK] <= 50
ORDER BY
	[KOL_SUPERCIF]
	,[DIVISI]
	,[AREA]
	,[RANK]