DECLARE
	@TGL_DATA DATE = '2023-07-31'
	,@TARGET_TABLE_BEF VARCHAR(MAX) 
	,@TARGET_TABLE_CUR VARCHAR(MAX)
	,@SQL_QUERY VARCHAR(MAX)
	,@POINTER INT = 1;

BEGIN TRY	
	DROP TABLE [report].[DAILY_PAYMENT];
END TRY
BEGIN CATCH
END CATCH

CREATE TABLE [report].[DAILY_PAYMENT] (
	TGL_DATA DATE
	,NOLOAN VARCHAR(255)
	,NOMORCIF VARCHAR(255)
	,SUPERCIF VARCHAR(255)
	,NAMANASABAH VARCHAR(255)
	,KODECABANG VARCHAR(255)
	,NAMACABANG VARCHAR(255)
	,AREA VARCHAR(255)
	,REGION VARCHAR(255)
	,DIVISI VARCHAR(255)
	,PRODUK VARCHAR(255)
	,PRODUK_DETAIL VARCHAR(255)
	,JENISPIUTANGPEMBIAYAAN VARCHAR(255)
	,CYCLE VARCHAR(255)
	,KOL_LOAN_LM VARCHAR(255)
	,KOL_CIF_LM VARCHAR(255)
	,KOL_SUPERCIF_LM VARCHAR(255)
	,KOL_LOAN VARCHAR(255)
	,KOL_CIF VARCHAR(255)
	,KOL_SUPERCIF VARCHAR(255)
	,KOL_01 VARCHAR(255)
	,KOL_02 VARCHAR(255)
	,KOL_03 VARCHAR(255)
	,KOL_04 VARCHAR(255)
	,KOL_05 VARCHAR(255)
	,KOL_06 VARCHAR(255)
	,KOL_07 VARCHAR(255)
	,KOL_08 VARCHAR(255)
	,KOL_09 VARCHAR(255)
	,KOL_10 VARCHAR(255)
	,KOL_11 VARCHAR(255)
	,KOL_12 VARCHAR(255)
	,KOL_13 VARCHAR(255)
	,KOL_14 VARCHAR(255)
	,KOL_15 VARCHAR(255)
	,KOL_16 VARCHAR(255)
	,KOL_17 VARCHAR(255)
	,KOL_18 VARCHAR(255)
	,KOL_19 VARCHAR(255)
	,KOL_20 VARCHAR(255)
	,KOL_21 VARCHAR(255)
	,KOL_22 VARCHAR(255)
	,KOL_23 VARCHAR(255)
	,KOL_24 VARCHAR(255)
	,KOL_25 VARCHAR(255)
	,KOL_26 VARCHAR(255)
	,KOL_27 VARCHAR(255)
	,KOL_28 VARCHAR(255)
	,KOL_29 VARCHAR(255)
	,KOL_30 VARCHAR(255)
	,KOL_31 VARCHAR(255)
	,CASH_IN_01 DECIMAL(20, 2)
	,CASH_IN_02 DECIMAL(20, 2)
	,CASH_IN_03 DECIMAL(20, 2)
	,CASH_IN_04 DECIMAL(20, 2)
	,CASH_IN_05 DECIMAL(20, 2)
	,CASH_IN_06 DECIMAL(20, 2)
	,CASH_IN_07 DECIMAL(20, 2)
	,CASH_IN_08 DECIMAL(20, 2)
	,CASH_IN_09 DECIMAL(20, 2)
	,CASH_IN_10 DECIMAL(20, 2)
	,CASH_IN_11 DECIMAL(20, 2)
	,CASH_IN_12 DECIMAL(20, 2)
	,CASH_IN_13 DECIMAL(20, 2)
	,CASH_IN_14 DECIMAL(20, 2)
	,CASH_IN_15 DECIMAL(20, 2)
	,CASH_IN_16 DECIMAL(20, 2)
	,CASH_IN_17 DECIMAL(20, 2)
	,CASH_IN_18 DECIMAL(20, 2)
	,CASH_IN_19 DECIMAL(20, 2)
	,CASH_IN_20 DECIMAL(20, 2)
	,CASH_IN_21 DECIMAL(20, 2)
	,CASH_IN_22 DECIMAL(20, 2)
	,CASH_IN_23 DECIMAL(20, 2)
	,CASH_IN_24 DECIMAL(20, 2)
	,CASH_IN_25 DECIMAL(20, 2)
	,CASH_IN_26 DECIMAL(20, 2)
	,CASH_IN_27 DECIMAL(20, 2)
	,CASH_IN_28 DECIMAL(20, 2)
	,CASH_IN_29 DECIMAL(20, 2)
	,CASH_IN_30 DECIMAL(20, 2)
	,CASH_IN_31 DECIMAL(20, 2)
);

WHILE @POINTER <= RIGHT(@TGL_DATA, 2)
BEGIN
	
	SET @TARGET_TABLE_BEF = (
		SELECT TOP 1
			CONCAT('[', SCHEMA_NAME(SCHEMA_ID), '].[', name, ']') AS NAME
		FROM [sys].[objects]
		WHERE type_desc = 'USER_TABLE'
		AND name LIKE 'RCG.LOAN_DAILY.____-__-__%'
		AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) < CONCAT(LEFT(@TGL_DATA, 8), [BSI_FASTER].[dbo].[fx_ndigit_code](@POINTER, 2))
		ORDER BY
			TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) DESC
			,CASE
				WHEN name LIKE ('%(FINAL)') THEN 1
				WHEN name LIKE ('%(QC)') THEN -1
				ELSE 0
			END DESC
	);
	
	SET @TARGET_TABLE_CUR = (
		SELECT TOP 1
			CONCAT('[', SCHEMA_NAME(SCHEMA_ID), '].[', name, ']') AS NAME
		FROM [sys].[objects]
		WHERE type_desc = 'USER_TABLE'
		AND name LIKE 'RCG.LOAN_DAILY.____-__-__%'
		AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) <= CONCAT(LEFT(@TGL_DATA, 8), [BSI_FASTER].[dbo].[fx_ndigit_code](@POINTER, 2))
		ORDER BY
			TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) DESC
			,CASE
				WHEN name LIKE ('%(FINAL)') THEN 1
				WHEN name LIKE ('%(QC)') THEN -1
				ELSE 0
			END DESC
	);
	
	IF @POINTER = 1
	BEGIN
		SET @SQL_QUERY = CONCAT(
			'MERGE [report].[DAILY_PAYMENT] [TARGET]
			USING
			(
				SELECT
					NOLOAN
					,NOMORCIF
					,SUPERCIF
					,NAMANASABAH
					,KODECABANG
					,NAMACABANG
					,AREA
					,REGION
					,DIVISI
					,PRODUK
					,PRODUK_DETAIL
					,JENISPIUTANGPEMBIAYAAN
					,CYCLE
					,KOL_LOAN
					,KOL_CIF
					,KOL_SUPERCIF
				FROM ', @TARGET_TABLE_BEF, '
				WHERE [DIVISI] NOT IN (''Hasanah Card'')
			) [SOURCE]
				ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
			WHEN NOT MATCHED BY TARGET THEN
			INSERT (
				TGL_DATA
				,NOLOAN
				,NOMORCIF
				,SUPERCIF
				,NAMANASABAH
				,KODECABANG
				,NAMACABANG
				,AREA
				,REGION
				,DIVISI
				,PRODUK
				,PRODUK_DETAIL
				,JENISPIUTANGPEMBIAYAAN
				,CYCLE
				,KOL_LOAN_LM
				,KOL_CIF_LM
				,KOL_SUPERCIF_LM
			) VALUES
			(
				''', @TGL_DATA, '''
				,[SOURCE].NOLOAN
				,[SOURCE].NOMORCIF
				,[SOURCE].SUPERCIF
				,[SOURCE].NAMANASABAH
				,[SOURCE].KODECABANG
				,[SOURCE].NAMACABANG
				,[SOURCE].AREA
				,[SOURCE].REGION
				,[SOURCE].DIVISI
				,[SOURCE].PRODUK
				,[SOURCE].PRODUK_DETAIL
				,[SOURCE].JENISPIUTANGPEMBIAYAAN
				,[SOURCE].CYCLE
				,[SOURCE].KOL_LOAN
				,[SOURCE].KOL_CIF
				,[SOURCE].KOL_SUPERCIF
			);'
		);
		
		BEGIN TRY
			EXEC(@SQL_QUERY);
		END TRY
		BEGIN CATCH
			PRINT CONCAT('ERROR: ', ERROR_MESSAGE());
		END CATCH
	END
	
	SET @SQL_QUERY = CONCAT(
		'MERGE [report].[DAILY_PAYMENT] [TARGET]
		USING
		(
			SELECT
				NOLOAN
				,NOMORCIF
				,SUPERCIF
				,NAMANASABAH
				,KODECABANG
				,NAMACABANG
				,AREA
				,REGION
				,DIVISI
				,PRODUK
				,PRODUK_DETAIL
				,JENISPIUTANGPEMBIAYAAN
				,CYCLE
			FROM ', @TARGET_TABLE_CUR, '
			WHERE [DIVISI] NOT IN (''Hasanah Card'')
		) [SOURCE]
			ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
		WHEN NOT MATCHED BY TARGET THEN
		INSERT (
			TGL_DATA
			,NOLOAN
			,NOMORCIF
			,SUPERCIF
			,NAMANASABAH
			,KODECABANG
			,NAMACABANG
			,AREA
			,REGION
			,DIVISI
			,PRODUK
			,PRODUK_DETAIL
			,JENISPIUTANGPEMBIAYAAN
			,CYCLE
		) VALUES
		(
			''', @TGL_DATA, '''
			,[SOURCE].NOLOAN
			,[SOURCE].NOMORCIF
			,[SOURCE].SUPERCIF
			,[SOURCE].NAMANASABAH
			,[SOURCE].KODECABANG
			,[SOURCE].NAMACABANG
			,[SOURCE].AREA
			,[SOURCE].REGION
			,[SOURCE].DIVISI
			,[SOURCE].PRODUK
			,[SOURCE].PRODUK_DETAIL
			,[SOURCE].JENISPIUTANGPEMBIAYAAN
			,[SOURCE].CYCLE
		);'
	);
	
	BEGIN TRY
		EXEC(@SQL_QUERY);
	END TRY
	BEGIN CATCH
		PRINT CONCAT('ERROR: ', ERROR_MESSAGE())
	END CATCH
	
	SET @SQL_QUERY = CONCAT(
		'UPDATE [report].[DAILY_PAYMENT]
		SET
			[KOL_LOAN] = COALESCE([CURRENT].[KOL_LOAN], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], [TARGET].[KOL_LOAN], ''Lunas'')
			
			,[KOL_CIF] = COALESCE([CURRENT].[KOL_CIF], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], [TARGET].[KOL_CIF], ''Lunas'')
			,[KOL_SUPERCIF] = COALESCE([CURRENT].[KOL_SUPERCIF], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], [TARGET].[KOL_SUPERCIF], ''Lunas'')
			,[KOL_', [BSI_FASTER].[dbo].[fx_ndigit_code](@POINTER, 2), '] = COALESCE([CURRENT].[KOL_SUPERCIF], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'')
			,[CASH_IN_', [BSI_FASTER].[dbo].[fx_ndigit_code](@POINTER, 2), '] =
				[dbo].[fx_common_zerofy](COALESCE(CASE
-- 					WHEN [BEFORE].[KOL_SUPERCIF] IS NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[PENCAIRAN_POKOK] - [CURRENT].[OS_POKOK]
					WHEN [BEFORE].[KOL_SUPERCIF] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [BEFORE].[OS_POKOK] - [CURRENT].[OS_POKOK]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL AND COALESCE([CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') IN (''Lunas'') THEN [BEFORE].[OS_POKOK]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL AND COALESCE([CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') IN (''EKSEKUSI WO'') THEN [BEFORE].[OS_POKOK] - [CHECK_WO].[EKSEKUSI_WO]
					ELSE 0.00
				END, 0.00))
			+
				[dbo].[fx_common_zerofy](COALESCE(CASE
-- 					WHEN [BEFORE].[KOL_SUPERCIF] IS NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[PENCAIRAN_MARGIN] - [CURRENT].[OS_MARGIN]
					WHEN [BEFORE].[KOL_SUPERCIF] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [BEFORE].[OS_MARGIN] - [CURRENT].[OS_MARGIN]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL THEN 0.00
					ELSE 0.00
				END, 0.00))
			+
				[dbo].[fx_common_zerofy](COALESCE(CASE
					WHEN [BEFORE].[REALISASI_BAGIHASIL] IS NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[REALISASI_BAGIHASIL]
					WHEN [BEFORE].[REALISASI_BAGIHASIL] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[REALISASI_BAGIHASIL] - [BEFORE].[REALISASI_BAGIHASIL]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL THEN 0.00
				END, 0.00))
		FROM [report].[DAILY_PAYMENT] [TARGET]
		LEFT JOIN ', @TARGET_TABLE_CUR, ' [CURRENT]
			ON [TARGET].[NOLOAN] = [CURRENT].[NOLOAN]
		LEFT JOIN ', @TARGET_TABLE_BEF, ' [BEFORE]
			ON [TARGET].[NOLOAN] = [BEFORE].[NOLOAN]
		OUTER APPLY (
			SELECT
				MAX(CASE WHEN [NOLOAN_BARU] IS NOT NULL THEN ''BUKA TUTUP'' END) [FLAG]
			FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
			WHERE [NOLOAN_LAMA] = [CURRENT].[NOLOAN]
			AND [NOCIF_LAMA] = [CURRENT].[NOMORCIF]
			AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'', ''EKSEKUSI WO'')
		) [CHECK_BUKA_TUTUP]
		OUTER APPLY (
			SELECT
				MAX(CASE WHEN [NOLOAN_WO] IS NOT NULL THEN ''EKSEKUSI WO'' END) [FLAG]
				,SUM(CASE WHEN [NOLOAN_WO] IS NOT NULL THEN [BAKI_DEBET_IDR] END) [EKSEKUSI_WO]
			FROM [mapping].[PORTOFOLIO_ONBS.DATABASE.JOIN.EKSEKUSI_WO]
			WHERE [NOLOAN] = [CURRENT].[NOLOAN]
			AND [NOCIF] = [CURRENT].[NOMORCIF]
		) [CHECK_WO];'
	);
	
	BEGIN TRY
		EXEC(@SQL_QUERY);
	END TRY
	BEGIN CATCH
		PRINT CONCAT('ERROR: ', ERROR_MESSAGE());
	END CATCH
	
	SET @POINTER = @POINTER + 1;
END

SELECT * FROM [report].[DAILY_PAYMENT];