SELECT
	[CUR].[TGL_DATA]
	,[CUR].[NOLOAN]
	,[CUR].[NOMORCIF]
	,[CUR].[SUPERCIF]
	,[CUR].[NAMANASABAH]
	,[CUR].[KODECABANG]
	,[CUR].[NAMACABANG]
	,[CUR].[AREA]
	,[CUR].[REGION]
	,[CUR].[DIVISI]
	,[CUR].[PRODUK]
	,[CUR].[PRODUK_DETAIL]
	,[CUR].[KOL_LOAN]
	,[CUR].[KOL_CIF]
	,[CUR].[KOL_SUPERCIF]
	,[CUR].[OS_POKOK_PSAK]
	,[CUR].[OS_POKOK]
FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
LEFT JOIN [series].[CRG.LOAN_DAILY.2023-04-30] [CRG]
	ON [CUR].[NOLOAN] = [CRG].[NOLOAN]
OUTER APPLY (
	SELECT
		SUM([OS_POKOK_PSAK]) [OS_POKOK_PSAK]
	FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)]
	WHERE [CUR].[SUPERCIF] = [SUPERCIF]
	AND [CUR].[DIVISI] = [DIVISI]
	AND [CUR].[PRODUK] = [PRODUK]
) [SUPERCIF]
OUTER APPLY (
	SELECT
		MAX([ACCT]) [ACCT]
	FROM
	(
		SELECT
			[CUR].[SUPERCIF]
			,COUNT(1) [ACCT]
		FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.RESTRU]
		WHERE [CUR].[NOLOAN] = [NOLOAN]
		AND [RESTRUCTFLAG] IS NOT NULL
		AND [RESTRUCTDATE] IS NOT NULL
	) [TEMP]
) [FREQ_RESTRU]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [CUR].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [CUR].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [CUR].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M1]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [CUR].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [CUR].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [CUR].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M2]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-02-28 (FINAL)]
				WHERE [CUR].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-02-28 (FINAL)]
				WHERE [CUR].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-02-28 (FINAL)]
				WHERE [CUR].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M3]
WHERE
	(
		[CUR].[DIVISI] = 'Mikro'
		AND [CUR].[KOL_SUPERCIF] IN ('3A', '3B', '3C')
	)
	AND
		(
			(
				LEFT(COALESCE([KOL_M1].[KOL_SUPERCIF], '1'), 1) = LEFT([CUR].[KOL_SUPERCIF], 1)
				AND LEFT(COALESCE([KOL_M2].[KOL_SUPERCIF], '1'), 1) = LEFT([CUR].[KOL_SUPERCIF], 1)
				AND LEFT(COALESCE([KOL_M3].[KOL_SUPERCIF], '1'), 1) = LEFT([CUR].[KOL_SUPERCIF], 1)
			)
		)
	AND COALESCE([FREQ_RESTRU].[ACCT], 0) <= 1
	AND [CUR].[TANGGAL_JATUH_TEMPO] >= EOMONTH(DATEADD(MONTH, 6, [CUR].[TGL_DATA]))
	AND [SUPERCIF].[OS_POKOK_PSAK] >= 50000000.00
	/*FILTER FRONTLOADING BELUM DITERAPKAN*/
	/*FILTER KEMAMPUAN BAYAR BELUM DITERAPKAN*/
ORDER BY
	[CUR].[SUPERCIF]
	,[CUR].[OS_POKOK_PSAK] DESC