SELECT
	[CUR].[TGL_DATA]
	,[CUR].[NOLOAN]
	,[CUR].[NOMORCIF]
	,[CUR].[SUPERCIF]
	,[CUR].[NAMANASABAH]
	,[CUR].[KODECABANG]
	,[CUR].[NAMACABANG]
	,[CUR].[AREA]
	,[CUR].[REGION]
	,[CUR].[DIVISI]
	,[CUR].[PRODUK]
	,[CUR].[PRODUK_DETAIL]
	,[CUR].[KOL_LOAN]
	,[CUR].[KOL_CIF]
	,[CUR].[KOL_SUPERCIF]
	,[CUR].[OS_POKOK_PSAK]
	,[CUR].[OS_POKOK]
FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)] [CUR]
OUTER APPLY (
	SELECT
		SUM([OS_POKOK_PSAK]) [OS_POKOK_PSAK]
	FROM [series].[RCG.LOAN_DAILY.2023-05-31 (FINAL)]
	WHERE [CUR].[SUPERCIF] = [SUPERCIF]
	AND [CUR].[DIVISI] = [DIVISI]
	AND [CUR].[PRODUK] = [PRODUK]
) [SUPERCIF]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [CUR].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [CUR].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-04-30 (FINAL)]
				WHERE [CUR].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M1]
OUTER APPLY (
	SELECT
		COALESCE([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF]) [KOL_SUPERCIF]
	FROM
	(
		VALUES
		(
			(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [CUR].[NOLOAN] = [NOLOAN]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [CUR].[NOMORCIF] = [NOMORCIF]
			)
			,(
				SELECT
					MAX([KOL_SUPERCIF]) [KOL_SUPERCIF]
				FROM [series].[RCG.LOAN_DAILY.2023-03-31 (FINAL)]
				WHERE [CUR].[SUPERCIF] = [SUPERCIF]
			)
		)
	)[TEMP]([BY_NOLOAN], [BY_NOMORCIF], [BY_SUPERCIF])
) [KOL_M2]
WHERE
(
	(
		[CUR].[DIVISI] = 'Konsumer'
		AND [CUR].[PRODUK] = 'Mitraguna & Other'
		AND LEFT([CUR].[KOL_SUPERCIF], 1) IN ('3', '4', '5')
		AND [SUPERCIF].[OS_POKOK_PSAK] >= 200000000.00
	)
	OR
	(
		[CUR].[DIVISI] = 'Mikro'
		AND [CUR].[PRODUK] = 'Non Kur'
		AND LEFT([CUR].[KOL_SUPERCIF], 1) IN ('3', '4', '5')
		AND [SUPERCIF].[OS_POKOK_PSAK] >= 200000000.00
	)
)
AND LEFT([KOL_M1].[KOL_SUPERCIF], 1) IN ('3', '4', '5')
AND LEFT([KOL_M2].[KOL_SUPERCIF], 1) IN ('3', '4', '5')