DECLARE
	@TGL_DATA DATE = '2023-08-01'
	,@TARGET_TABLE_LM VARCHAR(MAX) 
	,@TARGET_TABLE_BEF VARCHAR(MAX) 
	,@TARGET_TABLE_CUR VARCHAR(MAX)
	,@SQL_QUERY VARCHAR(MAX)
	,@POINTER INT = 1
	,@NUM_DAYS INT = 3;

BEGIN TRY	
	CREATE TABLE [compile].[DAILY_PAYMENT.VERTICAL] (
		[INDEX] INTEGER IDENTITY(1, 1)
		,TGL_LM DATE
		,TGL_LD DATE
		,TGL_DATA DATE
		,NOLOAN VARCHAR(255)
		,NOMORCIF VARCHAR(255)
		,SUPERCIF VARCHAR(255)
		,NAMANASABAH VARCHAR(255)
		,KODECABANG VARCHAR(255)
		,NAMACABANG VARCHAR(255)
		,AREA VARCHAR(255)
		,REGION VARCHAR(255)
		,DIVISI VARCHAR(255)
		,PRODUK VARCHAR(255)
		,PRODUK_DETAIL VARCHAR(255)
		,JENISPIUTANGPEMBIAYAAN VARCHAR(255)
		,CYCLE VARCHAR(255)
		,KOL_LOAN_LM VARCHAR(255)
		,KOL_CIF_LM VARCHAR(255)
		,KOL_SUPERCIF_LM VARCHAR(255)
		,KOL_LOAN_LD VARCHAR(255)
		,KOL_CIF_LD VARCHAR(255)
		,KOL_SUPERCIF_LD VARCHAR(255)
		,KOL_LOAN VARCHAR(255)
		,KOL_CIF VARCHAR(255)
		,KOL_SUPERCIF VARCHAR(255)
		,PAY_POKOK DECIMAL(20, 2)
		,PAY_MARGIN DECIMAL(20, 2)
		,PAY_BASIL DECIMAL(20, 2)
		,FLAG VARCHAR(255)
		,KETERANGAN VARCHAR(255)
		,REK_PEMBAYARAN VARCHAR(255)
	);
END TRY
BEGIN CATCH
END CATCH

WHILE @POINTER <= @NUM_DAYS
BEGIN
	
	SET @TARGET_TABLE_LM = (
		SELECT TOP 1
			CONCAT('[', SCHEMA_NAME(SCHEMA_ID), '].[', name, ']') AS NAME
		FROM [sys].[objects]
		WHERE type_desc = 'USER_TABLE'
		AND name LIKE 'RCG.LOAN_DAILY.____-__-__%'
		AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) < @TGL_DATA
			AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) = EOMONTH(DATEADD(MONTH, -1, @TGL_DATA))
		ORDER BY
			TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) DESC
			,CASE
				WHEN name LIKE ('%(FINAL)') THEN 1
				WHEN name LIKE ('%(FOG)') THEN 0.5
				WHEN name LIKE ('%(QC)') THEN -1
				ELSE 0
			END DESC
	);
	
	SET @TARGET_TABLE_BEF = (
		SELECT TOP 1
			CONCAT('[', SCHEMA_NAME(SCHEMA_ID), '].[', name, ']') AS NAME
		FROM [sys].[objects]
		WHERE type_desc = 'USER_TABLE'
		AND name LIKE 'RCG.LOAN_DAILY.____-__-__%'
		AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) < @TGL_DATA
		ORDER BY
			TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) DESC
			,CASE
				WHEN name LIKE ('%(FINAL)') THEN 1
				WHEN name LIKE ('%(FOG)') THEN 0.5
				WHEN name LIKE ('%(QC)') THEN -1
				ELSE 0
			END DESC
	);
	
	SET @TARGET_TABLE_CUR = (
		SELECT TOP 1
			CONCAT('[', SCHEMA_NAME(SCHEMA_ID), '].[', name, ']') AS NAME
		FROM [sys].[objects]
		WHERE type_desc = 'USER_TABLE'
		AND name LIKE 'RCG.LOAN_DAILY.____-__-__%'
		AND TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) <= @TGL_DATA
		ORDER BY
			TRY_CAST(LEFT(REPLACE(name, 'RCG.LOAN_DAILY.', ''), 10) AS DATE) DESC
			,CASE
				WHEN name LIKE ('%(FINAL)') THEN 1
				WHEN name LIKE ('%(FOG)') THEN 0.5
				WHEN name LIKE ('%(QC)') THEN -1
				ELSE 0
			END DESC
	);

	DELETE FROM [compile].[DAILY_PAYMENT.VERTICAL] WHERE [TGL_DATA] = @TGL_DATA AND [FLAG] IN ('ON BALANCE');

	SET @SQL_QUERY = CONCAT(
		'SELECT
			''', EOMONTH(DATEADD(MONTH, -1, @TGL_DATA)), ''' [TGL_LM]
			,[BEFORE].[TGL_DATA] [TGL_LD]
			,''', @TGL_DATA, ''' [TGL_DATA]
			,COALESCE([CURRENT].[NOLOAN], [BEFORE].[NOLOAN]) [NOLOAN]
			,COALESCE([CURRENT].[NOMORCIF], [BEFORE].[NOMORCIF]) [NOMORCIF]
			,COALESCE([CURRENT].[SUPERCIF], [BEFORE].[SUPERCIF]) [SUPERCIF]
			,COALESCE([CURRENT].[NAMANASABAH], [BEFORE].[NAMANASABAH]) [NAMANASABAH]
			,COALESCE([CURRENT].[KODECABANG], [BEFORE].[KODECABANG]) [KODECABANG]
			,COALESCE([CURRENT].[NAMACABANG], [BEFORE].[NAMACABANG]) [NAMACABANG]
			,COALESCE([CURRENT].[AREA], [BEFORE].[AREA]) [AREA]
			,COALESCE([CURRENT].[REGION], [BEFORE].[REGION]) [REGION]
			,COALESCE([CURRENT].[DIVISI], [BEFORE].[DIVISI]) [DIVISI]
			,COALESCE([CURRENT].[PRODUK], [BEFORE].[PRODUK]) [PRODUK]
			,COALESCE([CURRENT].[PRODUK_DETAIL], [BEFORE].[PRODUK_DETAIL]) [PRODUK_DETAIL]
			,COALESCE([CURRENT].[JENISPIUTANGPEMBIAYAAN], [BEFORE].[JENISPIUTANGPEMBIAYAAN]) [JENISPIUTANGPEMBIAYAAN]
			,COALESCE([CURRENT].[CYCLE], [BEFORE].[CYCLE]) [CYCLE]
			,[KOL_LOAN_LM] = [SOURCE].[KOL_LOAN]
			,[KOL_CIF_LM] = COALESCE([SOURCE].[KOL_CIF], [M_1].[KOL_CIF])
			,[KOL_SUPERCIF_LM] = COALESCE([SOURCE].[KOL_SUPERCIF], [M_1].[KOL_SUPERCIF])
			,[BEFORE].[KOL_LOAN] [KOL_LOAN_LD]
			,[BEFORE].[KOL_CIF] [KOL_CIF_LD]
			,[BEFORE].[KOL_SUPERCIF] [KOL_SUPERCIF_LD]
			,COALESCE([CURRENT].[KOL_LOAN], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') [KOL_LOAN]
			,COALESCE([CURRENT].[KOL_CIF], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') [KOL_CIF]
			,COALESCE([CURRENT].[KOL_SUPERCIF], [CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') [KOL_SUPERCIF]
			,[dbo].[fx_common_zerofy](COALESCE(CASE
					WHEN [BEFORE].[KOL_SUPERCIF] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [BEFORE].[OS_POKOK] - [CURRENT].[OS_POKOK]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL AND COALESCE([CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') IN (''Lunas'') THEN [BEFORE].[OS_POKOK]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL AND COALESCE([CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') IN (''EKSEKUSI WO'') THEN [BEFORE].[OS_POKOK] - [CHECK_WO].[EKSEKUSI_WO]
					ELSE 0.00
				END, 0.00)) [PAY_POKOK]
			,[dbo].[fx_common_zerofy](COALESCE(CASE
					WHEN [BEFORE].[KOL_SUPERCIF] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [BEFORE].[OS_MARGIN] - [CURRENT].[OS_MARGIN]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL THEN 0.00
					ELSE 0.00
				END, 0.00)) [PAY_MARGIN]
			,[dbo].[fx_common_zerofy](COALESCE(CASE
					WHEN [BEFORE].[REALISASI_BAGIHASIL] IS NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[REALISASI_BAGIHASIL]
					WHEN [BEFORE].[REALISASI_BAGIHASIL] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[REALISASI_BAGIHASIL] - [BEFORE].[REALISASI_BAGIHASIL]
					WHEN [CURRENT].[KOL_SUPERCIF] IS NULL THEN 0.00
				END, 0.00)) [PAY_BASIL]
			,''ON BALANCE'' [FLAG]
		FROM ', @TARGET_TABLE_BEF, ' [BEFORE]
		LEFT JOIN ', @TARGET_TABLE_CUR, ' [CURRENT]
			ON [BEFORE].[NOLOAN] = [CURRENT].[NOLOAN]
		LEFT JOIN ', @TARGET_TABLE_LM, ' [SOURCE]
			ON [BEFORE].[NOLOAN] = [SOURCE].[NOLOAN]
		OUTER APPLY (
			SELECT
				COALESCE(MAX([BY_LOAN]), MAX([BY_CIF])) [KOL_CIF]
				,COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]) , MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
			FROM (
				SELECT
					CASE WHEN [NOLOAN] IN (
						SELECT
							[NOLOAN_LAMA]
						FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
						WHERE [NOLOAN_BARU] = [BEFORE].[NOLOAN]
						AND [NOCIF_BARU] = [BEFORE].[NOMORCIF]
						AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
					) OR [NOLOAN] = COALESCE([BEFORE].[NOLOAN], ''X'') THEN [KOL_SUPERCIF]
					WHEN [BEFORE].[DIVISI] IN (''Pawning'') THEN ''1'' END [BY_LOAN]
					,CASE WHEN [NOMORCIF] = [BEFORE].[NOMORCIF] THEN [KOL_SUPERCIF] END [BY_CIF]
					,[KOL_SUPERCIF] [BY_SUPERCIF]
				FROM ', @TARGET_TABLE_LM, '
				WHERE
					(
						[BEFORE].[SUPERCIF] = [SUPERCIF]
					)
					AND
					(
						(
							[BEFORE].[DIVISI] IN (''Hasanah Card'')
							AND [DIVISI] IN (''Hasanah Card'')
						)
						OR
						(
							[BEFORE].[DIVISI] NOT IN (''Hasanah Card'')
							AND [DIVISI] NOT IN (''Hasanah Card'')
						)
					)
			) [SUB]
		) [M_1]
		OUTER APPLY (
			SELECT
				MAX(CASE WHEN [NOLOAN_BARU] IS NOT NULL THEN ''BUKA TUTUP'' END) [FLAG]
			FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
			WHERE [NOLOAN_LAMA] = [CURRENT].[NOLOAN]
			AND [NOCIF_LAMA] = [CURRENT].[NOMORCIF]
			AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'', ''EKSEKUSI WO'')
		) [CHECK_BUKA_TUTUP]
		OUTER APPLY (
			SELECT
				MAX(CASE WHEN [NOLOAN_WO] IS NOT NULL THEN ''EKSEKUSI WO'' END) [FLAG]
				,SUM(CASE WHEN [NOLOAN_WO] IS NOT NULL THEN [BAKI_DEBET_IDR] END) [EKSEKUSI_WO]
			FROM [mapping].[PORTOFOLIO_ONBS.DATABASE.JOIN.EKSEKUSI_WO]
			WHERE [NOLOAN] = [CURRENT].[NOLOAN]
			AND [NOCIF] = [CURRENT].[NOMORCIF]
		) [CHECK_WO]
		WHERE
			[dbo].[fx_common_zerofy](COALESCE(CASE
				WHEN [BEFORE].[KOL_SUPERCIF] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [BEFORE].[OS_POKOK] - [CURRENT].[OS_POKOK]
				WHEN [CURRENT].[KOL_SUPERCIF] IS NULL AND COALESCE([CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') IN (''Lunas'') THEN [BEFORE].[OS_POKOK]
				WHEN [CURRENT].[KOL_SUPERCIF] IS NULL AND COALESCE([CHECK_BUKA_TUTUP].[FLAG], [CHECK_WO].[FLAG], ''Lunas'') IN (''EKSEKUSI WO'') THEN [BEFORE].[OS_POKOK] - [CHECK_WO].[EKSEKUSI_WO]
				ELSE 0.00
			END, 0.00))
		+ [dbo].[fx_common_zerofy](COALESCE(CASE
				WHEN [BEFORE].[KOL_SUPERCIF] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [BEFORE].[OS_MARGIN] - [CURRENT].[OS_MARGIN]
				WHEN [CURRENT].[KOL_SUPERCIF] IS NULL THEN 0.00
				ELSE 0.00
			END, 0.00))
		+ [dbo].[fx_common_zerofy](COALESCE(CASE
				WHEN [BEFORE].[REALISASI_BAGIHASIL] IS NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[REALISASI_BAGIHASIL]
				WHEN [BEFORE].[REALISASI_BAGIHASIL] IS NOT NULL AND [CURRENT].[KOL_SUPERCIF] IS NOT NULL THEN [CURRENT].[REALISASI_BAGIHASIL] - [BEFORE].[REALISASI_BAGIHASIL]
				WHEN [CURRENT].[KOL_SUPERCIF] IS NULL THEN 0.00
			END, 0.00)) > 0.00
		AND COALESCE([CURRENT].[DIVISI], [BEFORE].[DIVISI]) NOT IN (''Hasanah Card'');'
	);
	
	BEGIN TRY
		INSERT INTO [compile].[DAILY_PAYMENT.VERTICAL] (
			[TGL_LM]
			,[TGL_LD]
			,[TGL_DATA]
			,[NOLOAN]
			,[NOMORCIF]
			,[SUPERCIF]
			,[NAMANASABAH]
			,[KODECABANG]
			,[NAMACABANG]
			,[AREA]
			,[REGION]
			,[DIVISI]
			,[PRODUK]
			,[PRODUK_DETAIL]
			,[JENISPIUTANGPEMBIAYAAN]
			,[CYCLE]
			,[KOL_LOAN_LM]
			,[KOL_CIF_LM]
			,[KOL_SUPERCIF_LM]
			,[KOL_LOAN_LD]
			,[KOL_CIF_LD]
			,[KOL_SUPERCIF_LD]
			,[KOL_LOAN]
			,[KOL_CIF]
			,[KOL_SUPERCIF]
			,[PAY_POKOK]
			,[PAY_MARGIN]
			,[PAY_BASIL]
			,[FLAG]
		)
		EXEC(@SQL_QUERY);
	END TRY
	BEGIN CATCH
		PRINT CONCAT('ERROR: ', ERROR_MESSAGE());
	END CATCH
	
-- 	SET @SQL_QUERY = CONCAT(
-- 		'WITH CTE AS (
-- 			SELECT
-- 				*
-- 			FROM [compile].[DAILY_PAYMENT.VERTICAL]
-- 			WHERE [TGL_DATA] = ''', @TGL_DATA, '''
-- 		) UPDATE CTE
-- 		SET
-- 			[KOL_LOAN_LM] = [SOURCE].[KOL_LOAN]
-- 			,[KOL_CIF_LM] = COALESCE([SOURCE].[KOL_CIF], [M_1].[KOL_CIF])
-- 			,[KOL_SUPERCIF_LM] = COALESCE([SOURCE].[KOL_SUPERCIF], [M_1].[KOL_SUPERCIF])
-- 		FROM CTE [TARGET]
-- 		LEFT JOIN ', @TARGET_TABLE_LM, ' [SOURCE]
-- 			ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
-- 		OUTER APPLY (
-- 			SELECT
-- 				COALESCE(MAX([BY_LOAN]), MAX([BY_CIF]) , MAX([BY_SUPERCIF])) [KOL_SUPERCIF]
-- 			FROM (
-- 				SELECT
-- 					CASE WHEN [NOLOAN] IN (
-- 						SELECT
-- 							[NOLOAN_LAMA]
-- 						FROM [mapping].[PORTOFOLIO_ONBS.COMPILE.JOIN.REKAP_NOLOAN.MUTASI_NOLOAN]
-- 						WHERE [NOLOAN_BARU] = [TARGET].[NOLOAN]
-- 						AND [NOCIF_BARU] = [TARGET].[NOMORCIF]
-- 						AND COALESCE([KETERANGAN], ''X'') NOT IN (''Invalid'')
-- 					) OR [NOLOAN] = COALESCE([TARGET].[NOLOAN], ''X'') THEN [KOL_SUPERCIF]
-- 					WHEN [TARGET].[DIVISI] IN (''Pawning'') THEN ''1'' END [BY_LOAN]
-- 					,CASE WHEN [NOMORCIF] = [TARGET].[NOMORCIF] THEN [KOL_SUPERCIF] END [BY_CIF]
-- 					,[KOL_SUPERCIF] [BY_SUPERCIF]
-- 				FROM ', @TARGET_TABLE_LM, '
-- 				WHERE
-- 					(
-- 						[TARGET].[SUPERCIF] = [SUPERCIF]
-- 					)
-- 					AND
-- 					(
-- 						(
-- 							[TARGET].[DIVISI] IN (''Hasanah Card'')
-- 							AND [DIVISI] IN (''Hasanah Card'')
-- 						)
-- 						OR
-- 						(
-- 							[TARGET].[DIVISI] NOT IN (''Hasanah Card'')
-- 							AND [DIVISI] NOT IN (''Hasanah Card'')
-- 						)
-- 					)
-- 			) [SUB]
-- 		) [M_1];'
-- 	);
-- 	
-- 	BEGIN TRY
-- 		EXEC(@SQL_QUERY);
-- 	END TRY
-- 	BEGIN CATCH
-- 		PRINT CONCAT('ERROR: ', ERROR_MESSAGE());
-- 	END CATCH
	
	SET @POINTER = @POINTER + 1;
	SET @TGL_DATA = DATEADD(DAY, 1, @TGL_DATA);
END