TRUNCATE TABLE [MAIN].[PORTOFOLIO.ONBS.DAILY];

---------------------------------------------------------------
/*
MERGE [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
USING
(
	SELECT
		TRY_CAST(FICMISDATE AS DATE) AS TGL_DATA
		,NOLOAN AS NOLOAN
		,NOMORCIF AS NOMORCIF
		,NAMALENGKAP AS NAMANASABAH
		,KODECABANGBARU AS KODECABANG
		,NAMACABANG AS NAMACABANG
		,DIVISI AS DIVISI
		,LOANTYPE AS LOANTYPE
		,JENISPIUTANGPEMBIAYAAN AS JENISPIUTANGPEMBIAYAAN
		,MAX(TRY_CAST(DAYPASTDUE AS INTEGER)) AS DPD
		,MAX(TRY_CAST(TGLPENCAIRAN AS DATE)) AS TANGGAL_CAIR
		,MAX(TRY_CAST(TGLJTTEMPO AS DATE)) AS TANGGAL_JATUH_TEMPO
		,MAX(KOLBSM) AS KOL_LOAN
		,MAX(KOLCIF) AS KOL_CIF
		,SUM(TRY_CAST(OSPOKOKCONVERSION AS DECIMAL(20, 2))) AS OS_POKOK
		,SUM(TRY_CAST(OSMARGINCONVERSION AS DECIMAL(20, 2))) AS OS_MARGIN
		,SUM(TRY_CAST(REALISASI_BAGIHASIL AS DECIMAL(20, 2))) AS REALISASI_BAGIHASIL
		,SUM(TRY_CAST(PROYEKSI_BAGIHASIL AS DECIMAL(20, 2))) AS PROYEKSI_BAGIHASIL
		,SUM(TRY_CAST(TUNGGAKANPOKOKCONVERSION AS DECIMAL(20, 2))) AS TUNGGAKAN_POKOK
		,SUM(TRY_CAST(TUNGGAKANMARGINCONVERSION AS DECIMAL(20, 2))) AS TUNGGAKAN_MARGIN
		,COUNT(1) AS ACCT
	FROM [SOURCE].[IFOIS.LOAN_DAILY]
	GROUP BY
		TRY_CAST(FICMISDATE AS DATE)
		,NOLOAN
		,NOMORCIF
		,NAMALENGKAP
		,KODECABANGBARU
		,NAMACABANG
		,DIVISI
		,LOANTYPE
		,JENISPIUTANGPEMBIAYAAN
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
	AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
WHEN MATCHED THEN UPDATE
SET
	TGL_DATA = COALESCE([SOURCE].[TGL_DATA], [TARGET].[TGL_DATA])
	,NOLOAN = COALESCE([SOURCE].[NOLOAN], [TARGET].[NOLOAN])
	,NOMORCIF = COALESCE([SOURCE].[NOMORCIF], [TARGET].[NOMORCIF])
	,NAMANASABAH = COALESCE([SOURCE].[NAMANASABAH], [TARGET].[NAMANASABAH])
	,KODECABANG = COALESCE([SOURCE].[KODECABANG], [TARGET].[KODECABANG])
	,NAMACABANG = COALESCE([SOURCE].[NAMACABANG], [TARGET].[NAMACABANG])
	,DIVISI = COALESCE([SOURCE].[DIVISI], [TARGET].[DIVISI])
	,LOANTYPE = COALESCE([SOURCE].[LOANTYPE], [TARGET].[LOANTYPE])
	,JENISPIUTANGPEMBIAYAAN = COALESCE([SOURCE].[JENISPIUTANGPEMBIAYAAN], [TARGET].[JENISPIUTANGPEMBIAYAAN])
	,DPD = COALESCE([SOURCE].[DPD], [TARGET].[DPD])
	,TANGGAL_CAIR = COALESCE([SOURCE].[TANGGAL_CAIR], [TARGET].[TANGGAL_CAIR])
	,TANGGAL_JATUH_TEMPO = COALESCE([SOURCE].[TANGGAL_JATUH_TEMPO], [TARGET].[TANGGAL_JATUH_TEMPO])
	,KOL_LOAN = COALESCE([SOURCE].[KOL_LOAN], [TARGET].[KOL_LOAN])
	,KOL_CIF = COALESCE([SOURCE].[KOL_CIF], [TARGET].[KOL_CIF])
	,OS_POKOK = COALESCE([SOURCE].[OS_POKOK], [TARGET].[OS_POKOK])
	,OS_MARGIN = COALESCE([SOURCE].[OS_MARGIN], [TARGET].[OS_MARGIN])
	,REALISASI_BAGIHASIL = COALESCE([SOURCE].[REALISASI_BAGIHASIL], [TARGET].[REALISASI_BAGIHASIL])
	,PROYEKSI_BAGIHASIL = COALESCE([SOURCE].[PROYEKSI_BAGIHASIL], [TARGET].[PROYEKSI_BAGIHASIL])
	,TUNGGAKAN_POKOK = COALESCE([SOURCE].[TUNGGAKAN_POKOK], [TARGET].[TUNGGAKAN_POKOK])
	,TUNGGAKAN_MARGIN = COALESCE([SOURCE].[TUNGGAKAN_MARGIN], [TARGET].[TUNGGAKAN_MARGIN])
	,ACCT = COALESCE([SOURCE].[ACCT], [TARGET].[ACCT])
WHEN NOT MATCHED BY TARGET THEN
INSERT
	(
		TGL_DATA
		,NOLOAN
		,NOMORCIF
		,NAMANASABAH
		,KODECABANG
		,NAMACABANG
		,DIVISI
		,LOANTYPE
		,JENISPIUTANGPEMBIAYAAN
		,DPD
		,TANGGAL_CAIR
		,TANGGAL_JATUH_TEMPO
		,KOL_LOAN
		,KOL_CIF
		,OS_POKOK
		,OS_MARGIN
		,REALISASI_BAGIHASIL
		,PROYEKSI_BAGIHASIL
		,TUNGGAKAN_POKOK
		,TUNGGAKAN_MARGIN
		,ACCT
	)
VALUES
(
	[SOURCE].TGL_DATA
	,[SOURCE].NOLOAN
	,[SOURCE].NOMORCIF
	,[SOURCE].NAMANASABAH
	,[SOURCE].KODECABANG
	,[SOURCE].NAMACABANG
	,[SOURCE].DIVISI
	,[SOURCE].LOANTYPE
	,[SOURCE].JENISPIUTANGPEMBIAYAAN
	,[SOURCE].DPD
	,[SOURCE].TANGGAL_CAIR
	,[SOURCE].TANGGAL_JATUH_TEMPO
	,[SOURCE].KOL_LOAN
	,[SOURCE].KOL_CIF
	,[SOURCE].OS_POKOK
	,[SOURCE].OS_MARGIN
	,[SOURCE].REALISASI_BAGIHASIL
	,[SOURCE].PROYEKSI_BAGIHASIL
	,[SOURCE].TUNGGAKAN_POKOK
	,[SOURCE].TUNGGAKAN_MARGIN
	,[SOURCE].ACCT
);

---------------------------------------------------------------

MERGE [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
USING
(
	SELECT
		TRY_CAST(FICMISDATE AS DATE) AS TGL_DATA
		,NOLOAN AS NOLOAN
		,NOMORCIF AS NOMORCIF
		,NAMALENGKAP AS NAMANASABAH
		,KODECABANGBARU AS KODECABANG
		,NAMACABANG AS NAMACABANG
		,DIVISI AS DIVISI
		,'OTO' AS PRODUK
		,'OTO JFAST' AS PRODUK_DETAIL
		,LOANTYPE AS LOANTYPE
		,JENISPIUTANGPEMBIAYAAN AS JENISPIUTANGPEMBIAYAAN
		,MAX(TRY_CAST(DAYPASTDUE AS INTEGER)) AS DPD
		,MAX(TRY_CAST(TGLPENCAIRAN AS DATE)) AS TANGGAL_CAIR
		,MAX(TRY_CAST(TGLJTTEMPO AS DATE)) AS TANGGAL_JATUH_TEMPO
		,MAX(KOLBSM) AS KOL_LOAN
		,MAX(KOLCIF) AS KOL_CIF
		,SUM(TRY_CAST(OSPOKOKCONVERSION AS DECIMAL(20, 2))) AS OS_POKOK
		,SUM(TRY_CAST(OSMARGINCONVERSION AS DECIMAL(20, 2))) AS OS_MARGIN
		,SUM(TRY_CAST(REALISASI_BAGIHASIL AS DECIMAL(20, 2))) AS REALISASI_BAGIHASIL
		,SUM(TRY_CAST(PROYEKSI_BAGIHASIL AS DECIMAL(20, 2))) AS PROYEKSI_BAGIHASIL
		,SUM(TRY_CAST(TUNGGAKANPOKOKCONVERSION AS DECIMAL(20, 2))) AS TUNGGAKAN_POKOK
		,SUM(TRY_CAST(TUNGGAKANMARGINCONVERSION AS DECIMAL(20, 2))) AS TUNGGAKAN_MARGIN
		,COUNT(1) AS ACCT
	FROM [SOURCE].[MIS.IFOS_JFAST]
	WHERE TRY_CAST(FICMISDATE AS DATE) IS NOT NULL
	GROUP BY
		TRY_CAST(FICMISDATE AS DATE)
		,NOLOAN
		,NOMORCIF
		,NAMALENGKAP
		,KODECABANGBARU
		,NAMACABANG
		,DIVISI
		,LOANTYPE
		,JENISPIUTANGPEMBIAYAAN
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
	AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
WHEN MATCHED THEN UPDATE
SET
	TGL_DATA = COALESCE([SOURCE].[TGL_DATA], [TARGET].[TGL_DATA])
	,NOLOAN = COALESCE([SOURCE].[NOLOAN], [TARGET].[NOLOAN])
	,NOMORCIF = COALESCE([SOURCE].[NOMORCIF], [TARGET].[NOMORCIF])
	,NAMANASABAH = COALESCE([SOURCE].[NAMANASABAH], [TARGET].[NAMANASABAH])
	,KODECABANG = COALESCE([SOURCE].[KODECABANG], [TARGET].[KODECABANG])
	,NAMACABANG = COALESCE([SOURCE].[NAMACABANG], [TARGET].[NAMACABANG])
	,DIVISI = COALESCE([SOURCE].[DIVISI], [TARGET].[DIVISI])
	,PRODUK = COALESCE([SOURCE].[PRODUK], [TARGET].[PRODUK])
	,PRODUK_DETAIL = COALESCE([SOURCE].[PRODUK_DETAIL], [TARGET].[PRODUK_DETAIL])
	,LOANTYPE = COALESCE([SOURCE].[LOANTYPE], [TARGET].[LOANTYPE])
	,JENISPIUTANGPEMBIAYAAN = COALESCE([SOURCE].[JENISPIUTANGPEMBIAYAAN], [TARGET].[JENISPIUTANGPEMBIAYAAN])
	,DPD = COALESCE([SOURCE].[DPD], [TARGET].[DPD])
	,TANGGAL_CAIR = COALESCE([SOURCE].[TANGGAL_CAIR], [TARGET].[TANGGAL_CAIR])
	,TANGGAL_JATUH_TEMPO = COALESCE([SOURCE].[TANGGAL_JATUH_TEMPO], [TARGET].[TANGGAL_JATUH_TEMPO])
	,KOL_LOAN = COALESCE([SOURCE].[KOL_LOAN], [TARGET].[KOL_LOAN])
	,KOL_CIF = COALESCE([SOURCE].[KOL_CIF], [TARGET].[KOL_CIF])
	,OS_POKOK = COALESCE([SOURCE].[OS_POKOK], [TARGET].[OS_POKOK])
	,OS_MARGIN = COALESCE([SOURCE].[OS_MARGIN], [TARGET].[OS_MARGIN])
	,REALISASI_BAGIHASIL = COALESCE([SOURCE].[REALISASI_BAGIHASIL], [TARGET].[REALISASI_BAGIHASIL])
	,PROYEKSI_BAGIHASIL = COALESCE([SOURCE].[PROYEKSI_BAGIHASIL], [TARGET].[PROYEKSI_BAGIHASIL])
	,TUNGGAKAN_POKOK = COALESCE([SOURCE].[TUNGGAKAN_POKOK], [TARGET].[TUNGGAKAN_POKOK])
	,TUNGGAKAN_MARGIN = COALESCE([SOURCE].[TUNGGAKAN_MARGIN], [TARGET].[TUNGGAKAN_MARGIN])
	,ACCT = COALESCE([SOURCE].[ACCT], [TARGET].[ACCT])
WHEN NOT MATCHED BY TARGET THEN
INSERT
	(
		TGL_DATA
		,NOLOAN
		,NOMORCIF
		,NAMANASABAH
		,KODECABANG
		,NAMACABANG
		,DIVISI
		,PRODUK
		,PRODUK_DETAIL
		,LOANTYPE
		,JENISPIUTANGPEMBIAYAAN
		,DPD
		,TANGGAL_CAIR
		,TANGGAL_JATUH_TEMPO
		,KOL_LOAN
		,KOL_CIF
		,OS_POKOK
		,OS_MARGIN
		,REALISASI_BAGIHASIL
		,PROYEKSI_BAGIHASIL
		,TUNGGAKAN_POKOK
		,TUNGGAKAN_MARGIN
		,ACCT
	)
VALUES
(
	[SOURCE].TGL_DATA
	,[SOURCE].NOLOAN
	,[SOURCE].NOMORCIF
	,[SOURCE].NAMANASABAH
	,[SOURCE].KODECABANG
	,[SOURCE].NAMACABANG
	,[SOURCE].DIVISI
	,[SOURCE].PRODUK
	,[SOURCE].PRODUK_DETAIL
	,[SOURCE].LOANTYPE
	,[SOURCE].JENISPIUTANGPEMBIAYAAN
	,[SOURCE].DPD
	,[SOURCE].TANGGAL_CAIR
	,[SOURCE].TANGGAL_JATUH_TEMPO
	,[SOURCE].KOL_LOAN
	,[SOURCE].KOL_CIF
	,[SOURCE].OS_POKOK
	,[SOURCE].OS_MARGIN
	,[SOURCE].REALISASI_BAGIHASIL
	,[SOURCE].PROYEKSI_BAGIHASIL
	,[SOURCE].TUNGGAKAN_POKOK
	,[SOURCE].TUNGGAKAN_MARGIN
	,[SOURCE].ACCT
);

---------------------------------------------------------------

MERGE [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
USING
(
	SELECT
		TRY_CAST(FILE_DATE AS DATE) AS TGL_DATA
		,CARDNO AS NOLOAN
		,RIGHT(CUSTNO, 15) AS NOMORCIF
		,SHORT_NAME AS NAMANASABAH
		,'ID0010001' AS KODECABANG
		,'KANTOR PUSAT' AS NAMACABANG
		,'Hasanah Card' AS DIVISI
		,[JENIS] AS PRODUK
		,[TYPE] AS PRODUK_DETAIL
		,'HC0001' AS LOANTYPE
		,'Qard' AS JENISPIUTANGPEMBIAYAAN
		,MAX(TRY_CAST(
			CASE
				WHEN [DPD] = '0' THEN 0
				ELSE (
					CASE
						WHEN RIGHT([FILE_DATE], 2) < CYCLE THEN RIGHT([FILE_DATE], 2) + DATEPART(DAY, EOMONTH(DATEADD(MONTH, -1, [FILE_DATE])))
						ELSE RIGHT([FILE_DATE], 2)
					END
					)	
					- [CYCLE] + COALESCE(NULLIF([DPD], 'XDY'), 0)
				END
		 AS INTEGER)) AS DPD
		,MAX(TRY_CAST(OPDT AS DATE)) AS TANGGAL_CAIR
		,MAX(
			CASE
				WHEN GOL = 'GOL_01' THEN '1'
				WHEN GOL = 'GOL_02' AND BUCKET = '02_XDY' THEN '2A'
				WHEN GOL = 'GOL_02' AND BUCKET = '03_D30' THEN '2B'
				WHEN GOL = 'GOL_02' AND BUCKET = '04_D60' THEN '2C'
				WHEN GOL = 'GOL_03' AND
					(CASE WHEN RIGHT([FILE_DATE], 2) < CYCLE THEN RIGHT([FILE_DATE], 2) + DATEPART(DAY, EOMONTH(DATEADD(MONTH, -1, [FILE_DATE]))) ELSE RIGHT([FILE_DATE], 2) END) <= 10 THEN '3A'
				WHEN GOL = 'GOL_03' AND
					(CASE WHEN RIGHT([FILE_DATE], 2) < CYCLE THEN RIGHT([FILE_DATE], 2) + DATEPART(DAY, EOMONTH(DATEADD(MONTH, -1, [FILE_DATE]))) ELSE RIGHT([FILE_DATE], 2) END) <= 20 THEN '3B'
				WHEN GOL = 'GOL_03' AND
					(CASE WHEN RIGHT([FILE_DATE], 2) < CYCLE THEN RIGHT([FILE_DATE], 2) + DATEPART(DAY, EOMONTH(DATEADD(MONTH, -1, [FILE_DATE]))) ELSE RIGHT([FILE_DATE], 2) END) > 20 THEN '3C'
				WHEN GOL = 'GOL_04' AND BUCKET = '06_120' THEN '4A'
				WHEN GOL = 'GOL_04' AND
					(CASE WHEN RIGHT([FILE_DATE], 2) < CYCLE THEN RIGHT([FILE_DATE], 2) + DATEPART(DAY, EOMONTH(DATEADD(MONTH, -1, [FILE_DATE]))) ELSE RIGHT([FILE_DATE], 2) END) <= 15 THEN '4B'
				WHEN GOL = 'GOL_04' AND
					(CASE WHEN RIGHT([FILE_DATE], 2) < CYCLE THEN RIGHT([FILE_DATE], 2) + DATEPART(DAY, EOMONTH(DATEADD(MONTH, -1, [FILE_DATE]))) ELSE RIGHT([FILE_DATE], 2) END) > 15 THEN '4C'
				WHEN GOL = 'GOL_05' THEN '5'
				ELSE CONCAT(RIGHT([GOL], 1), 'A')
			END
		) AS KOL_LOAN
		,SUM(TRY_CAST(MLAP AS DECIMAL(20, 2))) AS OS_POKOK
		,SUM(TRY_CAST(rtlfeesvc AS DECIMAL(20, 2))) + SUM(TRY_CAST(cshfeesvc AS DECIMAL(20, 2))) AS OS_MARGIN
		,COUNT(1) AS ACCT
	FROM [SOURCE].[CARDLINK.LOAN_DAILY]
	WHERE ([PB] NOT IN ('A', 'G', 'I', 'K', 'O', 'Z') OR [PB] IS NULL)
	AND [POSTFLG] IN ('PP')
	AND TRY_CAST([MLAP] AS DECIMAL(20, 2)) > 0.00
	GROUP BY
		TRY_CAST(FILE_DATE AS DATE)
		,CARDNO
		,RIGHT(CUSTNO, 15)
		,SHORT_NAME
		,[JENIS]
		,[TYPE]
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
	AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
WHEN MATCHED THEN UPDATE
SET
	TGL_DATA = COALESCE([SOURCE].[TGL_DATA], [TARGET].[TGL_DATA])
	,NOLOAN = COALESCE([SOURCE].[NOLOAN], [TARGET].[NOLOAN])
	,NOMORCIF = COALESCE([SOURCE].[NOMORCIF], [TARGET].[NOMORCIF])
	,NAMANASABAH = COALESCE([SOURCE].[NAMANASABAH], [TARGET].[NAMANASABAH])
	,KODECABANG = COALESCE([SOURCE].[KODECABANG], [TARGET].[KODECABANG])
	,NAMACABANG = COALESCE([SOURCE].[NAMACABANG], [TARGET].[NAMACABANG])
	,DIVISI = COALESCE([SOURCE].[DIVISI], [TARGET].[DIVISI])
	,PRODUK = COALESCE([SOURCE].[PRODUK], [TARGET].[PRODUK])
	,PRODUK_DETAIL = COALESCE([SOURCE].[PRODUK_DETAIL], [TARGET].[PRODUK_DETAIL])
	,LOANTYPE = COALESCE([SOURCE].[LOANTYPE], [TARGET].[LOANTYPE])
	,JENISPIUTANGPEMBIAYAAN = COALESCE([SOURCE].[JENISPIUTANGPEMBIAYAAN], [TARGET].[JENISPIUTANGPEMBIAYAAN])
	,DPD = COALESCE([SOURCE].[DPD], [TARGET].[DPD])
	,TANGGAL_CAIR = COALESCE([SOURCE].[TANGGAL_CAIR], [TARGET].[TANGGAL_CAIR])
	,KOL_LOAN = COALESCE([SOURCE].[KOL_LOAN], [TARGET].[KOL_LOAN])
	,OS_POKOK = COALESCE([SOURCE].[OS_POKOK], [TARGET].[OS_POKOK])
	,OS_MARGIN = COALESCE([SOURCE].[OS_MARGIN], [TARGET].[OS_MARGIN])
	,ACCT = COALESCE([SOURCE].[ACCT], [TARGET].[ACCT])
WHEN NOT MATCHED BY TARGET THEN
INSERT
	(
		TGL_DATA
		,NOLOAN
		,NOMORCIF
		,NAMANASABAH
		,KODECABANG
		,NAMACABANG
		,DIVISI
		,PRODUK
		,PRODUK_DETAIL
		,LOANTYPE
		,JENISPIUTANGPEMBIAYAAN
		,DPD
		,TANGGAL_CAIR
		,KOL_LOAN
		,OS_POKOK
		,OS_MARGIN
		,ACCT
	)
VALUES
(
	[SOURCE].TGL_DATA
	,[SOURCE].NOLOAN
	,[SOURCE].NOMORCIF
	,[SOURCE].NAMANASABAH
	,[SOURCE].KODECABANG
	,[SOURCE].NAMACABANG
	,[SOURCE].DIVISI
	,[SOURCE].PRODUK
	,[SOURCE].PRODUK_DETAIL
	,[SOURCE].LOANTYPE
	,[SOURCE].JENISPIUTANGPEMBIAYAAN
	,[SOURCE].DPD
	,[SOURCE].TANGGAL_CAIR
	,[SOURCE].KOL_LOAN
	,[SOURCE].OS_POKOK
	,[SOURCE].OS_MARGIN
	,[SOURCE].ACCT
);
*/

---------------------------------------------------------------

/*
MERGE [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
USING (
	SELECT
		[periodeData] [TGL_DATA]
		,[noRekening] [NOLOAN]
		,COALESCE([noCIF_Legacy], [noCIF]) [NOMORCIF]
		,[noCIF] [SUPERCIF]
		,[namaNasabah] [NAMANASABAH]
		,[cabangBSI] [KODECABANG]
		,[segmenBSI] [DIVISI]
		,[namaProdukBSI] [PRODUK]
		,COALESCE([subProduct1], [subProduct2]) [PRODUK_DETAIL]
		,[kodeProduk] [LOANTYPE]
		,MAX([tunggakanHari]) [DPD]
		,MAX([tanggalBuka]) [TANGGAL_CAIR]
		,MAX([tanggalTutup]) [TANGGAL_JATUH_TEMPO]
		,[kol_rek] [KOL_LOAN]
		,[kolektibilitas] [KOL_SUPERCIF]
		,SUM([sisaPokokPSAK]) [OS_POKOK_PSAK]
		,SUM([sisaPokok]) [OS_POKOK]
		,SUM([sisaMargin]) [OS_MARGIN]
		,SUM([realisasiBagiHasil]) [REALISASI_BAGIHASIL]
		,SUM([proyeksiBagiHasil]) [PROYEKSI_BAGIHASIL]
		,SUM([tunggakanPokok]) [TUNGGAKAN_POKOK]
		,SUM([tunggakanMargin]) [TUNGGAKAN_MARGIN]
		,SUM([CKPN]) [CKPN]
		,COUNT(1) [ACCT]
	FROM [series].[DDM.LOAN_DAILY.2021-09-30]
	GROUP BY
		[periodeData]
		,[noRekening]
		,COALESCE([noCIF_Legacy], [noCIF])
		,[noCIF]
		,[namaNasabah]
		,[cabangBSI]
		,[segmenBSI]
		,[namaProdukBSI]
		,COALESCE([subProduct1], [subProduct2])
		,[kodeProduk]
		,[kol_rek]
		,[kolektibilitas]
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
	AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
WHEN MATCHED THEN UPDATE
SET
	[SUPERCIF] = COALESCE([SOURCE].[SUPERCIF], [TARGET].[SUPERCIF])
	,[NAMANASABAH] = COALESCE([SOURCE].[NAMANASABAH], [TARGET].[NAMANASABAH])
	,[KODECABANG] = COALESCE([SOURCE].[KODECABANG], [TARGET].[KODECABANG])
	,[DIVISI] = COALESCE([SOURCE].[DIVISI], [TARGET].[DIVISI])
	,[PRODUK] = COALESCE([SOURCE].[PRODUK], [TARGET].[PRODUK])
	,[PRODUK_DETAIL] = COALESCE([SOURCE].[PRODUK_DETAIL], [TARGET].[PRODUK_DETAIL])
	,[LOANTYPE] = COALESCE([SOURCE].[LOANTYPE], [TARGET].[LOANTYPE])
	,[DPD] = COALESCE([SOURCE].[DPD], [TARGET].[DPD])
	,[TANGGAL_CAIR] = COALESCE([SOURCE].[TANGGAL_CAIR], [TARGET].[TANGGAL_CAIR])
	,[TANGGAL_JATUH_TEMPO] = COALESCE([SOURCE].[TANGGAL_JATUH_TEMPO], [TARGET].[TANGGAL_JATUH_TEMPO])
	,[KOL_LOAN] = COALESCE([SOURCE].[KOL_LOAN], [TARGET].[KOL_LOAN])
	,[KOL_SUPERCIF] = COALESCE([SOURCE].[KOL_SUPERCIF], [TARGET].[KOL_SUPERCIF])
	,[OS_POKOK_PSAK] = COALESCE([SOURCE].[OS_POKOK_PSAK], [TARGET].[OS_POKOK_PSAK])
	,[OS_POKOK] = COALESCE([SOURCE].[OS_POKOK], [TARGET].[OS_POKOK])
	,[OS_MARGIN] = COALESCE([SOURCE].[OS_MARGIN], [TARGET].[OS_MARGIN])
	,[REALISASI_BAGIHASIL] = COALESCE([SOURCE].[REALISASI_BAGIHASIL], [TARGET].[REALISASI_BAGIHASIL])
	,[PROYEKSI_BAGIHASIL] = COALESCE([SOURCE].[PROYEKSI_BAGIHASIL], [TARGET].[PROYEKSI_BAGIHASIL])
	,[TUNGGAKAN_POKOK] = COALESCE([SOURCE].[TUNGGAKAN_POKOK], [TARGET].[TUNGGAKAN_POKOK])
	,[TUNGGAKAN_MARGIN] = COALESCE([SOURCE].[TUNGGAKAN_MARGIN], [TARGET].[TUNGGAKAN_MARGIN])
	,[CKPN] = COALESCE([SOURCE].[CKPN], [TARGET].[CKPN])
	,[ACCT] = COALESCE([SOURCE].[ACCT], [TARGET].[ACCT])
WHEN NOT MATCHED BY TARGET THEN INSERT
(
	[TGL_DATA]
	,[NOLOAN]
	,[NOMORCIF]
	,[SUPERCIF]
	,[NAMANASABAH]
	,[KODECABANG]
	,[DIVISI]
	,[PRODUK]
	,[PRODUK_DETAIL]
	,[LOANTYPE]
	,[DPD]
	,[TANGGAL_CAIR]
	,[TANGGAL_JATUH_TEMPO]
	,[KOL_LOAN]
	,[KOL_SUPERCIF]
	,[OS_POKOK_PSAK]
	,[OS_POKOK]
	,[OS_MARGIN]
	,[REALISASI_BAGIHASIL]
	,[PROYEKSI_BAGIHASIL]
	,[TUNGGAKAN_POKOK]
	,[TUNGGAKAN_MARGIN]
	,[CKPN]
	,[ACCT]
) VALUES (
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[KODECABANG]
	,[SOURCE].[DIVISI]
	,[SOURCE].[PRODUK]
	,[SOURCE].[PRODUK_DETAIL]
	,[SOURCE].[LOANTYPE]
	,[SOURCE].[DPD]
	,[SOURCE].[TANGGAL_CAIR]
	,[SOURCE].[TANGGAL_JATUH_TEMPO]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK_PSAK]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[OS_MARGIN]
	,[SOURCE].[REALISASI_BAGIHASIL]
	,[SOURCE].[PROYEKSI_BAGIHASIL]
	,[SOURCE].[TUNGGAKAN_POKOK]
	,[SOURCE].[TUNGGAKAN_MARGIN]
	,[SOURCE].[CKPN]
	,[SOURCE].[ACCT]
);
*/

MERGE [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
USING (
	SELECT
		[FICMISDATE] [TGL_DATA]
		,[NOLOAN] [NOLOAN]
		,[NOMORCIF] [NOMORCIF]
		,[SUPERCIF_NO] [SUPERCIF]
		,[NAMALENGKAP] [NAMANASABAH]
		,[KODECABANGBARU] [KODECABANG]
		,[NAMACABANG] [NAMACABANG]
		,[DIVISI_FINAL] [DIVISI]
		,MAX([TGLPENCAIRAN]) [TANGGAL_CAIR]
		,[KOL_LOAN_FINAL] [KOL_LOAN]
		,[KOL_CIF_FINAL] [KOL_CIF]
		,[KOL_SUPERCIF_FINAL] [KOL_SUPERCIF]
		,SUM([OSPOKOKCONVERSION]) [OS_POKOK]
		,COUNT(1) [ACCT]
	FROM [source].[FOG.LOAN_DAILY]
	GROUP BY
		[FICMISDATE]
		,[NOLOAN]
		,[NOMORCIF]
		,[SUPERCIF_NO]
		,[NAMALENGKAP]
		,[KODECABANGBARU]
		,[NAMACABANG]
		,[DIVISI_FINAL]
		,[KOL_LOAN_FINAL]
		,[KOL_CIF_FINAL]
		,[KOL_SUPERCIF_FINAL]
) [SOURCE]
	ON [TARGET].[NOLOAN] = [SOURCE].[NOLOAN]
	AND [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
WHEN MATCHED THEN UPDATE
SET
	[SUPERCIF] = COALESCE([SOURCE].[SUPERCIF], [TARGET].[SUPERCIF])
	,[NAMANASABAH] = COALESCE([SOURCE].[NAMANASABAH], [TARGET].[NAMANASABAH])
	,[KODECABANG] = COALESCE([SOURCE].[KODECABANG], [TARGET].[KODECABANG])
	,[NAMACABANG] = COALESCE([SOURCE].[NAMACABANG], [TARGET].[NAMACABANG])
	,[DIVISI] = COALESCE([SOURCE].[DIVISI], [TARGET].[DIVISI])
	,[TANGGAL_CAIR] = COALESCE([SOURCE].[TANGGAL_CAIR], [TARGET].[TANGGAL_CAIR])
	,[KOL_LOAN] = COALESCE([SOURCE].[KOL_LOAN], [TARGET].[KOL_LOAN])
	,[KOL_CIF] = COALESCE([SOURCE].[KOL_CIF], [TARGET].[KOL_CIF])
	,[KOL_SUPERCIF] = COALESCE([SOURCE].[KOL_SUPERCIF], [TARGET].[KOL_SUPERCIF])
	,[OS_POKOK] = COALESCE([SOURCE].[OS_POKOK], [TARGET].[OS_POKOK])
	,[ACCT] = COALESCE([SOURCE].[ACCT], [TARGET].[ACCT])
WHEN NOT MATCHED BY TARGET THEN INSERT
(
	[TGL_DATA]
	,[NOLOAN]
	,[NOMORCIF]
	,[SUPERCIF]
	,[NAMANASABAH]
	,[KODECABANG]
	,[NAMACABANG]
	,[DIVISI]
	,[TANGGAL_CAIR]
	,[KOL_LOAN]
	,[KOL_CIF]
	,[KOL_SUPERCIF]
	,[OS_POKOK]
	,[ACCT]
) VALUES (
	[SOURCE].[TGL_DATA]
	,[SOURCE].[NOLOAN]
	,[SOURCE].[NOMORCIF]
	,[SOURCE].[SUPERCIF]
	,[SOURCE].[NAMANASABAH]
	,[SOURCE].[NAMACABANG]
	,[SOURCE].[DIVISI]
	,[SOURCE].[TANGGAL_CAIR]
	,[SOURCE].[KOL_LOAN]
	,[SOURCE].[KOL_CIF]
	,[SOURCE].[KOL_SUPERCIF]
	,[SOURCE].[OS_POKOK]
	,[SOURCE].[ACCT]
);

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[SUPERCIF] = COALESCE([SOURCE].[SUPERCIF], [TARGET].[SUPERCIF], [TARGET].[NOMORCIF])
FROM [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
LEFT JOIN [mapping].[PORTOFOLIO.ONBS.CIF_DETAIL] [SOURCE]
	ON [TARGET].[NOMORCIF] = [SOURCE].[NOMORCIF]
	AND [SOURCE].[NOMORCIF] != [SOURCE].[SUPERCIF];

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[DIVISI] = [dbo].[fx_adjustment_divisi_bsi]([DIVISI]);

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[DIVISI] = [dbo].[fx_adjustment_divisi_bsi]([DIVISI]);

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[PRODUK] = NULL
	,[PRODUK_DETAIL] = NULL
WHERE
	(
		([DIVISI] IN ('Konsumer') AND [PRODUK] NOT IN ('Griya', 'OTO', 'Pensiun', 'Mitraguna & Other', 'Mitraguna & Others'))
		OR ([DIVISI] IN ('Pawning') AND [PRODUK] NOT IN ('Cicil Emas', 'Gadai Emas'))
		OR ([DIVISI] IN ('SME') AND [PRODUK] NOT IN ('Linkage', 'Non Linkage'))
		OR ([DIVISI] IN ('Mikro') AND [PRODUK] NOT IN ('KUR', 'Non KUR'))
	)
AND [DIVISI] IN ('Konsumer', 'Pawning', 'SME', 'Mikro');

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[DIVISI] = [SOURCE].[DIVISI_BSI]
	,[PRODUK] = [SOURCE].[PRODUK]
	,[PRODUK_DETAIL] = [SOURCE].[PRODUK_DETAIL]
FROM [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
LEFT JOIN [MAPPING].[PORTOFOLIO.MAPPING.LOANTYPE] [SOURCE]
	ON [TARGET].[LOANTYPE] = [SOURCE].[LOANTYPE]
	AND [TARGET].[DIVISI] = [SOURCE].[DIVISI]
WHERE [TARGET].[PRODUK] IS NULL
AND [SOURCE].[LOANTYPE] IS NOT NULL;

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[KOL_LOAN] = COALESCE([KOL_SUPERCIF], [KOL_CIF])
WHERE [KOL_LOAN] IS NULL;

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[KOL_LOAN] = [dbo].[fx_adjustment_kol]([KOL_LOAN], [DPD], [JENISPIUTANGPEMBIAYAAN], [TANGGAL_JATUH_TEMPO], [TGL_DATA], [NOLOAN], [REALISASI_BAGIHASIL], [PROYEKSI_BAGIHASIL]);

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[KOL_CIF] =
		CASE
			WHEN [TARGET].[DIVISI] IN ('Hasanah Card') THEN [TARGET].[KOL_LOAN]
			WHEN [TARGET].[KOL_LOAN] IN ('1') AND [TARGET].[DIVISI] IN ('Pawning') THEN [TARGET].[KOL_LOAN]
			WHEN [TARGET].[KOL_CIF] IS NULL AND [TARGET].[DIVISI] NOT IN ('Hasanah Card', 'Pawning') AND [KOL_REGULER].[KOL] IN ('1') THEN [KOL_REGULER].[KOL]
			WHEN [TARGET].[KOL_CIF] IS NULL THEN (SELECT MAX([KOL]) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL]))
			WHEN [TARGET].[KOL_CIF] IN ('1', '5') THEN [TARGET].[KOL_CIF]
			WHEN LEFT([TARGET].[KOL_CIF], 1) > (SELECT MAX(LEFT([KOL], 1)) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL])) THEN CONCAT(LEFT([TARGET].[KOL_CIF], 1), 'A')
			WHEN LEFT([TARGET].[KOL_CIF], 1) < (SELECT MAX(LEFT([KOL], 1)) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL])) THEN CONCAT(LEFT([TARGET].[KOL_CIF], 1), 'C')
			WHEN LEFT([TARGET].[KOL_CIF], 1) = (SELECT MAX(LEFT([KOL], 1)) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL])) THEN (SELECT MAX([KOL]) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL]))
			ELSE [KOL_LOAN]
		END
FROM [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) AS [KOL]
	FROM [MAIN].[PORTOFOLIO.ONBS.DAILY]
	WHERE [TARGET].[NOMORCIF] = [NOMORCIF]
	AND [DIVISI] NOT IN ('Hasanah Card', 'Pawning')
) [KOL_REGULER]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) AS [KOL]
	FROM [MAIN].[PORTOFOLIO.ONBS.DAILY]
	WHERE [TARGET].[NOMORCIF] = [NOMORCIF]
	AND [DIVISI] IN ('Pawning')
) [KOL_PAWNING];

---------------------------------------------------------------

UPDATE [MAIN].[PORTOFOLIO.ONBS.DAILY]
SET
	[KOL_SUPERCIF] =
		CASE
			WHEN [TARGET].[DIVISI] IN ('Hasanah Card') THEN [TARGET].[KOL_LOAN]
			WHEN [TARGET].[KOL_LOAN] IN ('1') AND [TARGET].[DIVISI] IN ('Pawning') THEN [TARGET].[KOL_LOAN]
			WHEN [TARGET].[KOL_SUPERCIF] IS NULL AND [TARGET].[DIVISI] NOT IN ('Hasanah Card', 'Pawning') AND [KOL_REGULER].[KOL] IN ('1') THEN [KOL_REGULER].[KOL]
			WHEN [TARGET].[KOL_SUPERCIF] IS NULL THEN (SELECT MAX([KOL]) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL]))
			WHEN [TARGET].[KOL_SUPERCIF] IN ('1', '5') THEN [TARGET].[KOL_SUPERCIF]
			WHEN LEFT([TARGET].[KOL_SUPERCIF], 1) > (SELECT MAX(LEFT([KOL], 1)) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL])) THEN CONCAT(LEFT([TARGET].[KOL_SUPERCIF], 1), 'A')
			WHEN LEFT([TARGET].[KOL_SUPERCIF], 1) < (SELECT MAX(LEFT([KOL], 1)) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL])) THEN CONCAT(LEFT([TARGET].[KOL_SUPERCIF], 1), 'C')
			WHEN LEFT([TARGET].[KOL_SUPERCIF], 1) = (SELECT MAX(LEFT([KOL], 1)) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL])) THEN (SELECT MAX([KOL]) FROM (VALUES([KOL_REGULER].[KOL]), ([KOL_PAWNING].[KOL]))[TEMP_TB]([KOL]))
			ELSE [KOL_LOAN]
		END
FROM [MAIN].[PORTOFOLIO.ONBS.DAILY] [TARGET]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) AS [KOL]
	FROM [MAIN].[PORTOFOLIO.ONBS.DAILY]
	WHERE [TARGET].[SUPERCIF] = [SUPERCIF]
	AND [DIVISI] NOT IN ('Hasanah Card', 'Pawning')
) [KOL_REGULER]
OUTER APPLY (
	SELECT
		MAX([KOL_LOAN]) AS [KOL]
	FROM [MAIN].[PORTOFOLIO.ONBS.DAILY]
	WHERE [TARGET].[SUPERCIF] = [SUPERCIF]
	AND [DIVISI] IN ('Pawning')
) [KOL_PAWNING];

---------------------------------------------------------------